-- Staging/disposable DB only, after 001–021. All fixtures roll back.
begin;
create temporary table business_fixture(owner_id uuid,editor_id uuid,viewer_id uuid,outsider_id uuid,workspace_id uuid,site_id uuid,external_id uuid,doc jsonb);
insert into business_fixture values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,null,'{"schemaVersion":1,"templateId":"service-studio-v1","accent":"mint","name":"Test business","headline":"Real business headline","description":"","about":"","location":"","email":"","phone":"","services":[{"title":"Service","description":"Details"}]}'::jsonb);
do $$ begin execute format('grant usage on schema %I to authenticated, anon',(select nspname from pg_namespace where oid=pg_my_temp_schema())); end; $$;
grant select,update on business_fixture to authenticated;
grant select on business_fixture to anon;
insert into auth.users(id) select owner_id from business_fixture union all select editor_id from business_fixture union all select viewer_id from business_fixture union all select outsider_id from business_fixture;
create function pg_temp.business_expect_error(sql text, expected text) returns void language plpgsql as $$
declare caught boolean := false;
begin
  begin execute sql; exception when others then if sqlerrm = expected or (expected='permission' and sqlstate='42501') then caught:=true; else raise; end if; end;
  if not caught then raise exception 'Expected %: %',expected,sql; end if;
end; $$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select owner_id::text from business_fixture),true);
update business_fixture set workspace_id=(select id from public.bz_create_workspace('Business acceptance'));
update business_fixture set site_id=(select id from public.bz_register_site(workspace_id,'Native','native_business','business',null,null,'active',true));
update business_fixture set external_id=(select id from public.bz_register_site(workspace_id,'External','external','business','https://sufianmustafa.com/',null,'active',true));
select public.bz_save_business_draft(workspace_id,site_id,doc,0) from business_fixture;
select pg_temp.business_expect_error(format('select public.bz_save_business_draft(%L,%L,%L,0)',workspace_id,site_id,doc),'bz_conflict') from business_fixture;
select pg_temp.business_expect_error(format('select public.bz_save_business_draft(%L,%L,%L,1)',workspace_id,site_id,doc||'{"accent":"evil"}'::jsonb),'bz_invalid_business_document') from business_fixture;
select pg_temp.business_expect_error(format('select public.bz_save_business_draft(%L,%L,%L,1)',workspace_id,site_id,doc-'name'),'bz_invalid_business_document') from business_fixture;
select pg_temp.business_expect_error(format('select public.bz_save_business_draft(%L,%L,%L,0)',workspace_id,external_id,doc),'bz_not_found') from business_fixture;
select pg_temp.business_expect_error('update public.bizoveya_business_drafts set version=99','permission');
reset role;
insert into public.bizoveya_memberships(workspace_id,user_id,role) select workspace_id,editor_id,'editor' from business_fixture union all select workspace_id,viewer_id,'viewer' from business_fixture;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select editor_id::text from business_fixture),true);
select public.bz_save_business_draft(workspace_id,site_id,doc||'{"headline":"Editor updated"}'::jsonb,1) from business_fixture;
do $$ begin if (select version from public.bizoveya_business_drafts)<>2 then raise exception 'Editor save failed'; end if; end; $$;
select set_config('request.jwt.claim.sub',(select viewer_id::text from business_fixture),true);
do $$ begin if (select count(*) from public.bizoveya_business_drafts)<>1 then raise exception 'Viewer read failed'; end if; end; $$;
select pg_temp.business_expect_error(format('select public.bz_save_business_draft(%L,%L,%L,2)',workspace_id,site_id,doc),'bz_forbidden') from business_fixture;
select set_config('request.jwt.claim.sub',(select outsider_id::text from business_fixture),true);
do $$ begin if exists(select 1 from public.bizoveya_business_drafts) then raise exception 'Cross-tenant draft leaked'; end if; end; $$;
select pg_temp.business_expect_error(format('select public.bz_save_business_draft(%L,%L,%L,2)',workspace_id,site_id,doc),'bz_forbidden') from business_fixture;
reset role;
delete from public.bizoveya_memberships where user_id=(select editor_id from business_fixture);
set local role authenticated;
select set_config('request.jwt.claim.sub',(select editor_id::text from business_fixture),true);
do $$ begin if exists(select 1 from public.bizoveya_business_drafts) then raise exception 'Revoked editor retained access'; end if; end; $$;
select pg_temp.business_expect_error(format('select public.bz_save_business_draft(%L,%L,%L,2)',workspace_id,site_id,doc),'bz_forbidden') from business_fixture;
reset role;
set local role anon;
select pg_temp.business_expect_error('select * from public.bizoveya_business_drafts','permission');
select pg_temp.business_expect_error(format('select public.bz_save_business_draft(%L,%L,%L,2)',workspace_id,site_id,doc),'permission') from business_fixture;
reset role;
rollback;
