-- Local/staging transaction only. Never a production migration.
begin;
create temporary table afixture(owner_id uuid,editor_id uuid,viewer_id uuid,outsider_id uuid,admin_id uuid,w uuid,s uuid,s2 uuid,a uuid,k uuid);
insert into afixture values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,null,null,gen_random_uuid());
insert into auth.users(id) select owner_id from afixture union all select editor_id from afixture union all select viewer_id from afixture union all select outsider_id from afixture union all select admin_id from afixture;
create function pg_temp.aexpect(q text,needle text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,needle)>0 then return;else raise exception 'Unexpected failure: %',sqlerrm;end if;end;raise exception 'Expected failure %',needle;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;
grant all on afixture to authenticated;
update afixture set a=(select id from bizoveya_private.agent_definitions where kind='quality' limit 1);
select bizoveya_private.set_platform_admin(admin_id,true,'fixture-operator','Testing configuration controls') from afixture;
set local role authenticated;select set_config('request.jwt.claim.sub',(select owner_id::text from afixture),true);
update afixture set w=(select id from public.bz_create_workspace('Agent workspace'));
update afixture set s=(select id from public.bz_register_site(w,'Agent site','external','business','https://agent-fixture.com/',null,'active',true));
update afixture set s2=(select id from public.bz_register_site(w,'Other site','external','business','https://agent-second.com/',null,'active',true));
reset role;
insert into public.bizoveya_memberships(workspace_id,user_id,role) select w,editor_id,'editor' from afixture union all select w,viewer_id,'viewer' from afixture;
set local role authenticated;select set_config('request.jwt.claim.sub',(select admin_id::text from afixture),true);select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select pg_temp.aexpect('select public.bz_admin_agent_registry()','bz_mfa_required');
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
do $$declare f record;d jsonb;r jsonb;begin select * into f from afixture;
 r:=public.bz_admin_agent_registry();if jsonb_array_length(r)<>3 then raise exception 'Missing seeded drafts';end if;
 select value->'document' into d from jsonb_array_elements(r) where value->>'id'=f.a::text;
 perform pg_temp.aexpect(format('select public.bz_admin_mutate_agent(%L,''approve-preview'',null,null,null,1,1,''Human reviewed rules'',true)',f.a),'bz_agent_unchecked');
 perform public.bz_admin_mutate_agent(f.a,'check',null,null,null,null,1,'Schema review completed',false);
 perform pg_temp.aexpect(format('select public.bz_admin_mutate_agent(%L,''approve-preview'',null,null,null,1,2,''Human reviewed rules'',false)',f.a),'bz_agent_unchecked');
 perform public.bz_admin_mutate_agent(f.a,'approve-preview',null,null,null,1,2,'Human reviewed preview scope',true);
 perform pg_temp.aexpect(format('select public.bz_admin_mutate_agent(%L,''check'',null,null,null,null,1,''Stale browser check'',false)',f.a),'bz_conflict');
 perform pg_temp.aexpect(format('select public.bz_admin_mutate_agent(%L,''save'',''quality-starter'',''quality'',%L::jsonb,null,3,''Unsupported capability test'',false)',f.a,jsonb_set(d,'{tools}','["knowledge.read_approved","publish"]')),'bz_invalid_agent');
 perform public.bz_admin_mutate_agent(f.a,'save','quality-starter','quality',jsonb_set(d,'{name}','"Updated quality reviewer"'),null,3,'Prepare revised instructions',false);
 r:=public.bz_admin_agent_history(f.a);if jsonb_array_length(r->'versions')<>2 or r->'versions'->1->'document'<>d then raise exception 'Old version overwritten';end if;
 if r->'versions'->0->>'checked'<>'false' then raise exception 'New version retained checks';end if;
end;$$;
do $$declare d jsonb;new_id uuid:=gen_random_uuid();r jsonb;begin
 select value->'document' into d from jsonb_array_elements(public.bz_admin_agent_registry()) limit 1;
 -- Supported-role create is an immutable new identity, not a customer-controlled tool.
 perform public.bz_admin_mutate_agent(new_id,'save','quality-custom','quality',jsonb_set(d,'{tools}','["knowledge.read_approved","proposal.review"]'),null,0,'Create named quality fixture',false);
 r:=public.bz_admin_agent_registry();if jsonb_array_length(r)<>4 then raise exception 'New agent missing';end if;
 perform pg_temp.aexpect(format('select public.bz_admin_mutate_agent(%L,''save'',''quality-custom'',''quality'',%L::jsonb,null,0,''Duplicate identifier fixture'',false)',gen_random_uuid(),jsonb_set(d,'{tools}','["knowledge.read_approved","proposal.review"]')),'bz_duplicate_agent');
end;$$;
select set_config('request.jwt.claim.sub',(select owner_id::text from afixture),true);
do $$declare f record;cat jsonb;preview jsonb;d jsonb:='{"title":"Approved policy","filename":"","sourceText":"We repair bicycles.","facts":[{"id":"f1","text":"Bicycle repair is available."}]}';begin select * into f from afixture;
 cat:=public.bz_site_agent_catalog(f.w,f.s);if jsonb_array_length(cat)<>1 or cat->0->>'version'<>'1' or cat->0 ? 'instructions' then raise exception 'Catalog exposes draft/instructions';end if;
 perform public.bz_save_site_agent_preferences(f.w,f.s,'{"brandVoice":"Friendly","audience":"Local clients","guidance":"Be clear"}',0);
 perform pg_temp.aexpect(format('select public.bz_save_site_agent_preferences(%L,%L,''{}'',1)',f.w,f.s),'bz_invalid_preferences');
 perform pg_temp.aexpect(format('select public.bz_save_site_agent_preferences(%L,%L,''{"brandVoice":"","audience":"","guidance":""}'',0)',f.w,f.s),'bz_conflict');
 perform public.bz_mutate_knowledge(f.w,f.s,f.k,'save',d,0);
 preview:=public.bz_preview_site_agent(f.w,f.s,f.a,1,1);if jsonb_array_length(preview->'facts')<>0 or preview->>'runtimeEnabled'<>'false' then raise exception 'Draft leaked or execution enabled';end if;
 perform public.bz_mutate_knowledge(f.w,f.s,f.k,'approve',null,1);
 preview:=public.bz_preview_site_agent(f.w,f.s,f.a,1,1);if preview->'facts'->0->>'sourceVersion'<>'2' or preview->'facts'->0->>'text'<>'Bicycle repair is available.' then raise exception 'Approved citation missing';end if;
 if jsonb_array_length(public.bz_preview_site_agent(f.w,f.s2,f.a,1,0)->'facts')<>0 then raise exception 'Cross-site knowledge leak';end if;
 perform public.bz_mutate_knowledge(f.w,f.s,f.k,'save',jsonb_set(d,'{facts}','[{"id":"f1","text":"Corrected policy."}]'),2);
 if jsonb_array_length(public.bz_preview_site_agent(f.w,f.s,f.a,1,1)->'facts')<>0 then raise exception 'Correction retained approved context';end if;
 perform pg_temp.aexpect(format('select public.bz_preview_site_agent(%L,%L,%L,2,1)',f.w,f.s,f.a),'bz_agent_preview_changed');
end;$$;
select set_config('request.jwt.claim.sub',(select editor_id::text from afixture),true);
select public.bz_save_site_agent_preferences(w,s,'{"brandVoice":"Editor guidance","audience":"","guidance":""}',1) from afixture;
select set_config('request.jwt.claim.sub',(select viewer_id::text from afixture),true);
select pg_temp.aexpect(format('select public.bz_save_site_agent_preferences(%L,%L,''{"brandVoice":"","audience":"","guidance":""}'',2)',w,s),'bz_forbidden') from afixture;
select public.bz_preview_site_agent(w,s,a,1,2) from afixture;
select set_config('request.jwt.claim.sub',(select outsider_id::text from afixture),true);
select pg_temp.aexpect(format('select public.bz_site_agent_catalog(%L,%L)',w,s),'bz_forbidden') from afixture;
select pg_temp.aexpect('select public.bz_admin_agent_registry()','bz_admin_forbidden');
select set_config('request.jwt.claim.sub',(select admin_id::text from afixture),true);
select pg_temp.aexpect(format('select public.bz_preview_site_agent(%L,%L,%L,1,2)',w,s,a),'bz_forbidden') from afixture;
select public.bz_admin_mutate_agent(a,'check',null,null,null,null,4,'Review revised configuration',false) from afixture;
select public.bz_admin_mutate_agent(a,'approve-preview',null,null,null,2,5,'Approve revised preview only',true) from afixture;
-- Explicit rollback to checked previous version.
select public.bz_admin_mutate_agent(a,'approve-preview',null,null,null,1,6,'Rollback preview to reviewed rules',true) from afixture;
select public.bz_admin_mutate_agent(a,'revoke-preview',null,null,null,null,7,'Revoke context preview approval',false) from afixture;
select set_config('request.jwt.claim.sub',(select owner_id::text from afixture),true);
select pg_temp.aexpect(format('select public.bz_preview_site_agent(%L,%L,%L,1,2)',w,s,a),'bz_agent_preview_changed') from afixture;
reset role;
do $$begin
 if has_table_privilege('authenticated','bizoveya_private.agent_versions','select') or has_table_privilege('authenticated','public.bizoveya_site_agent_preferences','update') or has_function_privilege('anon','public.bz_admin_agent_registry()','execute') then raise exception 'Unexpected privilege';end if;
 if bizoveya_private.valid_site_agent_preferences('[]') or bizoveya_private.valid_site_agent_preferences('{"brandVoice":"","audience":"","unexpected":""}') is distinct from false then raise exception 'Malformed preferences accepted';end if;
end;$$;
select bizoveya_private.set_platform_admin(admin_id,false,'fixture-operator','Revoke active test administrator') from afixture;
set local role authenticated;select set_config('request.jwt.claim.sub',(select admin_id::text from afixture),true);
select pg_temp.aexpect('select public.bz_admin_agent_registry()','bz_admin_forbidden');
reset role;rollback;
