begin;
create temporary table mf(id uuid,outsider uuid,profile uuid);
insert into mf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid());
insert into auth.users(id) select id from mf union all select outsider from mf;
select bizoveya_private.set_platform_admin(id,true,'test-operator','Model profile controls test') from mf;
create function pg_temp.mexpect(q text,needle text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,needle)>0 then return;else raise exception 'Unexpected failure: %',sqlerrm;end if;end;raise exception 'Expected failure %',needle;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;
grant all on mf to authenticated;
set local role authenticated;select set_config('request.jwt.claim.sub',(select id::text from mf),true);select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select pg_temp.mexpect('select public.bz_admin_model_registry()','bz_mfa_required');
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
do $$declare f record;r jsonb;d jsonb:='{"name":"Candidate model","provider":"nebius","credentialRef":"platform-nebius","modelId":"operator-verified-model","tier":"economical","maxOutputTokens":1500,"dailyBudgetCents":100}';begin
 select * into f from mf;r:=public.bz_admin_model_registry();if jsonb_array_length(r->'credentials')<>3 or jsonb_array_length(r->'profiles')<>0 then raise exception 'Seed state incorrect';end if;
 perform public.bz_admin_mutate_model(f.profile,'save','candidate-model',d,0,'Save first candidate profile');
 perform pg_temp.mexpect(format('select public.bz_admin_mutate_model(%L,''check'',null,null,1,''Check before enable'')',f.profile),'bz_credential_disabled');
 perform pg_temp.mexpect('select public.bz_admin_mutate_credential(''platform-nebius'',''enable'',1,''Review credential change'',false)','bz_invalid_credential');
 perform public.bz_admin_mutate_credential('platform-nebius','enable',1,'Review candidate reference',true);
 perform public.bz_admin_mutate_model(f.profile,'check',null,null,1,'Check current reference version');
 r:=public.bz_admin_model_registry();if r->'profiles'->0->>'checked'<>'true' then raise exception 'Check missing';end if;
 perform public.bz_admin_mutate_credential('platform-nebius','record-rotation',2,'Record operator key rotation',true);
 r:=public.bz_admin_model_registry();if r->'profiles'->0->>'checked'<>'false' then raise exception 'Rotation retained check';end if;
 perform pg_temp.mexpect('select public.bz_admin_mutate_credential(''platform-nebius'',''disable'',1,''Stale disable action'',true)','bz_conflict');
 perform public.bz_admin_mutate_model(f.profile,'check',null,null,2,'Recheck reference after rotation');
 perform public.bz_admin_mutate_model(f.profile,'save','candidate-model',jsonb_set(d,'{name}','"New candidate version"'),3,'Revise model profile name');
 r:=public.bz_admin_model_history(f.profile);if jsonb_array_length(r)<>2 or r->1->'document'<>d then raise exception 'Immutable version missing';end if;
 perform pg_temp.mexpect(format('select public.bz_admin_mutate_model(%L,''save'',''duplicate-profile'',%L::jsonb,0,''Mismatched reference test'')',gen_random_uuid(),jsonb_set(d,'{credentialRef}','"platform-openai"')),'bz_invalid_model');
 perform pg_temp.mexpect(format('select public.bz_admin_mutate_model(%L,''save'',''candidate-model'',%L::jsonb,0,''Duplicate profile identity'')',gen_random_uuid(),d),'bz_duplicate_model');
 perform pg_temp.mexpect(format('select public.bz_admin_mutate_model(%L,''check'',null,null,1,''Stale profile check'')',f.profile),'bz_conflict');
 perform public.bz_admin_mutate_model(f.profile,'check',null,null,4,'Check new candidate version');
 perform public.bz_admin_mutate_credential('platform-nebius','disable',3,'Disable candidate reference',true);
 r:=public.bz_admin_model_registry();if r->'profiles'->0->>'checked'<>'false' then raise exception 'Disabled reference retained check';end if;
 if jsonb_array_length(public.bz_admin_model_events())<>8 then raise exception 'Missing audit events';end if;
end;$$;
select set_config('request.jwt.claim.sub',(select outsider::text from mf),true);
select pg_temp.mexpect('select public.bz_admin_model_registry()','bz_admin_forbidden');
select pg_temp.mexpect('select public.bz_admin_model_events()','bz_admin_forbidden');
reset role;
do $$begin if has_table_privilege('authenticated','bizoveya_private.model_credentials','select') or has_table_privilege('authenticated','bizoveya_private.model_profile_versions','update') or has_function_privilege('anon','public.bz_admin_model_registry()','execute') then raise exception 'Direct privilege leak';end if;if bizoveya_private.valid_model_profile('[]') or bizoveya_private.valid_model_profile('{"name":"Bad"}') then raise exception 'Malformed accepted';end if;end;$$;
select bizoveya_private.set_platform_admin(id,false,'test-operator','Revoke profile administrator') from mf;
set local role authenticated;select set_config('request.jwt.claim.sub',(select id::text from mf),true);
select pg_temp.mexpect('select public.bz_admin_model_registry()','bz_admin_forbidden');
reset role;rollback;
