-- Local/staging fixtures only. Never apply as a migration.
begin;
create temporary table remove_fixture(u uuid,e uuid,v uuid,o uuid,w uuid,s uuid,p uuid,portfolio_site uuid,k uuid,d jsonb);
insert into remove_fixture values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,gen_random_uuid(),null,gen_random_uuid(),'{"schemaVersion": 2, "templateId": "service-studio-v1", "accent": "mint", "name": "Delete Business", "headline": "Approved headline", "description": "", "about": "", "location": "", "email": "hello@example.com", "phone": "", "services": [{"title": "Service", "description": ""}], "font": "editorial", "hours": "", "logo": "https://example.com/logo.png", "sections": [{"id": "hero", "type": "hero", "layout": "split", "visible": true, "tone": "base", "heading": "", "body": "", "image": "", "items": [], "imageFit": "contain", "imagePosition": "top"}, {"id": "contact", "type": "contact", "layout": "panel", "visible": true, "tone": "base", "heading": "", "body": "", "image": "", "items": [], "imageFit": "contain", "imagePosition": "top"}]}'::jsonb);
insert into auth.users(id) select u from remove_fixture union all select e from remove_fixture union all select v from remove_fixture union all select o from remove_fixture;
do $$begin execute format('grant usage on schema %I to authenticated,anon',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;
grant all on remove_fixture to authenticated,anon;
create function pg_temp.rexpect(q text,needle text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,needle)>0 then return;end if;raise;end;raise exception 'Expected failure %',needle;end;$$;
set local role authenticated;select set_config('request.jwt.claim.sub',(select u::text from remove_fixture),true);
update remove_fixture set w=(select id from public.bz_create_workspace('Removal test'));
update remove_fixture set s=(select id from public.bz_register_business_site(w,'Delete Business','active',true,d));
select public.bz_set_business_publication(w,s,1,0,true) from remove_fixture;
select public.bz_mutate_knowledge(w,s,k,'save','{"title":"Private","filename":"","sourceText":"Private source","facts":[{"id":"f1","text":"Private fact"}]}'::jsonb,0) from remove_fixture;
select public.bz_save_site_agent_preferences(w,s,'{"brandVoice":"Clear","audience":"Owners","guidance":"Drafts only"}'::jsonb,0) from remove_fixture;
reset role;
insert into public.bizoveya_memberships(workspace_id,user_id,role) select w,e,'editor' from remove_fixture union all select w,v,'viewer' from remove_fixture;
insert into public.projects(id,owner_id,name,creation_mode,document) select p,u,'Preserved original','guided','{"original":true}'::jsonb from remove_fixture;
set local role authenticated;select set_config('request.jwt.claim.sub',(select u::text from remove_fixture),true);
update remove_fixture set portfolio_site=(select id from public.bz_register_site(w,'Portfolio','native_portfolio','portfolio',null,p,'active',true));
select pg_temp.rexpect(format('select public.bz_delete_site(%L,%L,9,%L)',w,s,'Delete Business'),'bz_conflict') from remove_fixture;
select pg_temp.rexpect(format('select public.bz_delete_site(%L,%L,1,%L)',w,s,'Wrong'),'bz_confirmation_mismatch') from remove_fixture;
select pg_temp.rexpect(format('select public.bz_delete_site(%L,%L,1,%L)',w,gen_random_uuid(),'Delete Business'),'bz_not_found') from remove_fixture;
select pg_temp.rexpect(format('select public.bz_save_business_draft(%L,%L,%L,1)',w,s,jsonb_set(d,'{sections}',jsonb_build_array(d->'sections'->1,d->'sections'->0))),'bz_invalid_business_order') from remove_fixture;
select pg_temp.rexpect(format('select public.bz_save_business_draft(%L,%L,%L,1)',w,s,jsonb_set(d,'{headline}',to_jsonb(repeat('x',121)))),'bz_invalid_business_order') from remove_fixture;
select set_config('request.jwt.claim.sub',(select e::text from remove_fixture),true);
select pg_temp.rexpect(format('select public.bz_delete_site(%L,%L,1,%L)',w,s,'Delete Business'),'bz_forbidden') from remove_fixture;
select set_config('request.jwt.claim.sub',(select v::text from remove_fixture),true);
select pg_temp.rexpect(format('select public.bz_delete_site(%L,%L,1,%L)',w,s,'Delete Business'),'bz_forbidden') from remove_fixture;
select set_config('request.jwt.claim.sub',(select o::text from remove_fixture),true);
select pg_temp.rexpect(format('select public.bz_delete_site(%L,%L,1,%L)',w,s,'Delete Business'),'bz_forbidden') from remove_fixture;
select set_config('request.jwt.claim.sub',(select u::text from remove_fixture),true);
select public.bz_delete_site(w,s,1,'Delete Business') from remove_fixture;
select public.bz_delete_site(w,portfolio_site,1,'Portfolio') from remove_fixture;
select pg_temp.rexpect(format('select public.bz_delete_site(%L,%L,1,%L)',w,s,'Delete Business'),'bz_not_found') from remove_fixture;
-- Deleted identity can be reused; no automatic duplicate merge/removal occurs.
select public.bz_register_business_site(w,'Delete Business','active',true,d) from remove_fixture;
reset role;
do $$declare f record;begin select * into f from remove_fixture;
 if exists(select 1 from public.bizoveya_sites where id in (f.s,f.portfolio_site)) then raise exception 'Site not removed';end if;
 if exists(select 1 from public.bizoveya_business_drafts where site_id=f.s) or exists(select 1 from public.bizoveya_business_publications where site_id=f.s) or exists(select 1 from public.bizoveya_business_publication_history where site_id=f.s) or exists(select 1 from public.bizoveya_knowledge_sources where site_id=f.s) or exists(select 1 from public.bizoveya_knowledge_revisions where site_id=f.s) or exists(select 1 from public.bizoveya_knowledge_events where site_id=f.s) or exists(select 1 from public.bizoveya_site_agent_preferences where site_id=f.s) then raise exception 'Child data remains';end if;
 if not exists(select 1 from public.projects where id=f.p and document='{"original":true}'::jsonb) then raise exception 'Original portfolio changed';end if;
 if (select count(*) from public.bizoveya_site_removal_events where workspace_id=f.w)<>2 then raise exception 'Removal evidence missing';end if;
 if not bizoveya_private.valid_business_document(f.d) or bizoveya_private.valid_business_document(jsonb_set(f.d,'{logo}','"javascript:bad"')) then raise exception 'Logo boundary wrong';end if;
end;$$;
set local role anon;select pg_temp.rexpect('select public.bz_delete_site(null,null,1,null)','permission');
rollback;
