begin;
create temporary table tf(actor uuid,outsider uuid,profile uuid,run uuid,claim uuid);
insert into tf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid());
insert into auth.users(id) select actor from tf union all select outsider from tf;
select bizoveya_private.set_platform_admin(actor,true,'test-operator','Model connectivity test fixture') from tf;
create function pg_temp.texpect(q text,needle text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,needle)>0 then return;else raise exception 'Unexpected failure: %',sqlerrm;end if;end;raise exception 'Expected failure %',needle;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,service_role,anon',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;
grant all on tf to authenticated,service_role,anon;
set local role anon;
select pg_temp.texpect('select public.bz_admin_model_tests()','permission denied');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub',(select actor::text from tf),true);select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select pg_temp.texpect('select public.bz_admin_model_tests()','bz_mfa_required');
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select public.bz_admin_mutate_model(profile,'save','test-profile','{"name":"Test","provider":"nebius","credentialRef":"platform-nebius","modelId":"fixture-model","tier":"economical","maxOutputTokens":128,"dailyBudgetCents":100}',0,'Create fixture test profile') from tf;
select pg_temp.texpect(format('select public.bz_admin_begin_model_test(%L,%L,1,1,%L,true,''Not ready test profile'')',run,profile,claim),'bz_test_not_ready') from tf;
select public.bz_admin_mutate_credential('platform-nebius','enable',1,'Enable fixture reference',true);
select public.bz_admin_mutate_model(profile,'check',null,null,1,'Check fixture model profile') from tf;
select pg_temp.texpect(format('select public.bz_admin_begin_model_test(%L,%L,1,2,%L,true,''Stale model revision'')',run,profile,claim),'bz_conflict') from tf;
do $$declare f record;r jsonb;begin select * into f from tf;r:=public.bz_admin_begin_model_test(f.run,f.profile,2,2,f.claim,true,'First bounded model test');if r->>'execute'<>'true' then raise exception 'No reservation';end if;r:=public.bz_admin_begin_model_test(f.run,f.profile,2,2,gen_random_uuid(),true,'Repeat same identifier');if r->>'execute'<>'false' then raise exception 'Replay executed';end if;if (public.bz_admin_model_tests()->>'usedToday')::int<>1 then raise exception 'Replay consumed second attempt';end if;end;$$;
select pg_temp.texpect(format('select public.bz_admin_begin_model_test(%L,%L,2,2,%L,true,''Concurrent model request'')',gen_random_uuid(),profile,gen_random_uuid()),'bz_test_busy') from tf;
select pg_temp.texpect(format('select public.bz_finish_model_test(%L,%L,''response_matched'',13,4)',run,claim),'permission denied') from tf;
reset role;set local role service_role;
select public.bz_finish_model_test(run,claim,'response_matched',13,4) from tf;
select pg_temp.texpect(format('select public.bz_finish_model_test(%L,%L,''response_matched'',13,4)',run,claim),'bz_test_expired') from tf;
reset role;set local role authenticated;
do $$begin if public.bz_admin_model_tests()->'runs'->0->>'current'<>'true' then raise exception 'Current qualification absent';end if;end;$$;
select public.bz_admin_mutate_credential('platform-nebius','record-rotation',2,'Rotate fixture credential',true);
do $$begin if public.bz_admin_model_tests()->'runs'->0->>'current'<>'false' then raise exception 'Stale qualification remained current';end if;end;$$;
select public.bz_admin_mutate_model(profile,'check',null,null,2,'Recheck after rotation') from tf;
reset role;
-- Charge uncertain historical attempts against today's limit; no provider calls performed.
insert into bizoveya_private.model_test_runs(id,profile_id,profile_version,credential_id,credential_version,actor_id,claim,status,result_code,reason) select gen_random_uuid(),profile,1,'platform-nebius',3,actor,gen_random_uuid(),'unknown','interrupted','Interrupted fixture attempt' from tf,generate_series(1,4);
set local role authenticated;
select pg_temp.texpect(format('select public.bz_admin_begin_model_test(%L,%L,3,3,%L,true,''Beyond daily attempt limit'')',gen_random_uuid(),profile,gen_random_uuid()),'bz_test_daily_limit') from tf;
select set_config('request.jwt.claim.sub',(select outsider::text from tf),true);
select pg_temp.texpect('select public.bz_admin_model_tests()','bz_admin_forbidden');
rollback;
