-- Isolated test fixture: never apply this file to hosted data.
begin;
create temporary table bf(actor uuid,outsider uuid,profile uuid,run uuid,claim uuid,agent uuid);
insert into bf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),(select id from bizoveya_private.agent_definitions where kind='quality' limit 1));
insert into auth.users(id) select actor from bf union all select outsider from bf;
select bizoveya_private.set_platform_admin(actor,true,'test-operator','Assignment test fixture') from bf;
create function pg_temp.bexpect(q text,needle text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,needle)>0 then return;else raise exception 'Unexpected failure: %',sqlerrm;end if;end;raise exception 'Expected failure %',needle;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,service_role,anon',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;
grant all on bf to authenticated,service_role,anon;
set local role anon;
select pg_temp.bexpect('select public.bz_admin_binding_registry()','permission denied');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub',(select actor::text from bf),true);select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select pg_temp.bexpect('select public.bz_admin_binding_registry()','bz_mfa_required');
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select public.bz_admin_mutate_model(profile,'save','binding-profile','{"name":"Binding test","provider":"nebius","credentialRef":"platform-nebius","modelId":"fixture-model","tier":"economical","maxOutputTokens":128,"dailyBudgetCents":100}',0,'Create assignment test profile') from bf;
select public.bz_admin_mutate_credential('platform-nebius','enable',1,'Enable fixture reference',true);
select public.bz_admin_mutate_model(profile,'check',null,null,1,'Check fixture model profile') from bf;
select public.bz_admin_begin_model_test(run,profile,2,2,claim,true,'Assignment connectivity fixture') from bf;
reset role;set local role service_role;
select public.bz_finish_model_test(run,claim,'response_matched',13,4) from bf;
reset role;set local role authenticated;
select pg_temp.bexpect(format('select public.bz_admin_mutate_binding(%L,%L,%L,0,1,2,2,''assign'',true,''Unreviewed agent denied'')',agent,profile,run),'bz_binding_agent_changed') from bf;
do $$declare f record;d jsonb;begin select * into f from bf;select value->'document' into d from jsonb_array_elements(public.bz_admin_agent_registry()) where value->>'id'=f.agent::text;
perform public.bz_admin_mutate_agent(f.agent,'save','quality-starter','quality',jsonb_set(d,'{modelTier}','"economical"'),null,1,'Select economical routing tier',false);
perform public.bz_admin_mutate_agent(f.agent,'check',null,null,null,null,2,'Check saved routing preference',false);
perform public.bz_admin_mutate_agent(f.agent,'approve-preview',null,null,null,2,3,'Approve saved reviewed version',true);
end;$$;
select pg_temp.bexpect(format('select public.bz_admin_mutate_binding(%L,%L,%L,0,4,2,2,''assign'',false,''Consent is required here'')',agent,profile,run),'bz_invalid_binding') from bf;
select public.bz_admin_mutate_binding(agent,profile,run,0,4,2,2,'assign',true,'Assign reviewed model for draft pilot') from bf;
do $$declare r jsonb;begin r:=public.bz_admin_binding_registry();if jsonb_array_length(r->'bindings')<>1 or r->'bindings'->0->>'issue' is not null or jsonb_array_length(r->'events')<>1 then raise exception 'Current assignment/history missing';end if;end;$$;
select pg_temp.bexpect(format('select public.bz_admin_mutate_binding(%L,%L,%L,0,4,2,2,''assign'',true,''Stale tab retry denied'')',agent,profile,run),'bz_conflict') from bf;
select pg_temp.bexpect('select * from bizoveya_private.agent_model_bindings','permission denied');
reset role;update bizoveya_private.model_test_runs set finished_at=clock_timestamp()-interval '25 hours' where id=(select run from bf);
set local role authenticated;
do $$begin if public.bz_admin_binding_registry()->'bindings'->0->>'issue'<>'test_expired' then raise exception 'Expired test not invalidated';end if;end;$$;
select pg_temp.bexpect(format('select public.bz_admin_mutate_binding(%L,%L,%L,1,4,2,2,''assign'',true,''Expired test retry denied'')',agent,profile,run),'bz_binding_test_expired') from bf;
reset role;update bizoveya_private.model_test_runs set finished_at=clock_timestamp() where id=(select run from bf);
set local role authenticated;
select public.bz_admin_mutate_credential('platform-nebius','record-rotation',2,'Rotate fixture credential',true);
do $$begin if public.bz_admin_binding_registry()->'bindings'->0->>'issue'<>'credential_changed' then raise exception 'Rotation not invalidated';end if;end;$$;
select public.bz_admin_mutate_binding(agent,null,null,1,null,null,null,'disable',true,'Disable assignment after rotation') from bf;
do $$declare r jsonb;begin r:=public.bz_admin_binding_registry();if r->'bindings'->0->>'issue'<>'disabled' or jsonb_array_length(r->'events')<>2 then raise exception 'Disable lost history';end if;end;$$;
select set_config('request.jwt.claim.sub',(select outsider::text from bf),true);
select pg_temp.bexpect('select public.bz_admin_binding_registry()','bz_admin_forbidden');
rollback;
