-- Local synthetic fixture, not a hosted migration; fictional USD rates.
begin;
create temporary table sf(actor uuid,profile uuid,run uuid,claim uuid,run2 uuid,claim2 uuid,d jsonb);
insert into sf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),jsonb_build_object('enabled',true,'inputRateMicros',1000000,'outputRateMicros',1000000,'requestFeeMicros',0,'dailyLimitMicros',20000,'runLimitMicros',10000,'validUntil',clock_timestamp()+interval '7 days','source','https://example.com/fictional-test-pricing','reviewed',true));
insert into auth.users(id) select actor from sf;
select bizoveya_private.set_platform_admin(actor,true,'test-operator','Spending synthetic fixture') from sf;
create function pg_temp.sexpect(q text,n text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,n)>0 then return;else raise exception 'Unexpected: %',sqlerrm;end if;end;raise exception 'Expected %',n;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,service_role,anon',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;
grant all on sf to authenticated,service_role,anon;
set local role anon;
select pg_temp.sexpect('select public.bz_admin_spending()','permission denied');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub',(select actor::text from sf),true);select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select pg_temp.sexpect('select public.bz_admin_spending()','bz_mfa_required');
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select public.bz_admin_mutate_model(profile,'save','spending-profile','{"name":"Spending test","provider":"nebius","credentialRef":"platform-nebius","modelId":"fixture-model","tier":"economical","maxOutputTokens":128,"dailyBudgetCents":100}',0,'Create spending fixture profile') from sf;
select public.bz_admin_mutate_credential('platform-nebius','enable',1,'Enable spending fixture',true);
select public.bz_admin_mutate_model(profile,'check',null,null,1,'Check spending fixture model') from sf;
select pg_temp.sexpect(format('select public.bz_admin_begin_model_test(%L,%L,2,2,%L,true,''Missing policy denied'')',run,profile,claim),'bz_spending_not_ready') from sf;
select pg_temp.sexpect(format('select public.bz_admin_save_spending(%L,2,0,%L::jsonb,''Missing consent denied'',false)',profile,d),'bz_invalid_spending') from sf;
select pg_temp.sexpect(format('select public.bz_admin_save_spending(%L,2,0,%L::jsonb,''Null expiry denied'',true)',profile,jsonb_set(d,'{validUntil}','null')),'bz_invalid_spending') from sf;
select public.bz_admin_save_spending(profile,2,0,d,'Review fictional test prices',true) from sf;
select pg_temp.sexpect(format('select public.bz_admin_save_spending(%L,2,0,%L::jsonb,''Stale policy tab denied'',true)',profile,d),'bz_conflict') from sf;
select pg_temp.sexpect('select * from bizoveya_private.spending_ledger','permission denied');
select pg_temp.sexpect(format('select bizoveya_private.begin_model_test_legacy(%L,%L,2,2,%L,true,''Bypass attempt denied'')',run,profile,claim),'permission denied') from sf;
select public.bz_admin_begin_model_test(run,profile,2,2,claim,true,'Reserve synthetic request cost') from sf;
select public.bz_admin_begin_model_test(run,profile,2,2,claim,true,'Reserve synthetic request cost') from sf;
do $$begin if public.bz_admin_spending()->'policies'->0->>'spentTodayMicros'<>'5280' or jsonb_array_length(public.bz_admin_spending()->'runs')<>1 then raise exception 'Reservation/replay incorrect';end if;end;$$;
reset role;set local role service_role;
select public.bz_finish_model_test(run,claim,'response_matched',13,4) from sf;
reset role;set local role authenticated;
do $$begin if public.bz_admin_spending()->'policies'->0->>'spentTodayMicros'<>'17' then raise exception 'Settlement wrong';end if;end;$$;
select public.bz_admin_begin_model_test(run2,profile,2,2,claim2,true,'Reserve missing usage fixture') from sf;
reset role;set local role service_role;
select public.bz_finish_model_test(run2,claim2,'timeout',null,null) from sf;
reset role;set local role authenticated;
select pg_temp.sexpect(format('select public.bz_admin_begin_model_test(%L,%L,2,2,%L,true,''Uncertain charge denied'')',gen_random_uuid(),profile,gen_random_uuid()),'bz_spending_unresolved') from sf;
select public.bz_admin_reconcile_spending(run2,'unknown',200,'Verified fictional billing evidence',true) from sf;
select pg_temp.sexpect(format('select public.bz_admin_reconcile_spending(%L,''unknown'',0,''Stale reconciliation denied'',true)',run2),'bz_conflict') from sf;
select public.bz_admin_save_spending(profile,2,1,jsonb_set(d,'{runLimitMicros}','100'),'Tighten fictional run allowance',true) from sf;
select pg_temp.sexpect(format('select public.bz_admin_begin_model_test(%L,%L,2,2,%L,true,''Run allowance denied'')',gen_random_uuid(),profile,gen_random_uuid()),'bz_run_budget') from sf;
select public.bz_admin_save_spending(profile,2,2,jsonb_set(jsonb_set(d,'{dailyLimitMicros}','5280'),'{runLimitMicros}','5280'),'Tighten daily allowance test',true) from sf;
select pg_temp.sexpect(format('select public.bz_admin_begin_model_test(%L,%L,2,2,%L,true,''Daily allowance denied'')',gen_random_uuid(),profile,gen_random_uuid()),'bz_daily_budget') from sf;
do $$begin if jsonb_array_length(public.bz_admin_spending()->'policyEvents')<>3 or public.bz_admin_spending()->'policies'->0->>'spentTodayMicros'<>'217' then raise exception 'History reset spending';end if;end;$$;
select public.bz_admin_save_spending(profile,2,3,d,'Restore synthetic budget policy',true) from sf;
update sf set run=gen_random_uuid(),claim=gen_random_uuid();
select public.bz_admin_begin_model_test(run,profile,2,2,claim,true,'Reserve overrun test fixture') from sf;
reset role;set local role service_role;
select public.bz_finish_model_test(run,claim,'response_matched',5000,128) from sf;
reset role;set local role authenticated;
select pg_temp.sexpect(format('select public.bz_admin_begin_model_test(%L,%L,2,2,%L,true,''Overrun blocks next request'')',gen_random_uuid(),profile,gen_random_uuid()),'bz_spending_unresolved') from sf;
reset role;
update bizoveya_private.spending_ledger set started_at=clock_timestamp()-interval '2 days' where run_id=(select run from sf);
set local role authenticated;
select pg_temp.sexpect(format('select public.bz_admin_begin_model_test(%L,%L,2,2,%L,true,''Old unresolved still blocked'')',gen_random_uuid(),profile,gen_random_uuid()),'bz_spending_unresolved') from sf;
select public.bz_admin_reconcile_spending(run,'overrun',5128,'Verified overrun billing evidence',true) from sf;
reset role;
update bizoveya_private.spending_policies set document=jsonb_set(document,'{validUntil}',to_jsonb(clock_timestamp()-interval '1 day')) where profile_id=(select profile from sf);
set local role authenticated;
select pg_temp.sexpect(format('select public.bz_admin_begin_model_test(%L,%L,2,2,%L,true,''Expired prices denied'')',gen_random_uuid(),profile,gen_random_uuid()),'bz_pricing_expired') from sf;
rollback;
