-- Local synthetic fixture only. Never run on hosted data; no provider request is made.
begin;
create temporary table gf(owner_id uuid,outsider uuid,w uuid,s uuid,c uuid,run uuid,profile uuid,test_run uuid);
insert into gf values(gen_random_uuid(),gen_random_uuid(),null,null,gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid());
insert into auth.users(id) select owner_id from gf union all select outsider from gf;
create function pg_temp.gexpect(q text,n text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,n)>0 then return;else raise exception 'Unexpected: %',sqlerrm;end if;end;raise exception 'Expected %',n;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,anon',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;grant all on gf to authenticated,anon;
set local role authenticated;select set_config('request.jwt.claim.sub',(select owner_id::text from gf),true);
update gf set w=(select id from public.bz_create_workspace('Generation fixture'));
update gf set s=(select id from public.bz_register_site(w,'Draft pilot','external','business','https://generation-fixture.com/',null,'active',true));
select public.bz_save_site_agent_preferences(w,s,'{"brandVoice":"practical","audience":"small business owners","guidance":"Draft only"}',0) from gf;
select public.bz_mutate_knowledge(w,s,gen_random_uuid(),'save','{"title":"Approved facts","filename":"facts.md","sourceText":"Bizoveya prepares private reviewable drafts.","facts":[{"id":"f1","text":"Bizoveya prepares private reviewable drafts."}]}',0) from gf;
select public.bz_mutate_knowledge(w,s,(select id from public.bizoveya_knowledge_sources where site_id=s),'approve',null,1) from gf;
select public.bz_save_campaign(w,s,c,'{"title":"Pilot","brief":"Prepare three draft formats","blog":"","pinterest":"","linkedin":""}',0) from gf;
reset role;
update bizoveya_private.model_credentials set enabled=true where id='platform-gemini';
insert into bizoveya_private.model_profiles(id,slug,version,revision) select profile,'generation-fixture',1,1 from gf;
insert into bizoveya_private.model_profile_versions(profile_id,version,document,reason) select profile,1,'{"name":"Fixture Gemini","provider":"gemini","credentialRef":"platform-gemini","modelId":"fixture-model","tier":"economical","maxOutputTokens":1500,"dailyBudgetCents":100}','Synthetic snapshot fixture' from gf;
insert into bizoveya_private.model_profile_checks(profile_id,version,credential_id,credential_version) select profile,1,'platform-gemini',1 from gf;
insert into bizoveya_private.model_test_runs(id,profile_id,profile_version,credential_id,credential_version,claim,status,result_code,input_tokens,output_tokens,reason,finished_at) select test_run,profile,1,'platform-gemini',1,gen_random_uuid(),'passed','response_matched',20,7,'Synthetic connectivity evidence',clock_timestamp() from gf;
insert into bizoveya_private.spending_policies(profile_id,version,profile_version,document,reason) select profile,1,1,jsonb_build_object('enabled',true,'inputRateMicros',0,'outputRateMicros',0,'requestFeeMicros',0,'dailyLimitMicros',10000,'runLimitMicros',10000,'validUntil',clock_timestamp()+interval '7 days','source','https://example.com/fictional-pricing','reviewed',true),'Synthetic reviewed prices' from gf;
update bizoveya_private.agent_versions set document=jsonb_set(document,'{modelTier}','"economical"') where version=1 and agent_id in(select id from bizoveya_private.agent_definitions where kind in('coordinator','content','quality'));
update bizoveya_private.agent_definitions set preview_version=1 where kind in('coordinator','content','quality');
insert into bizoveya_private.agent_checks(agent_id,version) select id,1 from bizoveya_private.agent_definitions where kind in('coordinator','content','quality') on conflict do nothing;
insert into bizoveya_private.agent_model_bindings(agent_id,agent_version,profile_id,profile_version,credential_version,test_id,revision,enabled,reason) select a.id,1,g.profile,1,1,g.test_run,1,true,'Synthetic generation binding' from bizoveya_private.agent_definitions a cross join gf g where a.kind in('coordinator','content','quality');
set local role authenticated;select set_config('request.jwt.claim.sub',(select owner_id::text from gf),true);
select public.bz_prepare_campaign_generation(w,s,c,1,run) from gf;
select public.bz_prepare_campaign_generation(w,s,c,1,run) from gf;
do $$declare h jsonb;begin select public.bz_campaign_generation_history(w,s) into h from gf;if jsonb_array_length(h)<>1 or h->0->>'status'<>'prepared' or h->0->>'stageCount'<>'3' then raise exception 'Prepared snapshot/history incorrect';end if;end;$$;
select pg_temp.gexpect(format('select public.bz_prepare_campaign_generation(%L,%L,%L,2,%L)',w,s,c,gen_random_uuid()),'bz_conflict') from gf;
select set_config('request.jwt.claim.sub',(select outsider::text from gf),true);
select pg_temp.gexpect(format('select public.bz_campaign_generation_history(%L,%L)',w,s),'bz_forbidden') from gf;
reset role;
do $$begin if has_table_privilege('authenticated','bizoveya_private.generation_runs','select') then raise exception 'Private snapshot exposed';end if;end;$$;
delete from public.bizoveya_sites where id=(select s from gf);
do $$begin if exists(select 1 from bizoveya_private.generation_runs) then raise exception 'Site removal left generation snapshot';end if;end;$$;
rollback;
