-- Local synthetic fixture only. Never run on hosted data; no provider request is made.
begin;
create temporary table gs(owner_id uuid,outsider uuid,w uuid,s uuid,c uuid,run uuid,profile uuid,test_run uuid,coordinator uuid,content uuid,quality uuid,claim1 uuid,claim2 uuid,claim3 uuid);
insert into gs values(gen_random_uuid(),gen_random_uuid(),null,null,gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid());
insert into auth.users(id) select owner_id from gs union all select outsider from gs;
create function pg_temp.gsexpect(q text,n text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,n)>0 then return;else raise exception 'Unexpected: %',sqlerrm;end if;end;raise exception 'Expected %',n;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,anon,service_role',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;grant all on gs to authenticated,anon,service_role;
set local role authenticated;select set_config('request.jwt.claim.sub',(select owner_id::text from gs),true);
update gs set w=(select id from public.bz_create_workspace('Stage accounting fixture'));
update gs set s=(select id from public.bz_register_site(w,'Draft pilot','external','business','https://stage-fixture.com/',null,'active',true));
select public.bz_save_site_agent_preferences(w,s,'{"brandVoice":"practical","audience":"small business owners","guidance":"Draft only"}',0) from gs;
select public.bz_mutate_knowledge(w,s,gen_random_uuid(),'save','{"title":"Approved facts","filename":"facts.md","sourceText":"Bizoveya prepares private reviewable drafts.","facts":[{"id":"f1","text":"Bizoveya prepares private reviewable drafts."}]}',0) from gs;
select public.bz_mutate_knowledge(w,s,(select id from public.bizoveya_knowledge_sources where site_id=s),'approve',null,1) from gs;
select public.bz_save_campaign(w,s,c,'{"title":"Pilot","brief":"Prepare three draft formats","blog":"","pinterest":"","linkedin":""}',0) from gs;
reset role;
update bizoveya_private.model_credentials set enabled=true where id='platform-gemini';
insert into bizoveya_private.model_profiles(id,slug,version,revision) select profile,'stage-fixture',1,1 from gs;
insert into bizoveya_private.model_profile_versions(profile_id,version,document,reason) select profile,1,'{"name":"Fixture Gemini","provider":"gemini","credentialRef":"platform-gemini","modelId":"fixture-model","tier":"economical","maxOutputTokens":1500,"dailyBudgetCents":100}','Synthetic stage fixture' from gs;
insert into bizoveya_private.model_profile_checks(profile_id,version,credential_id,credential_version) select profile,1,'platform-gemini',1 from gs;
insert into bizoveya_private.model_test_runs(id,profile_id,profile_version,credential_id,credential_version,claim,status,result_code,input_tokens,output_tokens,reason,finished_at) select test_run,profile,1,'platform-gemini',1,gen_random_uuid(),'passed','response_matched',20,7,'Synthetic connectivity evidence',clock_timestamp() from gs;
insert into bizoveya_private.spending_policies(profile_id,version,profile_version,document,reason) select profile,1,1,jsonb_build_object('enabled',true,'inputRateMicros',0,'outputRateMicros',0,'requestFeeMicros',0,'dailyLimitMicros',10000,'runLimitMicros',10000,'validUntil',clock_timestamp()+interval '7 days','source','https://example.com/fictional-pricing','reviewed',true),'Synthetic reviewed prices' from gs;
update bizoveya_private.agent_versions set document=jsonb_set(document,'{modelTier}','"economical"') where version=1 and agent_id in(select id from bizoveya_private.agent_definitions where kind in('coordinator','content','quality'));
update bizoveya_private.agent_definitions set preview_version=1 where kind in('coordinator','content','quality');
insert into bizoveya_private.agent_checks(agent_id,version) select id,1 from bizoveya_private.agent_definitions where kind in('coordinator','content','quality') on conflict do nothing;
insert into bizoveya_private.agent_model_bindings(agent_id,agent_version,profile_id,profile_version,credential_version,test_id,revision,enabled,reason) select a.id,1,g.profile,1,1,g.test_run,1,true,'Synthetic generation binding' from bizoveya_private.agent_definitions a cross join gs g where a.kind in('coordinator','content','quality');
set local role authenticated;select set_config('request.jwt.claim.sub',(select owner_id::text from gs),true);select public.bz_prepare_campaign_generation(w,s,c,1,run) from gs;

reset role;
select bizoveya_private.set_platform_admin(owner_id,true,'fixture','Synthetic dispatch operator') from gs;
select bizoveya_private.set_platform_admin(outsider,true,'fixture','Synthetic unrelated operator') from gs;
set local role authenticated;
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select set_config('request.jwt.claim.sub',(select outsider::text from gs),true);
do $$begin if public.bz_admin_generation_queue()<>'[]'::jsonb then raise exception 'Unrelated admin read queue';end if;end;$$;
select pg_temp.gsexpect(format('select public.bz_admin_authorize_generation(%L,%L,%L,true)',run,claim1,'Authorize fixture private draft'),'bz_forbidden') from gs;
select pg_temp.gsexpect(format('select public.bz_campaign_generation_outputs(%L,%L)',w,s),'bz_forbidden') from gs;
select set_config('request.jwt.claim.sub',(select owner_id::text from gs),true);
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
select pg_temp.gsexpect('select public.bz_admin_generation_queue()','bz_mfa_required');
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
do $$begin if jsonb_array_length(public.bz_admin_generation_queue())<>1 then raise exception 'Owner queue missing';end if;end;$$;
select public.bz_admin_authorize_generation(run,claim1,'Authorize fixture private draft',true) from gs;
select pg_temp.gsexpect(format('select public.bz_admin_authorize_generation(%L,%L,%L,true)',run,claim2,'Duplicate fixture authorization'),'bz_generation_busy') from gs;
select pg_temp.gsexpect(format('select public.bz_finish_generation_dispatch(%L,%L,%L)',run,claim1,'failed'),'permission denied') from gs;
reset role;set local role service_role;
select public.bz_finish_generation_dispatch(run,claim1,'blocked') from gs;
reset role;
-- A changed binding invalidates an old immutable snapshot.
update bizoveya_private.agent_model_bindings set revision=revision+1;
set local role authenticated;
select pg_temp.gsexpect(format('select public.bz_admin_authorize_generation(%L,%L,%L,true)',run,claim2,'Authorize stale fixture'),'bz_generation_stale') from gs;
reset role;update bizoveya_private.agent_model_bindings set revision=revision-1;
-- Simulated successful output; no provider calls in this fixture.
update bizoveya_private.generation_runs set status='succeeded',started_at=clock_timestamp(),finished_at=clock_timestamp(),output_document='{"schema":"campaign-generation-output-v1","stages":{"quality":{"approved":false,"issues":[{"severity":"blocker"}]}}}' where id=(select run from gs);
set local role authenticated;
select public.bz_review_campaign_generation(w,s,run,0,'changes_requested','Check claims and revise draft text') from gs;
select pg_temp.gsexpect(format('select public.bz_review_campaign_generation(%L,%L,%L,0,%L,%L)',w,s,run,'changes_requested','Stale tab must not overwrite review'),'bz_conflict') from gs;
select pg_temp.gsexpect(format('select public.bz_review_campaign_generation(%L,%L,%L,1,%L,%L)',w,s,run,'accepted','Accept fixture for draft use only'),'bz_quality_blocked') from gs;
reset role;update bizoveya_private.generation_runs set output_document=jsonb_set(output_document,'{stages,quality}','{"approved":true,"issues":[]}') where id=(select run from gs);
set local role authenticated;
select public.bz_review_campaign_generation(w,s,run,1,'accepted','Accept fixture for draft use only') from gs;
do $$declare output jsonb;begin select public.bz_campaign_generation_outputs(w,s) into output from gs;if jsonb_array_length(output->0->'reviews')<>2 or output->0->'reviews'->0->>'decision'<>'accepted' then raise exception 'Review history missing';end if;end;$$;
reset role;
insert into bizoveya_private.generation_reviews(generation_id,version,decision,reason,actor_id) select run,n,'changes_requested','Synthetic bounded review history',owner_id from gs cross join generate_series(3,100) n;
set local role authenticated;
select pg_temp.gsexpect(format('select public.bz_review_campaign_generation(%L,%L,%L,100,%L,%L)',w,s,run,'accepted','Do not exceed bounded review history'),'bz_review_limit') from gs;
reset role;
update public.bizoveya_memberships set role='viewer' where user_id=(select owner_id from gs);
set local role authenticated;
select pg_temp.gsexpect(format('select public.bz_review_campaign_generation(%L,%L,%L,2,%L,%L)',w,s,run,'changes_requested','Viewer cannot change review'),'bz_forbidden') from gs;
reset role;
do $$begin
 if (select document->>'blog' from public.bizoveya_campaigns where id=(select c from gs))<>'' then raise exception 'Review changed campaign text';end if;
 if (select count(*) from bizoveya_private.generation_dispatch_events)<>1 then raise exception 'Authorization history missing';end if;
 if has_function_privilege('authenticated','public.bz_finish_generation_dispatch(uuid,uuid,text)','execute') or has_table_privilege('authenticated','bizoveya_private.generation_reviews','select') then raise exception 'Private grants leaked';end if;
end;$$;
rollback;
