-- Ephemeral local fixture only. Never run against hosted data.
begin;
create temporary table vf(owner_id uuid,viewer_id uuid,outsider uuid,w uuid,s uuid,c uuid,run uuid,document jsonb);
insert into vf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,gen_random_uuid(),gen_random_uuid(),jsonb_build_object('schema','campaign-visuals-v1','brand',jsonb_build_object('name','Fixture brand','accent','#5271FF','footer','Private test'),'pins',jsonb_build_array(jsonb_build_object('title','Pin one','body','Reviewed source excerpt'),jsonb_build_object('title','Pin two','body','Reviewed source excerpt')),'slides',(select jsonb_agg(jsonb_build_object('title','Slide '||n,'body','Reviewed source excerpt')) from generate_series(1,6)n)));
insert into auth.users(id) select owner_id from vf union all select viewer_id from vf union all select outsider from vf;
create function pg_temp.vexpect(q text,n text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,n)>0 then return;else raise exception 'Unexpected: %',sqlerrm;end if;end;raise exception 'Expected %',n;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,anon,service_role',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;grant all on vf to authenticated,anon,service_role;
set local role authenticated;select set_config('request.jwt.claim.sub',(select owner_id::text from vf),true);
update vf set w=(select id from public.bz_create_workspace('Visual fixture'));
update vf set s=(select id from public.bz_register_site(w,'Visual site','external','business','https://visual-fixture.example.com/',null,'active',true));
select public.bz_save_campaign(w,s,c,'{"title":"Private visual fixture","brief":"Review test excerpts","blog":"","pinterest":"","linkedin":""}',0) from vf;
reset role;
insert into public.bizoveya_memberships(workspace_id,user_id,role) select w,viewer_id,'viewer' from vf;
insert into bizoveya_private.generation_runs(id,campaign_id,site_id,campaign_version,status,input_snapshot,output_document,requested_by) select run,c,s,1,'succeeded','{}','{"schema":"campaign-generation-output-v1","stages":{"quality":{"approved":true,"issues":[]}}}',owner_id from vf;
set local role authenticated;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,0,1,%L::jsonb,true)',w,s,run,document),'bz_visual_source_unaccepted') from vf;
select public.bz_review_campaign_generation(w,s,run,0,'accepted','Reviewed fixture for private use') from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,0,1,%L::jsonb,false)',w,s,run,document),'bz_invalid_visual') from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,0,1,%L::jsonb,true)',w,s,run,document||'{"publish":true}'::jsonb),'bz_invalid_visual') from vf;
select public.bz_save_campaign_visual(w,s,run,0,1,document,true) from vf;
update vf set document=document||jsonb_build_object('schema','campaign-visuals-v2','templates',jsonb_build_object('pins',jsonb_build_array('editorial','midnight'),'carousel','headline','linkedin','classic'),'linkedin',jsonb_build_object('title','Standalone headline','body','Reviewed excerpt'));
select public.bz_save_campaign_visual(w,s,run,1,1,document,true) from vf;
do $$declare v jsonb;begin select public.bz_campaign_visual(w,s,run) into v from vf;if v->>'version'<>'2' or v#>>'{document,templates,pins,0}'<>'editorial' or v#>>'{document,linkedin,title}'<>'Standalone headline' or v#>>'{revisions,1,document,schema}'<>'campaign-visuals-v1' then raise exception 'Upgrade lost v1 history or v2 fields';end if;end;$$;
select public.bz_save_campaign_visual(w,s,run,2,1,document,true) from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,1,1,%L::jsonb,true)',w,s,run,document),'bz_conflict') from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,2,1,%L::jsonb,true)',w,s,run,jsonb_set(document,'{templates,carousel}','"untrusted"')),'bz_invalid_visual') from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,2,1,%L::jsonb,true)',w,s,run,jsonb_set(document,'{templates,pins}','["classic"]')),'bz_invalid_visual') from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,2,1,%L::jsonb,true)',w,s,run,jsonb_set(document,'{linkedin,script}','"bad"')),'bz_invalid_visual') from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,2,1,%L::jsonb,false)',w,s,run,document),'bz_invalid_visual') from vf;
select set_config('request.jwt.claim.sub',(select viewer_id::text from vf),true);
select public.bz_campaign_visual(w,s,run) from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,2,1,%L::jsonb,true)',w,s,run,document),'bz_forbidden') from vf;
select set_config('request.jwt.claim.sub',(select outsider::text from vf),true);
select pg_temp.vexpect(format('select public.bz_campaign_visual(%L,%L,%L)',w,s,run),'bz_forbidden') from vf;
select set_config('request.jwt.claim.sub',(select owner_id::text from vf),true);
select public.bz_review_campaign_generation(w,s,run,1,'changes_requested','Recheck source') from vf;
select pg_temp.vexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,2,1,%L::jsonb,true)',w,s,run,document),'bz_visual_source_unaccepted') from vf;
reset role;
do $$begin if has_function_privilege('authenticated','bizoveya_private.valid_visual_document_v1(jsonb)','execute') or has_function_privilege('anon','bizoveya_private.valid_visual_document(jsonb)','execute') then raise exception 'Private validator exposed';end if;if (select count(*) from bizoveya_private.campaign_visual_revisions where generation_id=(select run from vf))<>2 then raise exception 'No-op duplicated history';end if;end;$$;
rollback;
