-- Local ephemeral fixture only. Never run on hosted data.
begin;
create temporary table ptf(owner_id uuid,other_id uuid,template_id uuid,recipe jsonb);
insert into ptf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),'{"schema":"private-template-recipe-v1","renderer":"campaign-scenes-v2","name":"Private design","brand":{"name":"Fixture brand","accent":"#5271FF","footer":"Private test"},"templates":{"pins":["classic","midnight"],"carousel":"editorial","linkedin":"headline"}}');
insert into auth.users(id) select owner_id from ptf union all select other_id from ptf;
create function pg_temp.pexpect(q text,n text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,n)>0 then return;else raise exception 'Unexpected: %',sqlerrm;end if;end;raise exception 'Expected %',n;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,anon,service_role',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;
grant all on ptf to authenticated,anon,service_role;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select owner_id::text from ptf),true);
select public.bz_save_private_template(template_id,0,recipe) from ptf;
do $$declare r jsonb;begin select public.bz_private_template(template_id) into r from ptf;if jsonb_array_length(r->'versions')<>1 or r#>>'{versions,0,version}'<>'1' or (r#>>'{versions,0,createdAt}')!~ 'Z$' then raise exception 'Bad initial version or timestamp';end if;end;$$;
select public.bz_save_private_template(template_id,1,jsonb_set(recipe,'{brand,accent}','"#ff0000"')) from ptf;
do $$declare r jsonb;begin select public.bz_private_template(template_id) into r from ptf;if r#>>'{versions,0,recipe,brand,accent}'<>'#5271FF' or r#>>'{versions,1,recipe,brand,accent}'<>'#ff0000' then raise exception 'History rewritten';end if;end;$$;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,1,%L::jsonb)',template_id,recipe),'bz_conflict') from ptf;
select pg_temp.pexpect(format('select public.bz_archive_private_template(%L,1)',template_id),'bz_conflict') from ptf;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,2,%L::jsonb)',template_id,recipe||'{"script":"evil"}'::jsonb),'bz_invalid_template') from ptf;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,2,%L::jsonb)',template_id,jsonb_set(recipe,'{templates,carousel}','"unknown"')),'bz_invalid_template') from ptf;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,2,%L::jsonb)',template_id,jsonb_set(recipe,'{brand}', '[]')),'bz_invalid_template') from ptf;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,2,%L::jsonb)',template_id,jsonb_set(recipe,'{name}',to_jsonb(E'bad\nname'::text))),'bz_invalid_template') from ptf;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,NULL,%L::jsonb)',template_id,recipe),'bz_invalid_template') from ptf;
select pg_temp.pexpect('select * from bizoveya_private.private_templates','permission denied');
select set_config('request.jwt.claim.sub',(select other_id::text from ptf),true);
do $$begin if public.bz_private_templates(true)<>'[]'::jsonb then raise exception 'Foreign inventory exposed';end if;end;$$;
select pg_temp.pexpect(format('select public.bz_private_template(%L)',template_id),'bz_template_unavailable') from ptf;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,0,%L::jsonb)',template_id,recipe),'bz_template_unavailable') from ptf;
select pg_temp.pexpect(format('select public.bz_archive_private_template(%L,2)',template_id),'bz_template_unavailable') from ptf;
select pg_temp.pexpect(format('select public.bz_private_template(%L)',gen_random_uuid()),'bz_template_unavailable');
select set_config('request.jwt.claim.sub',(select owner_id::text from ptf),true);
select public.bz_archive_private_template(template_id,2) from ptf;
select public.bz_archive_private_template(template_id,2) from ptf;
do $$declare r jsonb;begin select public.bz_private_template(template_id) into r from ptf;if r->>'archived'<>'true' or jsonb_array_length(r->'versions')<>2 or public.bz_private_templates(false)<>'[]'::jsonb or jsonb_array_length(public.bz_private_templates(true))<>1 then raise exception 'Archive lost history or inventory visibility';end if;end;$$;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,2,%L::jsonb)',template_id,recipe),'bz_template_unavailable') from ptf;
reset role;
select pg_temp.pexpect(format('update bizoveya_private.private_template_versions set recipe=%L::jsonb where template_id=%L',recipe,template_id),'bz_template_immutable') from ptf;
select pg_temp.pexpect(format('delete from bizoveya_private.private_template_versions where template_id=%L',template_id),'bz_template_immutable') from ptf;
select pg_temp.pexpect(format('delete from bizoveya_private.private_templates where id=%L',template_id),'bz_template_immutable') from ptf;
select pg_temp.pexpect(format('update bizoveya_private.private_templates set creator_id=%L where id=%L',other_id,template_id),'bz_template_immutable') from ptf;
update auth.users set deleted_at=now() where id=(select owner_id from ptf);
set local role authenticated;
select pg_temp.pexpect('select public.bz_private_templates(true)','bz_forbidden');
select pg_temp.pexpect(format('select public.bz_private_template(%L)',template_id),'bz_forbidden') from ptf;
select pg_temp.pexpect(format('select public.bz_save_private_template(%L,0,%L::jsonb)',gen_random_uuid(),recipe),'bz_forbidden') from ptf;
reset role;
update auth.users set deleted_at=null where id=(select owner_id from ptf);
set local role anon;
select pg_temp.pexpect('select public.bz_private_templates(true)','permission denied');
reset role;set local role service_role;
select pg_temp.pexpect('select public.bz_private_templates(true)','permission denied');
select pg_temp.pexpect('select * from bizoveya_private.private_template_versions','permission denied');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub','',true);
select pg_temp.pexpect('select public.bz_private_templates(true)','bz_forbidden');
select set_config('request.jwt.claim.sub',(select other_id::text from ptf),true);
do $$declare i integer;id_ uuid:=gen_random_uuid();r_ jsonb;begin
 select recipe into r_ from ptf;
 perform public.bz_save_private_template(id_,0,r_);
 for i in 1..49 loop perform public.bz_save_private_template(id_,i,r_);end loop;
 perform pg_temp.pexpect(format('select public.bz_save_private_template(%L,50,%L::jsonb)',id_,r_),'bz_template_limit');
 for i in 1..31 loop perform public.bz_save_private_template(gen_random_uuid(),0,r_);end loop;
 perform pg_temp.pexpect(format('select public.bz_save_private_template(%L,0,%L::jsonb)',gen_random_uuid(),r_),'bz_template_limit');
 if jsonb_array_length(public.bz_private_templates(true))<>32 then raise exception 'Quota mismatch';end if;
end;$$;
reset role;
delete from auth.users where id=(select owner_id from ptf);
do $$begin if exists(select 1 from bizoveya_private.private_templates where creator_id=(select owner_id from ptf)) or exists(select 1 from bizoveya_private.private_template_versions where creator_id=(select owner_id from ptf)) then raise exception 'Deleted creator retained private recipes';end if;end;$$;
rollback;
