-- Ephemeral local fixture only. Never run against hosted data.
begin;
create temporary table pv(owner_id uuid,other_id uuid,w uuid,s uuid,c uuid,run uuid,template_id uuid,document jsonb,recipe jsonb);
insert into pv values(gen_random_uuid(),gen_random_uuid(),null,null,gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),jsonb_build_object('schema','campaign-visuals-v2','brand',jsonb_build_object('name','Original brand','accent','#123456','footer','Private test'),'pins',jsonb_build_array(jsonb_build_object('title','Pin one','body','Reviewed source excerpt'),jsonb_build_object('title','Pin two','body','Reviewed source excerpt')),'slides',(select jsonb_agg(jsonb_build_object('title','Slide '||n,'body','Reviewed source excerpt')) from generate_series(1,6)n),'templates',jsonb_build_object('pins',jsonb_build_array('classic','midnight'),'carousel','classic','linkedin','headline'),'linkedin',jsonb_build_object('title','LinkedIn title','body','Reviewed excerpt')),jsonb_build_object('schema','private-template-recipe-v1','renderer','campaign-scenes-v2','name','Pinned design','brand',jsonb_build_object('name','Template brand','accent','#5271FF','footer','Copied recipe'),'templates',jsonb_build_object('pins',jsonb_build_array('editorial','midnight'),'carousel','headline','linkedin','classic')));
insert into auth.users(id) select owner_id from pv union all select other_id from pv;
create function pg_temp.pvexpect(q text,n text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,n)>0 then return;else raise exception 'Unexpected: %',sqlerrm;end if;end;raise exception 'Expected %',n;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,anon,service_role',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;grant all on pv to authenticated;
set local role authenticated;select set_config('request.jwt.claim.sub',(select owner_id::text from pv),true);
update pv set w=(select id from public.bz_create_workspace('Provenance fixture'));
update pv set s=(select id from public.bz_register_site(w,'Provenance site','external','business','https://provenance.example.com/',null,'active',true));
select public.bz_save_campaign(w,s,c,'{"title":"Provenance fixture","brief":"Reviewed source","blog":"","pinterest":"","linkedin":""}',0) from pv;
reset role;
insert into bizoveya_private.generation_runs(id,campaign_id,site_id,campaign_version,status,input_snapshot,output_document,requested_by) select run,c,s,1,'succeeded','{}','{"schema":"campaign-generation-output-v1","stages":{"quality":{"approved":true,"issues":[]}}}',owner_id from pv;
set local role authenticated;select set_config('request.jwt.claim.sub',(select owner_id::text from pv),true);
select public.bz_review_campaign_generation(w,s,run,0,'accepted','Reviewed provenance fixture') from pv;
select public.bz_save_campaign_visual(w,s,run,0,1,document,true) from pv;
select public.bz_save_private_template(template_id,0,recipe) from pv;
select public.bz_save_private_template(template_id,1,jsonb_set(recipe,'{brand,accent}','"#ff0000"')) from pv;
select public.bz_apply_private_template_to_visual(w,s,run,1,1,template_id,1,document,true) from pv;
do $$declare v jsonb;begin select public.bz_campaign_visual(w,s,run) into v from pv;if v#>>'{document,schema}'<>'campaign-visuals-v3' or v#>>'{document,templateReference,version}'<>'1' or v#>>'{document,templateRecipe,brand,accent}'<>'#5271FF' or v#>>'{document,brand,accent}'<>'#5271FF' or v#>>'{document,pins,0,title}'<>'Pin one' then raise exception 'Copied provenance/content mismatch';end if;end;$$;
select pg_temp.pvexpect(format('select public.bz_save_campaign_visual(%L,%L,%L,2,1,%L::jsonb,true)',w,s,run,(document||jsonb_build_object('schema','campaign-visuals-v3','templateReference',jsonb_build_object('templateId',template_id,'version',2,'renderer','campaign-scenes-v2'),'templateRecipe',recipe))),'bz_invalid_visual') from pv;
select pg_temp.pvexpect(format('select public.bz_apply_private_template_to_visual(%L,%L,%L,1,1,%L,2,%L::jsonb,true)',w,s,run,template_id,document),'bz_conflict') from pv;
select public.bz_archive_private_template(template_id,2) from pv;
do $$declare v jsonb;begin select public.bz_campaign_visual(w,s,run) into v from pv;if v#>>'{document,templateReference,version}'<>'1' then raise exception 'Archive rewrote saved provenance';end if;end;$$;
select pg_temp.pvexpect(format('select public.bz_apply_private_template_to_visual(%L,%L,%L,2,1,%L,1,%L::jsonb,true)',w,s,run,template_id,document),'bz_template_unavailable') from pv;
select set_config('request.jwt.claim.sub',(select other_id::text from pv),true);
select pg_temp.pvexpect(format('select public.bz_apply_private_template_to_visual(%L,%L,%L,2,1,%L,1,%L::jsonb,true)',w,s,run,template_id,document),'bz_template_unavailable') from pv;
reset role;
do $$begin if has_function_privilege('authenticated','bizoveya_private.save_campaign_visual_internal(uuid,uuid,uuid,integer,integer,jsonb,boolean,boolean)','execute') then raise exception 'Internal provenance writer exposed';end if;end;$$;
rollback;
