-- Local ephemeral fixture only. Never run on hosted data.
begin;
create temporary table pmf(actor_id uuid,other_id uuid,workspace_id uuid,site_id uuid,media_id uuid,descriptor jsonb,path text);
insert into pmf values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),'{"schema":"private-media-descriptor-v1","mime":"image/png","bytes":1024,"width":1000,"height":1500,"sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","alt":"Blue abstract background","origin":"user-upload","rights":{"basis":"own-work","evidence":"Created by me for private draft use.","attested":true}}',null);
update pmf set path=concat(actor_id,'/',workspace_id,'/',site_id,'/',media_id,'/1/',descriptor->>'sha256','.png');
insert into auth.users(id) select actor_id from pmf union all select other_id from pmf;
insert into public.bizoveya_workspaces(id,owner_id,name) select workspace_id,actor_id,'Fixture workspace' from pmf;
insert into public.bizoveya_memberships(workspace_id,user_id,role) select workspace_id,actor_id,'owner' from pmf;
insert into public.bizoveya_sites(id,workspace_id,name,mode,kind,status,created_by) select site_id,workspace_id,'Fixture site','native_business','business','active',actor_id from pmf;
create function pg_temp.pmexpect(q text,n text) returns void language plpgsql as $$begin begin execute q;exception when others then if strpos(sqlerrm,n)>0 then return;else raise exception 'Unexpected: %',sqlerrm;end if;end;raise exception 'Expected %',n;end;$$;
do $$begin execute format('grant usage on schema %I to authenticated,anon,service_role',(select nspname from pg_namespace where oid=pg_my_temp_schema()));end;$$;
grant all on pmf to authenticated,anon,service_role;

set local role authenticated;select set_config('request.jwt.claim.sub',(select actor_id::text from pmf),true);
select pg_temp.pmexpect(format('select public.bz_record_sanitized_private_media(%L,%L,%L,%L,0,%L::jsonb,%L)',actor_id,workspace_id,site_id,media_id,descriptor,path),'permission denied') from pmf;
do $$begin if public.bz_private_media_inventory((select workspace_id from pmf),(select site_id from pmf),true)<>'[]'::jsonb then raise exception 'Unexpected initial inventory';end if;end;$$;
reset role;set local role service_role;
select set_config('request.jwt.claim.role','service_role',true);
select public.bz_record_sanitized_private_media(actor_id,workspace_id,site_id,media_id,0,descriptor,path) from pmf;
select pg_temp.pmexpect(format('select public.bz_record_sanitized_private_media(%L,%L,%L,%L,0,%L::jsonb,%L)',actor_id,workspace_id,site_id,media_id,descriptor,path),'bz_conflict') from pmf;
select pg_temp.pmexpect(format('select public.bz_record_sanitized_private_media(%L,%L,%L,%L,1,%L::jsonb,%L)',actor_id,workspace_id,site_id,media_id,descriptor,'wrong/path.png'),'bz_invalid_media') from pmf;
reset role;set local role authenticated;select set_config('request.jwt.claim.sub',(select actor_id::text from pmf),true);
do $$declare r jsonb;begin select public.bz_private_media((select workspace_id from pmf),(select site_id from pmf),(select media_id from pmf)) into r;if r->>'revision'<>'1' or r#>>'{versions,0,review}' is not null or r#>>'{versions,0,descriptor,sha256}'<>repeat('a',64) then raise exception 'Bad media record';end if;end;$$;
select public.bz_review_private_media(workspace_id,site_id,media_id,1,1,'accepted','Reviewed image and rights for private draft use.') from pmf;
select pg_temp.pmexpect(format('select public.bz_review_private_media(%L,%L,%L,1,1,%L,%L)',workspace_id,site_id,media_id,'rejected','Changed mind'),'bz_conflict') from pmf;
select pg_temp.pmexpect(format('select public.bz_archive_private_media(%L,%L,%L,1)',workspace_id,site_id,media_id),'bz_conflict') from pmf;
do $$declare r jsonb;begin select public.bz_private_media((select workspace_id from pmf),(select site_id from pmf),(select media_id from pmf)) into r;if r->>'revision'<>'2' or r#>>'{versions,0,review,decision}'<>'accepted' or r#>>'{versions,0,review,actorId}'<>(select actor_id::text from pmf) then raise exception 'Bad review';end if;end;$$;
select set_config('request.jwt.claim.sub',(select other_id::text from pmf),true);
select pg_temp.pmexpect(format('select public.bz_private_media(%L,%L,%L)',workspace_id,site_id,media_id),'bz_forbidden') from pmf;
select pg_temp.pmexpect(format('select public.bz_review_private_media(%L,%L,%L,2,1,%L,%L)',workspace_id,site_id,media_id,'accepted','Foreign'),'bz_forbidden') from pmf;
reset role;set local role authenticated;select set_config('request.jwt.claim.sub',(select actor_id::text from pmf),true);
select public.bz_archive_private_media(workspace_id,site_id,media_id,2) from pmf;
select public.bz_archive_private_media(workspace_id,site_id,media_id,3) from pmf;
do $$declare r jsonb;begin select public.bz_private_media((select workspace_id from pmf),(select site_id from pmf),(select media_id from pmf)) into r;if r->>'revision'<>'3' or r->>'archived'<>'true' or jsonb_array_length(r->'versions')<>1 then raise exception 'Archive damaged media';end if;if public.bz_private_media_inventory((select workspace_id from pmf),(select site_id from pmf),false)<>'[]'::jsonb then raise exception 'Archived item visible';end if;end;$$;
select pg_temp.pmexpect('select * from bizoveya_private.private_media','permission denied');
select pg_temp.pmexpect('select * from bizoveya_private.private_media_versions','permission denied');
reset role;set local role anon;
select pg_temp.pmexpect(format('select public.bz_private_media_inventory(%L,%L,true)',workspace_id,site_id),'permission denied') from pmf;
select pg_temp.pmexpect(format('select public.bz_record_sanitized_private_media(%L,%L,%L,%L,0,%L::jsonb,%L)',actor_id,workspace_id,site_id,gen_random_uuid(),descriptor,path),'permission denied') from pmf;
reset role;
do $$begin if (select public from storage.buckets where id='campaign-private-media') or exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and (qual like '%campaign-private-media%' or with_check like '%campaign-private-media%')) then raise exception 'Private bucket exposed';end if;end;$$;
rollback;
