"use client";
import React, { useState } from "react";
import Image from "next/image";
import { ArrowUpRight, Layers3, MapPin, ChevronLeft, ChevronRight, Menu, X } from "lucide-react";
import { telephoneHref } from "@/domain/business-publication";
import { imageSchema, type BusinessDocument, type BusinessSection } from "@/domain/business";
function Photo({ url, alt, fit = "cover", position = "center" }: { url: string; alt: string; fit?: "cover" | "contain"; position?: "center" | "top" | "bottom" }) {
  const [failedUrl, setFailedUrl] = useState("");
  if (!url || failedUrl === url || !imageSchema.safeParse(url).success) return null;
  return <span className="business-photo-frame" data-fit={fit} data-position={position}><Image className="business-photo" src={url} alt={alt} width={960} height={720} sizes="(max-width: 650px) 100vw, 50vw" unoptimized onError={() => setFailedUrl(url)} /></span>;
}
function DesignArtwork({ preset }: { preset: BusinessDocument["templateId"] }) {
  if (preset === "wellness-studio-v1") return <div className="business-design-art" aria-hidden="true"><svg viewBox="0 0 400 440"><rect x="25" y="15" width="350" height="410" rx="175" fill="var(--bp-soft)"/><path d="M200 390V200M200 280C70 280 70 160 200 180M200 230C330 230 330 110 200 140" fill="none" stroke="var(--bp-ink)" strokeWidth="3"/><circle cx="200" cy="95" r="35" fill="var(--bp-accent)"/><path d="M75 390H325" stroke="var(--bp-ink)" strokeWidth="3"/></svg></div>;
  if (preset === "education-academy-v1") return <div className="business-design-art" aria-hidden="true"><svg viewBox="0 0 450 350"><rect x="20" y="20" width="410" height="310" rx="18" fill="var(--bp-soft)"/><path d="M50 100L220 55V285L50 315ZM220 55L390 100V315L220 285Z" fill="var(--bp-accent)" stroke="var(--bp-ink)" strokeWidth="4"/><path d="M80 130L185 103M80 170L185 143M80 210L185 183M255 105L355 132M255 145L355 172M255 185L355 212" stroke="var(--bp-ink)" strokeWidth="4"/><circle cx="355" cy="60" r="40" fill="var(--bp-ink)"/><path d="M355 35V85M330 60H380" stroke="var(--bp-accent)" strokeWidth="5"/></svg></div>;
  if (preset === "product-launch-v1") return <div className="business-design-art" aria-hidden="true"><svg viewBox="0 0 600 300"><rect x="30" y="20" width="540" height="260" rx="20" fill="var(--bp-soft)" stroke="var(--bp-accent)"/><path d="M30 70H570M150 70V280" stroke="var(--bp-accent)" opacity=".4"/><circle cx="55" cy="45" r="7" fill="var(--bp-accent)"/><circle cx="80" cy="45" r="7" fill="var(--bp-accent)" opacity=".5"/><rect x="180" y="100" width="110" height="60" rx="8" fill="var(--bp-accent)"/><rect x="310" y="100" width="110" height="60" rx="8" fill="var(--bp-accent)" opacity=".5"/><path d="M185 240L245 205L310 225L370 180L445 200L525 115" fill="none" stroke="var(--bp-accent)" strokeWidth="6"/></svg></div>;
  return <div className="business-design-art" aria-hidden="true">{preset === "local-services-v1" ? <svg viewBox="0 0 400 310"><rect x="10" y="10" width="380" height="290" rx="40" fill="var(--bp-soft)"/><path d="M80 150L200 50L320 150V265H80Z" fill="var(--bp-ink)"/><path d="M180 265V190H230V265M110 160H155V205H110Z" fill="var(--bp-accent)"/><circle cx="325" cy="75" r="38" fill="var(--bp-accent)"/><path d="M308 75L320 87L341 61" fill="none" stroke="var(--bp-ink)" strokeWidth="8"/><path d="M50 270H352" stroke="var(--bp-ink)" strokeWidth="4"/></svg> : preset === "creative-business-v1" ? <svg viewBox="0 0 600 270"><path d="M0 270V135A135 135 0 01270 135V270Z" fill="var(--bp-accent)"/><circle cx="430" cy="135" r="125" fill="none" stroke="var(--bp-accent)" strokeWidth="24"/><path d="M320 10L560 260M320 260L560 10" stroke="var(--bp-accent)" strokeWidth="24"/></svg> : <svg viewBox="0 0 350 390"><path d="M40 360V170A135 135 0 01310 170V360Z" fill="var(--bp-ink)"/><path d="M78 360V170A97 97 0 01272 170V360" fill="none" stroke="var(--bp-accent)" strokeWidth="2"/><path d="M116 360V170A59 59 0 01234 170V360" fill="none" stroke="var(--bp-accent)" strokeWidth="2"/><circle cx="175" cy="170" r="26" fill="var(--bp-accent)"/><path d="M175 200V360M40 290H310" stroke="var(--bp-accent)" strokeWidth="2"/></svg>}</div>;
}
function Testimonials({ section: s }: { section: BusinessSection }) {
  const [index, setIndex] = useState(0); const current = Math.min(index, Math.max(0,s.items.length - 1));
  const items = s.layout === "slider" ? s.items.slice(current,current+1) : s.layout === "featured" ? s.items.slice(0,1) : s.items;
  return <><div className={`business-quotes layout-${s.layout}`} aria-live={s.layout === "slider" ? "polite" : undefined}>{items.map((item,i) => <figure key={`${current}-${i}`}><blockquote>{item.body}</blockquote><figcaption><Photo url={item.image} alt={`Portrait of ${item.title}`} /><strong>{item.title}</strong></figcaption></figure>)}</div>{s.layout === "slider" && s.items.length > 1 && <div className="business-slider-controls"><button type="button" aria-label="Previous testimonial" onClick={() => setIndex((current+s.items.length-1)%s.items.length)}><ChevronLeft size={18}/></button><span>{current+1} / {s.items.length}</span><button type="button" aria-label="Next testimonial" onClick={() => setIndex((current+1)%s.items.length)}><ChevronRight size={18}/></button></div>}</>;
}
export function BusinessPreview({ document: d, demo = false, selectedId, onSelect, published = false }: { document: BusinessDocument; demo?: boolean; published?: boolean; selectedId?: string; onSelect?: (id: string) => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const navSections = d.sections.filter(s => s.visible && s.type !== "hero" && s.type !== "cta" && (!published || (s.type === "about" ? Boolean(d.about) : ["testimonials","projects","faq"].includes(s.type) ? s.items.length > 0 : true)));
  const contact = d.sections.find(s => s.visible && s.type === "contact");
  const services = d.sections.find(s => s.visible && s.type === "services");
  const actionHref = contact ? `#section-${contact.id}` : d.email ? `mailto:${d.email}` : services ? `#section-${services.id}` : undefined;
  const action = (label: string) => actionHref ? <a className="business-cta" href={actionHref}>{contact || d.email ? label : "Explore services"}<ArrowUpRight size={17} aria-hidden="true" /></a> : <p className="business-empty">Add a contact section or email to enable a customer action.</p>;
  return <article className="business-preview" data-accent={d.accent} data-font={d.font} data-preset={d.templateId} aria-label={published ? "Business website" : "Business website preview"}>
    <header className="business-nav"><strong>{d.logo ? <Photo url={d.logo} alt={`${d.name} logo`} fit="contain" /> : <Layers3 size={20} aria-hidden="true" />}{d.name}</strong><button type="button" className="business-menu-toggle" aria-label={menuOpen ? "Close website menu" : "Open website menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen(v => !v)}>{menuOpen ? <X size={20}/> : <Menu size={20}/>}</button><nav aria-label="Website sections" data-open={menuOpen}>{navSections.map(s => <a key={s.id} href={`#section-${s.id}`} onClick={event => { setMenuOpen(false); if (onSelect) { event.preventDefault(); onSelect(s.id); } }}>{({services:"Services",about:"About",testimonials:"Reviews",projects:"Work",faq:"FAQ",contact:"Contact",hero:"Home",cta:"Contact"} as const)[s.type]}</a>)}</nav></header>
    {demo && <p className="business-example">Fictional sample business · preview only</p>}
    {d.sections.filter(s => s.visible && (!published || (s.type === "about" ? Boolean(d.about) : ["testimonials","projects","faq"].includes(s.type) ? s.items.length > 0 : true))).map(s => <section key={s.id} id={`section-${s.id}`} data-section-type={s.type} data-layout={s.layout} data-tone={s.tone} className={`business-section section-${s.type} layout-${s.layout} ${selectedId === s.id ? "section-selected" : ""}`}>
      {onSelect && <button type="button" className="business-select-section" aria-label={`Edit ${s.type} section ${s.id}`} onClick={() => onSelect(s.id)}>Edit section</button>}
      {s.type === "hero" && <><div className="business-hero-copy"><p className="business-eyebrow">{s.heading || "WELCOME TO " + d.name}</p>{published && s.id === d.sections.find(x => x.visible && x.type === "hero")?.id ? <h1>{d.headline}</h1> : <h2>{d.headline}</h2>}{d.description && <p>{d.description}</p>}{action("Let’s talk")}</div>{s.image ? <Photo url={s.image} alt={s.body || d.name} fit={s.imageFit} position={s.imagePosition} /> : <DesignArtwork preset={d.templateId} />}</>}
      {s.type === "services" && <><p className="business-eyebrow">WHAT WE DO</p><h2>{s.heading || "Services shaped around you."}</h2>{s.body && <p>{s.body}</p>}<div className="business-services">{d.services.map((item,i) => <div key={i}><span className="business-number">{String(i+1).padStart(2,"0")}</span><h3>{item.title}</h3><p>{item.description}</p></div>)}</div></>}
      {s.type === "about" && <><div><p className="business-eyebrow">OUR APPROACH</p><h2>{s.heading || `A little about ${d.name}.`}</h2>{d.about ? <p>{d.about}</p> : <p className="business-empty">Add your business story in the editor.</p>}</div>{s.layout === "split" && <Photo url={s.image} alt={s.body || `About ${d.name}`} fit={s.imageFit} position={s.imagePosition} />}</>}
      {s.type === "testimonials" && <><p className="business-eyebrow">CUSTOMER VOICES</p><h2>{s.heading || "In their own words."}</h2>{s.body && <p>{s.body}</p>}{s.items.length ? <Testimonials section={s} /> : <p className="business-empty">Add genuine customer quotes with permission. No reviews are generated for you.</p>}</>}
      {s.type === "projects" && <><p className="business-eyebrow">SELECTED WORK</p><h2>{s.heading || "Work with a story."}</h2>{s.body && <p>{s.body}</p>}<div className="business-projects">{s.items.map((item,i) => <article key={i}><Photo url={item.image} alt={item.title} /><span className="business-number">PROJECT {String(i+1).padStart(2,"0")}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div>{!s.items.length && <p className="business-empty">Add your approved project stories. A clean text layout works without photographs.</p>}</>}
      {s.type === "faq" && <><p className="business-eyebrow">GOOD TO KNOW</p><h2>{s.heading || "Your questions, answered."}</h2>{s.body && <p>{s.body}</p>}<div className="business-faq">{s.items.map((item,i) => s.layout === "accordion" ? <details key={i}><summary>{item.title}</summary><p>{item.body}</p></details> : <div key={i}><h3>{item.title}</h3><p>{item.body}</p></div>)}</div>{!s.items.length && <p className="business-empty">Add answers approved by your business.</p>}</>}
      {s.type === "contact" && <><p className="business-eyebrow">LET’S TALK</p><h2>{s.heading || "Your next step starts here."}</h2>{s.body && <p>{s.body}</p>}{d.email ? <a className="business-cta" href={`mailto:${d.email}`}>Email {d.name}<ArrowUpRight size={17} aria-hidden="true" /></a> : telephoneHref(d.phone) ? <a className="business-cta" href={telephoneHref(d.phone)!}>Call {d.name}<ArrowUpRight size={17} aria-hidden="true" /></a> : !published ? <p className="business-empty">Add your contact email in the editor.</p> : null}<div className="business-contact-facts">{d.phone && <p>{telephoneHref(d.phone) ? <a href={telephoneHref(d.phone)!}>Call {d.phone}</a> : d.phone}</p>}{d.location && <p><MapPin size={16} aria-hidden="true" />{d.location}</p>}{d.hours && <p>{d.hours}</p>}</div></>}
      {s.type === "cta" && <><h2>{s.heading || "Let’s work together."}</h2>{s.body && <p>{s.body}</p>}{action("Contact " + d.name)}</>}
    </section>)}
    <footer className="business-footer">{d.name}{!published && " · Business website draft"}</footer>
  </article>;
}
