"use client";
import { useEffect,useRef,useState } from "react";
import { publicationIssues,publicationSchema,publicSitePath,type Publication } from "@/domain/business-publication";
import type { BusinessDocument } from "@/domain/business";
export function PublicationPanel({endpoint,siteId,document,draftVersion,dirty,readOnly}:{endpoint:string;siteId:string;document:BusinessDocument;draftVersion:number;dirty:boolean;readOnly:boolean}) {
 const [publication,setPublication]=useState<Publication|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const latch=useRef(false);
 async function refresh(signal?:AbortSignal){setLoading(true);setError("");try {const response=await fetch(endpoint,{cache:"no-store",signal});const result=await response.json();if(!response.ok)throw Error(result.error || "Could not load publication.");setPublication(result.publication ? publicationSchema.parse(result.publication):null);}catch(cause){if(!signal?.aborted)setError(cause instanceof Error?cause.message:"Could not load publication.");}finally{if(!signal?.aborted)setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);return()=>controller.abort();},[endpoint]); // eslint-disable-line react-hooks/exhaustive-deps
 const issues=publicationIssues(document);const current=publication?.active && publication.source_version===draftVersion;
 async function act(publish:boolean){if(readOnly||loading||latch.current|| (publish && (dirty||issues.length||draftVersion===0)))return;
 if(!window.confirm(publish?"Publish your saved visible business information publicly? Review contact details, permissions and content first.":"Take this website offline? Visitors will receive a not-found page."))return;
 latch.current=true;setBusy(true);setError("");setMessage("");try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({publish,expectedDraftVersion:draftVersion,expectedPublicationVersion:publication?.version??0})});const result=await response.json();if(!response.ok)throw Error(result.error || "Publication failed.");setPublication(publicationSchema.parse(result.publication));setMessage(publish?"Saved snapshot published. Future draft edits remain private until you publish again.":"Website unpublished. Your private draft and publication history are preserved.");}catch(cause){setError(cause instanceof Error?cause.message:"Publication failed.");}finally{latch.current=false;setBusy(false);}}
 return <section className="business-publication" aria-label="Website publishing"><div><span className="business-tag">WEBSITE PUBLISHING</span><h2>{loading?"Checking publication…":error?"Publication status unavailable":publication?.active?"Your website is live":"Your website is private"}</h2><p>{publication?.active?`Published draft ${publication.source_version} · ${current?"matches saved draft":"new draft changes are not public"}`:"Publish a saved snapshot when your content is ready."}</p></div><div>{publication?.active&&<a href={publicSitePath(siteId)} target="_blank" rel="noopener noreferrer">Open public website ↗</a>}{!readOnly&&<><button type="button" disabled={loading||busy||Boolean(error)||dirty||issues.length>0||draftVersion===0||Boolean(current)} onClick={()=>act(true)}>{busy?"Working…":publication?.active?"Publish saved changes":"Publish website"}</button>{publication?.active&&<button type="button" disabled={loading||busy} onClick={()=>act(false)}>Unpublish website</button>}</>}{error&&<button type="button" disabled={busy} onClick={()=>void refresh()}>Refresh publication status</button>}</div>{dirty&&<p>Save your draft before publishing. Unpublish does not discard unsaved edits.</p>}{issues.length>0&&<ul>{issues.map(issue=><li key={issue}>{issue}</li>)}</ul>}<p>Visitor URL: <code>{publicSitePath(siteId)}</code>. Only visible sections and their used fields are exposed to visitors. Review all visible content and image permissions. No custom domain or enquiry-form inbox is connected.</p>{error&&<p role="alert">{error} Refresh status after resolving setup or another-session changes.</p>}{message&&<p role="status">{message}</p>}</section>;
}
