"use client";
import {useEffect,useRef,useState} from "react";
import {sitePreferencesSchema,preferencesRecordSchema,contextPreviewSchema,type SitePreferences,type PreviewAgent,type ContextPreview} from "@bizoveya/agent-contract";
export function ReadinessRoom({initial,initialVersion,agents,role,endpoint}:{initial:SitePreferences;initialVersion:number;agents:PreviewAgent[];role:string;endpoint:string}){
 const [saved,setSaved]=useState(initial);const [doc,setDoc]=useState(initial);const [version,setVersion]=useState(initialVersion);const [selected,setSelected]=useState(agents[0]?.id??"");const [preview,setPreview]=useState<ContextPreview|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const lock=useRef(false);const dirty=JSON.stringify(saved)!==JSON.stringify(doc);const writable=role==="owner"||role==="editor";
 useEffect(()=>{if(!dirty)return;const unload=(e:BeforeUnloadEvent)=>e.preventDefault();const leave=(e:Event)=>{if(!window.confirm("Discard unsaved site preferences?"))e.preventDefault();};const link=(e:MouseEvent)=>{if((e.target as HTMLElement).closest("a[href]")&&!window.confirm("Discard unsaved site preferences?"))e.preventDefault();};window.addEventListener("beforeunload",unload);window.addEventListener("bizoveya:before-signout",leave);document.addEventListener("click",link,true);return()=>{window.removeEventListener("beforeunload",unload);window.removeEventListener("bizoveya:before-signout",leave);document.removeEventListener("click",link,true);};},[dirty]);
 async function run(save:boolean){if(lock.current)return;const agent=agents.find(a=>a.id===selected);const parsed=sitePreferencesSchema.safeParse(doc);if(save&&!parsed.success){setMessage(parsed.error.issues[0]?.message??"Check preferences.");return;}if(!save&&(!agent||dirty))return;lock.current=true;setBusy(true);setPreview(null);setMessage("");try{const r=await fetch(save?endpoint:`${endpoint}/preview`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(save?{document:parsed.data,expectedVersion:version}:{agentId:agent!.id,agentVersion:agent!.version,preferencesVersion:version})});const data=await r.json();if(!r.ok)throw new Error(data.error??"Request failed.");if(save){const next=preferencesRecordSchema.parse(data);setSaved(next.document);setDoc(next.document);setVersion(next.version);setMessage("Site preferences saved. These do not override platform permissions.");}else{setPreview(contextPreviewSchema.parse(data));setMessage("Current approved context loaded. No AI response was generated.");}}catch(e){setMessage(e instanceof Error?e.message:"Request failed.");}finally{lock.current=false;setBusy(false);}}
 return <section className="bz-agent-room"><div className="bz-card"><h2>Site preferences</h2><p>Version {version} · {writable?"Owner and editor can prepare guidance":"Read-only viewer"}. Customer guidance cannot grant tools or publish permission.</p><fieldset disabled={busy||!writable}>{([['brandVoice','Brand voice',400],['audience','Audience',600],['guidance','Site guidance',2000]] as const).map(([key,label,max])=><label key={key}>{label}<textarea value={doc[key]} maxLength={max} onChange={e=>{setDoc({...doc,[key]:e.target.value});setPreview(null);}}/></label>)}</fieldset><button className="bz-button" disabled={busy||!writable||!dirty} onClick={()=>void run(true)}>Save site preferences</button></div><div className="bz-card"><h2>Context preview</h2><p>Only versions approved for preview appear here. Platform instructions stay private. Preview is a snapshot; future execution must recheck approval and facts.</p>{!agents.length?<p>No agents are approved for context preview yet. Contact your platform operator.</p>:<><label>Agent<select disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setPreview(null);}}>{agents.map(a=><option key={a.id} value={a.id}>{a.name} · v{a.version}</option>)}</select></label><button className="bz-button" disabled={busy||dirty} onClick={()=>void run(false)}>Preview approved context</button>{dirty&&<p>Save preferences before previewing.</p>}</>}<p role="status">{message}</p>{preview&&<section><h3>{preview.agent.name} · preview v{preview.agent.version}</h3><p>Preference v{preview.preferencesVersion} · {preview.facts.length} approved facts · Live execution disabled</p><p>{preview.boundary}</p><dl>{Object.entries(preview.preferences).map(([k,v])=><div key={k}><dt>{{brandVoice:"Brand voice",audience:"Audience",guidance:"Site guidance"}[k as keyof SitePreferences]}</dt><dd>{v||"Not set"}</dd></div>)}</dl>{preview.facts.map(f=><article key={`${f.sourceId}:${f.sourceVersion}:${f.factId}`}><h4>{f.title}</h4><p>{f.text}</p><small>Source {f.sourceId} · revision {f.sourceVersion} · fact {f.factId} · approved {f.approvedAt}</small></article>)}{!preview.facts.length&&<p>No approved facts. Prepare and approve site knowledge before relying on agent context.</p>}</section>}</div></section>;
}
