import {z} from "zod";
import type {SupabaseClient} from "@supabase/supabase-js";
import {emptyPreferences,preferencesRecordSchema,previewAgentSchema,contextPreviewSchema,type SitePreferences} from "@bizoveya/agent-contract";
import {getSite,checkDatabaseError,WorkspaceError} from "@/features/workspaces/store";
import {canWriteWorkspace} from "@/domain/workspaces";
function check(error:{code?:string;message?:string}|null){if(["42P01","PGRST202","PGRST205"].includes(error?.code??""))throw new WorkspaceError(503,"Agent readiness needs migration 027. Ask the operator to complete setup.");if(error?.message==="bz_agent_preview_changed")throw new WorkspaceError(409,"Preview approval changed. Reload the agent catalog.");if(error?.message==="bz_conflict")throw new WorkspaceError(409,"Preferences changed. Reload before continuing.");checkDatabaseError(error);}
export async function loadReadiness(db:SupabaseClient,userId:string,wid:string,sid:string){const context=await getSite(db,userId,wid,sid);const p=await db.from("bizoveya_site_agent_preferences").select("*").eq("site_id",sid).maybeSingle();check(p.error);const pref=p.data?preferencesRecordSchema.parse(p.data):null;const r=await db.rpc("bz_site_agent_catalog",{p_workspace_id:wid,p_site_id:sid});check(r.error);return {...context,document:pref?.document??emptyPreferences,version:pref?.version??0,agents:z.array(previewAgentSchema).parse(r.data??[])};}
export async function savePreferences(db:SupabaseClient,userId:string,wid:string,sid:string,document:SitePreferences,version:number){const {workspace}=await getSite(db,userId,wid,sid);if(!canWriteWorkspace(workspace.role))throw new WorkspaceError(403,"Viewers can read preferences but cannot change them.");const r=await db.rpc("bz_save_site_agent_preferences",{p_workspace_id:wid,p_site_id:sid,p_document:document,p_expected_version:version});check(r.error);return preferencesRecordSchema.parse(Array.isArray(r.data)?r.data[0]:r.data);}
export async function previewContext(db:SupabaseClient,userId:string,wid:string,sid:string,agentId:string,agentVersion:number,preferencesVersion:number){await getSite(db,userId,wid,sid);const r=await db.rpc("bz_preview_site_agent",{p_workspace_id:wid,p_site_id:sid,p_agent_id:agentId,p_agent_version:agentVersion,p_preferences_version:preferencesVersion});check(r.error);return contextPreviewSchema.parse(r.data);}
