"use client";
import {useEffect,useRef,useState} from "react";
import {agentKinds,agentRecordSchema,agentAdminMutationSchema,capabilities,starterAgent,validateAgent,type AgentRecord,type AgentKind,type AgentDocument,type AgentAdminMutation} from "@bizoveya/agent-contract";
import {z} from "zod";
import {historySchema,type AgentHistory} from "./history";
export function AgentRegistry({initial}:{initial:AgentRecord[]}){
 const [records,setRecords]=useState(initial);const [selected,setSelected]=useState(initial[0]?.id??"");const current=records.find(a=>a.id===selected);
 const [kind,setKind]=useState<AgentKind>(current?.kind??"coordinator");const [slug,setSlug]=useState(current?.slug??"");const [doc,setDoc]=useState<AgentDocument>(current?.document??starterAgent("coordinator"));const [reason,setReason]=useState("");const [reviewed,setReviewed]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [history,setHistory]=useState<AgentHistory|null>(null);const lock=useRef(false);const historyRequest=useRef(0);
 const dirty=current?JSON.stringify(doc)!==JSON.stringify(current.document):slug.length>0||kind!=="coordinator"||JSON.stringify(doc)!==JSON.stringify(starterAgent("coordinator"));
 useEffect(()=>{if(!dirty)return;const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();};const leave=(e:Event)=>{if(!window.confirm("Discard unsaved agent rules?"))e.preventDefault();};const link=(e:MouseEvent)=>{if((e.target as HTMLElement).closest("a[href]")&&!window.confirm("Discard unsaved agent rules?"))e.preventDefault();};window.addEventListener("beforeunload",unload);window.addEventListener("bizoveya:before-admin-signout",leave);document.addEventListener("click",link,true);return()=>{window.removeEventListener("beforeunload",unload);window.removeEventListener("bizoveya:before-admin-signout",leave);document.removeEventListener("click",link,true);};},[dirty]);
 function choose(a?:AgentRecord){if(lock.current||dirty&&!window.confirm("Discard unsaved agent rules?"))return;historyRequest.current++;setSelected(a?.id??"");setKind(a?.kind??"coordinator");setSlug(a?.slug??"");setDoc(a?.document??starterAgent("coordinator"));setReason("");setReviewed(false);setHistory(null);setMessage("");}
 async function action(input:AgentAdminMutation){if(lock.current)return;const parsed=agentAdminMutationSchema.safeParse(input);if(!parsed.success){setMessage(parsed.error.issues[0]?.message??"Check the form.");return;}lock.current=true;setBusy(true);setMessage("");try{const r=await fetch("/api/admin/agents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(parsed.data)});const data=await r.json();if(!r.ok)throw new Error(data.error??"Change failed.");const next=z.array(agentRecordSchema).parse(data);const a=next.find(a=>a.id===input.id);setRecords(next);if(a){setSelected(a.id);setKind(a.kind);setSlug(a.slug);setDoc(a.document);}historyRequest.current++;setHistory(null);setReviewed(false);setMessage(input.action==="approve-preview"?"Approved for context preview only. Live execution remains disabled.":"Configuration updated. Live execution remains disabled.");}catch(e){setMessage(e instanceof Error?e.message:"Change failed.");}finally{lock.current=false;setBusy(false);}}
 async function showHistory(){if(!current||lock.current)return;const token=++historyRequest.current;lock.current=true;setBusy(true);try{const r=await fetch(`/api/admin/agents/${current.id}/history`,{cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.error??"History unavailable.");if(token===historyRequest.current)setHistory(historySchema.parse(data));}catch(e){setMessage(e instanceof Error?e.message:"History unavailable.");}finally{lock.current=false;setBusy(false);}}
 const valid=validateAgent(kind,doc);const base={id:current?.id??"",expectedRevision:current?.revision??0,reason};
 return <section className="ba-agent-room"><h1>Agent configuration</h1><p>Versioned platform defaults · context preview only</p><div className="ba-notice">This room reviews agent rules; model connections are managed in Model assignments. Checks verify configuration shape and declared capabilities; they do not prove model quality. Approval permits a context preview, never publication or external actions.</div><div className="ba-agent-grid"><aside aria-label="Agent selection">{records.map(a=><button key={a.id} disabled={busy} aria-pressed={selected===a.id} onClick={()=>choose(a)}>{a.document.name}<small>Draft v{a.latest_version} · {a.preview_version?`Preview v${a.preview_version}`:"Not approved"}</small></button>)}<button disabled={busy||records.length>=16} onClick={()=>choose()}>Create agent draft</button></aside><div><h2>{current?doc.name:"New agent draft"}</h2>{current&&<p>Revision {current.revision} · Schema {capabilities[kind].schema} · {current.checked?"Current draft checked":"Current draft unchecked"}</p>}
 <fieldset disabled={busy}><label>Identifier<input value={slug} maxLength={40} disabled={!!current} onChange={e=>setSlug(e.target.value)}/></label><label>Role<select value={kind} disabled={!!current} onChange={e=>{const k=e.target.value as AgentKind;setKind(k);setDoc(starterAgent(k));}}>{agentKinds.map(k=><option key={k} value={k}>{capabilities[k].label}</option>)}</select></label><label>Display name<input value={doc.name} maxLength={80} onChange={e=>setDoc({...doc,name:e.target.value})}/></label><label>Purpose<textarea value={doc.description} maxLength={500} onChange={e=>setDoc({...doc,description:e.target.value})}/></label><label>Platform instructions<textarea rows={8} value={doc.instructions} maxLength={8000} onChange={e=>setDoc({...doc,instructions:e.target.value})}/></label><label>Future model tier<select value={doc.modelTier} onChange={e=>setDoc({...doc,modelTier:e.target.value as AgentDocument["modelTier"]})}><option value="unconfigured">Unconfigured</option><option value="economical">Economical preference</option><option value="reasoning">Reasoning preference</option></select></label><label>Maximum steps<input type="number" min={1} max={8} value={doc.maxSteps} onChange={e=>setDoc({...doc,maxSteps:Number(e.target.value)})}/></label><label>Maximum output tokens<input type="number" min={128} max={4096} value={doc.maxOutputTokens} onChange={e=>setDoc({...doc,maxOutputTokens:Number(e.target.value)})}/></label><p>Declared capabilities: {doc.tools.join(", ")}. These labels do not execute tools.</p><label>Change / review reason<textarea value={reason} minLength={10} maxLength={300} onChange={e=>setReason(e.target.value)}/></label><p>The reason is an audit note, not an AI instruction. Enter 10–300 characters. It stays available after saving or checking; each action records its own event.</p><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I reviewed the saved version for context preview</label></fieldset>
 <div className="ba-agent-actions"><button disabled={busy||!valid.valid||!dirty||reason.trim().length<10||!slug} onClick={()=>void action({...base,id:current?.id??crypto.randomUUID(),action:"save",slug,kind,document:doc})}>Save new draft version</button><button disabled={busy||dirty||!current||current.checked||reason.trim().length<10} onClick={()=>void action({...base,action:"check"})}>Check saved configuration</button><button disabled={busy||dirty||!current?.checked||!reviewed||current.preview_version===current.latest_version||reason.trim().length<10} onClick={()=>current&&void action({...base,action:"approve-preview",version:current.latest_version,reviewed:true})}>Approve for context preview</button><button disabled={busy||dirty||!current?.preview_version||reason.trim().length<10} onClick={()=>void action({...base,action:"revoke-preview"})}>Revoke preview approval</button><button disabled={busy||!current} onClick={()=>void showHistory()}>Review version history</button></div><p role="status">{message}</p>{!valid.valid&&<p>{valid.message}</p>}
 {history&&<section><h3>Saved versions · latest 30</h3>{history.versions.map(v=><article key={v.version}><h4>Version {v.version} · {v.checked?"Checked":"Unchecked"}</h4><p>{v.reason} · {v.created_at} · Actor {v.actor_id??"migration"}</p><details><summary>View saved rules</summary><pre>{JSON.stringify(v.document,null,2)}</pre></details>{v.checked&&current?.preview_version!==v.version&&<button disabled={busy||dirty||!reviewed||reason.trim().length<10} onClick={()=>void action({...base,action:"approve-preview",version:v.version,reviewed:true})}>Use version {v.version} for preview</button>}</article>)}<h3>Review events · latest 60</h3>{history.events.map(e=><p key={e.id}>{e.action} · v{e.version} · {e.reason} · {e.occurred_at} · {e.actor_id??"migration"}</p>)}</section>}</div></div></section>;
}
