import { z } from "zod";
import type { SupabaseClient } from "@supabase/supabase-js";
import { agentRecordSchema, validateAgent, type AgentAdminMutation } from "@bizoveya/agent-contract";
import { AdminError } from "@/features/admin/access";
import {historySchema} from "./history";
function check(error:{code?:string;message?:string}|null){if(!error)return;const m=error.message??"";if(["42P01","PGRST202","PGRST205"].includes(error.code??""))throw new AdminError(503,"SETUP_REQUIRED","Apply migration 027 to enable agent configuration.");if(m==="bz_conflict")throw new AdminError(409,"CONFLICT","Configuration changed. Reload before reviewing or saving.");if(m.includes("mfa"))throw new AdminError(403,"MFA_REQUIRED","Verify your authenticator.");if(error.code==="42501")throw new AdminError(403,"FORBIDDEN","Current platform administrator access is required.");throw new AdminError(400,"INVALID_CONFIGURATION",({bz_duplicate_agent:"This agent identifier already exists.",bz_agent_limit:"The registry allows 16 agents and 200 versions per agent.",bz_agent_unchecked:"Check this version before approving it for preview."} as Record<string,string>)[m]??"Check the configuration, version and review reason.");}
export async function loadRegistry(db:SupabaseClient){const r=await db.rpc("bz_admin_agent_registry");check(r.error);return z.array(agentRecordSchema).parse(r.data??[]);}
export async function loadHistory(db:SupabaseClient,id:string){const r=await db.rpc("bz_admin_agent_history",{p_agent_id:id});check(r.error);return historySchema.parse(r.data);}
export async function mutateAgent(db:SupabaseClient,input:AgentAdminMutation){if(input.action==="save"){const v=validateAgent(input.kind,input.document);if(!v.valid)throw new AdminError(400,"INVALID_CONFIGURATION",v.message);}const r=await db.rpc("bz_admin_mutate_agent",{p_id:input.id,p_action:input.action,p_slug:input.action==="save"?input.slug:null,p_kind:input.action==="save"?input.kind:null,p_document:input.action==="save"?input.document:null,p_version:input.action==="approve-preview"?input.version:null,p_expected_revision:input.expectedRevision,p_reason:input.reason,p_reviewed:input.action==="approve-preview"?input.reviewed:false});check(r.error);return z.array(agentRecordSchema).parse(r.data);}
