import {z} from "zod";
export const providers=["nebius","openai","gemini"] as const;
export const slots={nebius:{reference:"platform-nebius",variable:"BIZOVEYA_NEBIUS_API_KEY"},openai:{reference:"platform-openai",variable:"BIZOVEYA_OPENAI_API_KEY"},gemini:{reference:"platform-gemini",variable:"BIZOVEYA_GEMINI_API_KEY"}} as const;
export const profileDocumentSchema=z.object({name:z.string().trim().min(1).max(80),provider:z.enum(providers),modelId:z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._/-]{0,119}$/,"Enter a verified model identifier, not a URL."),credentialRef:z.enum(["platform-nebius","platform-openai","platform-gemini"]),tier:z.enum(["economical","reasoning"]),maxOutputTokens:z.number().int().min(128).max(32768),dailyBudgetCents:z.number().int().min(1).max(100000)}).strict().refine(v=>v.credentialRef===slots[v.provider].reference,"Match the credential reference to the provider.").refine(v=>!/[\u0000-\u001f]/.test(v.name),"Remove control characters.");
export type ProfileDocument=z.infer<typeof profileDocumentSchema>;
export const profileRecordSchema=z.object({id:z.uuid(),slug:z.string(),version:z.number().int().positive(),revision:z.number().int().positive(),document:profileDocumentSchema,checked:z.boolean()});export type ProfileRecord=z.infer<typeof profileRecordSchema>;
export const credentialRecordSchema=z.object({id:z.enum(["platform-nebius","platform-openai","platform-gemini"]),provider:z.enum(providers),enabled:z.boolean(),version:z.number().int().positive()});export type CredentialRecord=z.infer<typeof credentialRecordSchema>;
export const registrySchema=z.object({profiles:z.array(profileRecordSchema),credentials:z.array(credentialRecordSchema)});export type Registry=z.infer<typeof registrySchema>;
const reason=z.string().trim().min(10).max(300).refine(v=>!/[\u0000-\u001f]/.test(v));
export const profileMutationSchema=z.discriminatedUnion("action",[z.object({action:z.literal("save"),id:z.uuid(),slug:z.string().regex(/^[a-z][a-z0-9-]{2,39}$/),document:profileDocumentSchema,expectedRevision:z.number().int().nonnegative(),reason}).strict(),z.object({action:z.literal("check"),id:z.uuid(),expectedRevision:z.number().int().positive(),reason}).strict()]);export type ProfileMutation=z.infer<typeof profileMutationSchema>;
export const credentialMutationSchema=z.object({id:z.enum(["platform-nebius","platform-openai","platform-gemini"]),action:z.enum(["enable","disable","record-rotation"]),expectedVersion:z.number().int().positive(),reviewed:z.literal(true),reason}).strict();export type CredentialMutation=z.infer<typeof credentialMutationSchema>;
export const historySchema=z.array(z.object({id:z.uuid(),resource:z.string(),resource_id:z.string(),version:z.number(),action:z.string(),actor_id:z.uuid().nullable(),reason:z.string(),occurred_at:z.string()}));
export const profileVersionsSchema=z.array(z.object({version:z.number(),document:profileDocumentSchema,actor_id:z.uuid().nullable(),reason:z.string(),created_at:z.string()}));
export const presenceSchema=z.object({id:credentialRecordSchema.shape.id,configured:z.boolean(),scope:z.literal("current-admin-deployment"),providerValidated:z.literal(false),runtimeEnabled:z.literal(false)});
export function starterProfile():ProfileDocument{return {name:"",provider:"nebius",credentialRef:"platform-nebius",modelId:"",tier:"economical",maxOutputTokens:1500,dailyBudgetCents:100};}
