import type {SupabaseClient} from "@supabase/supabase-js";
import {AdminError} from "@/features/admin/access";
import {registrySchema,historySchema,profileVersionsSchema,type ProfileMutation,type CredentialMutation} from "./contracts";
function check(error:{code?:string;message?:string}|null){if(!error)return;if(["42P01","PGRST202","PGRST205"].includes(error.code??""))throw new AdminError(503,"SETUP_REQUIRED","Apply migration 028 after027.");if(error.message==="bz_conflict")throw new AdminError(409,"CONFLICT","Settings changed. Reload before continuing.");if(error.code==="42501")throw new AdminError(403,"FORBIDDEN","Current platform admin and MFA are required.");throw new AdminError(400,"INVALID_PROFILE",({bz_credential_disabled:"Enable the credential reference before checking this profile.",bz_duplicate_model:"This profile identifier already exists.",bz_model_limit:"Maximum32 profiles and100 versions per profile."} as Record<string,string>)[error.message??""]??"Check the profile, reference and review reason.");}
export async function loadModels(db:SupabaseClient){const r=await db.rpc("bz_admin_model_registry");check(r.error);return registrySchema.parse(r.data);}
export async function mutateModel(db:SupabaseClient,i:ProfileMutation){const r=await db.rpc("bz_admin_mutate_model",{p_id:i.id,p_action:i.action,p_slug:i.action==="save"?i.slug:null,p_document:i.action==="save"?i.document:null,p_expected_revision:i.expectedRevision,p_reason:i.reason});check(r.error);return registrySchema.parse(r.data);}
export async function mutateCredential(db:SupabaseClient,i:CredentialMutation){const r=await db.rpc("bz_admin_mutate_credential",{p_id:i.id,p_action:i.action,p_expected_version:i.expectedVersion,p_reason:i.reason,p_reviewed:i.reviewed});check(r.error);return registrySchema.parse(r.data);}
export async function modelHistory(db:SupabaseClient,id:string){const r=await db.rpc("bz_admin_model_history",{p_id:id});check(r.error);return profileVersionsSchema.parse(r.data);}
export async function modelEvents(db:SupabaseClient){const r=await db.rpc("bz_admin_model_events");check(r.error);return historySchema.parse(r.data);}
