"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState, type FormEvent } from "react";
import { ArrowRight, Building2, Globe2, Plus, ShieldCheck } from "lucide-react";
import { createWorkspaceSchema, registerSiteSchema, updateSiteSchema, workspaceNameSchema, type SiteRecord, type WorkspaceAccess } from "@/domain/workspaces";
import { businessPresets, type BusinessDocument } from "@/domain/business";
async function send(url: string, method: string, body: unknown) {
  const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body), cache: "no-store" });
  const result = await response.json().catch(() => ({ error: "The server returned an unreadable response." }));
  if (!response.ok) throw new Error(result.error ?? "The request failed. Please retry.");
  return result;
}
function FormMessage({ error, success }: { error: string; success?: string }) { return <>{error && <p className="bz-alert" role="alert">{error}</p>}{success && <p className="bz-success" role="status">{success}</p>}</>; }
export function CreateWorkspaceForm({ journey, templateId }: { journey?: "new" | "existing"; templateId?: BusinessDocument["templateId"] }) {
  const router = useRouter(); const [name, setName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const pending = useRef(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (pending.current) return; const parsed = createWorkspaceSchema.safeParse({ name }); if (!parsed.success) return setError(parsed.error.issues[0].message); pending.current = true; setBusy(true); setError(""); try { const result = await send("/api/workspaces", "POST", parsed.data); router.replace(journey ? `/workspaces/${result.workspace.id}/sites/new?journey=${journey}${templateId ? `&template=${templateId}` : ""}` : `/workspaces/${result.workspace.id}`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create workspace."); pending.current = false; setBusy(false); } }
  return <form className="bz-form" onSubmit={submit}><label htmlFor="workspace-name">Workspace name</label><input id="workspace-name" value={name} onChange={event => setName(event.target.value)} maxLength={80} required placeholder="My business workspace" autoComplete="organization" disabled={busy} /><small>Keep several websites together without changing where they are hosted.</small><FormMessage error={error} /><button className="bz-button" disabled={busy}>{busy ? "Creating…" : "Create workspace"}<Plus size={16} aria-hidden="true" /></button></form>;
}
export function RegisterSiteForm({ workspaceId, projects, initialJourney = "existing", initialTemplate = "service-studio-v1" }: { workspaceId: string; projects: { id: string; name: string }[]; initialJourney?: "new" | "existing"; initialTemplate?: BusinessDocument["templateId"] }) {
  const router = useRouter(); const [journey, setJourney] = useState<"existing" | "new">(initialJourney); const [newType, setNewType] = useState<"business" | "portfolio">("business");
  const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [kind, setKind] = useState<"business" | "portfolio">("business"); const [projectId, setProjectId] = useState(""); const [status, setStatus] = useState<"active" | "paused">("active"); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const pending = useRef(false); const [templateId, setTemplateId] = useState(initialTemplate);
  const mode = journey === "existing" ? "external" : newType === "portfolio" ? "native_portfolio" : "native_business";
  async function submit(event: FormEvent) {
    event.preventDefault(); if (pending.current) return;
    const input = mode === "external" ? { name, mode, kind, url, status, ownershipConfirmed: confirmed } : mode === "native_portfolio" ? { name, mode, projectId, status, ownershipConfirmed: confirmed } : { name, mode, status, templateId, ownershipConfirmed: confirmed };
    const parsed = registerSiteSchema.safeParse(input); if (!parsed.success) return setError(parsed.error.issues[0].message);
    pending.current = true; setBusy(true); setError(""); try { const result = await send(`/api/workspaces/${workspaceId}/sites`, "POST", parsed.data); router.replace(mode === "native_business" ? `/workspaces/${workspaceId}/sites/${result.site.id}/editor` : mode === "native_portfolio" ? `/studio/${result.site.project_id}` : `/workspaces/${workspaceId}/sites/${result.site.id}`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not register site."); pending.current = false; setBusy(false); }
  }
  return <form className="bz-form" onSubmit={submit}><fieldset disabled={busy}><legend>Where are you starting?</legend><div className="bz-choices"><label className={journey === "existing" ? "selected" : ""}><input type="radio" name="journey" checked={journey === "existing"} onChange={() => { setJourney("existing"); setConfirmed(false); setError(""); }} /><Globe2 size={22} aria-hidden="true" /><strong>I have a website</strong><span>Keep it where it is. Register its public URL.</span></label><label className={journey === "new" ? "selected" : ""}><input type="radio" name="journey" checked={journey === "new"} onChange={() => { setJourney("new"); setConfirmed(false); setError(""); }} /><Building2 size={22} aria-hidden="true" /><strong>I need a website</strong><span>Create a business draft or link an owned portfolio.</span></label></div>
    {journey === "new" && <><label htmlFor="new-type">Website type</label><select id="new-type" value={newType} onChange={event => { setNewType(event.target.value as "business" | "portfolio"); setConfirmed(false); }}><option value="business">New business site · draft editor</option><option value="portfolio">Owned portfolio · existing Studio</option></select></>}
    {mode === "native_business" && <fieldset className="bz-template-picker"><legend>Choose your business design</legend><p>Each design has its own visual style. Customize sections, colors and content in Studio.</p><div className="bz-template-options">{businessPresets.map(preset => <label key={preset.id} className={templateId === preset.id ? "selected" : ""}><input type="radio" name="business-template" value={preset.id} checked={templateId === preset.id} onChange={() => setTemplateId(preset.id)}/><span className={`bz-template-swatch ${preset.id}`} aria-hidden="true"><i/><i/><i/></span><strong>{preset.name}</strong><span>{preset.description}</span></label>)}</div></fieldset>}
    <label htmlFor="site-name">Site name</label><input id="site-name" value={name} onChange={event => setName(event.target.value)} required maxLength={80} placeholder="Your business or website name" />
    {mode === "external" && <><label htmlFor="site-url">Public website URL</label><input id="site-url" type="url" required value={url} onChange={event => setUrl(event.target.value)} maxLength={2048} placeholder="https://your-business.com/" /><label htmlFor="site-kind">Category</label><select id="site-kind" value={kind} onChange={event => setKind(event.target.value as "business" | "portfolio")}><option value="business">Business website</option><option value="portfolio">Portfolio</option></select></>}
    {mode === "native_portfolio" && <><label htmlFor="project-id">Owned portfolio</label><select id="project-id" value={projectId} onChange={event => setProjectId(event.target.value)} required><option value="">Select a saved portfolio</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select><p>Need a portfolio first? <Link href="/start">Create one in the existing Studio</Link>, then return here to link it. Linking keeps its current owner and public URL.</p></>}
    <label htmlFor="site-status">Registry status</label><select id="site-status" value={status} onChange={event => setStatus(event.target.value as "active" | "paused")}><option value="active">Active</option><option value="paused">Paused</option></select>
    <div className="bz-callout"><ShieldCheck size={20} aria-hidden="true" /><p>{mode === "external" ? "Registration saves this URL only. It does not log in, fetch pages, install anything or grant edit access." : mode === "native_business" ? "Your selected design and a starter draft are saved together. Studio opens automatically. Publish an approved snapshot from Studio when you are ready." : "Only a portfolio you own can be linked. Workspace collaborators do not gain access to its editor."}</p></div>
    <label className="bz-check"><input type="checkbox" required checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I own this site or am authorized to register this website/project.</label>
    </fieldset><FormMessage error={error} /><div className="bz-actions"><button className="bz-button" disabled={busy || (mode === "native_portfolio" && !projects.length)}>{busy ? "Saving…" : mode === "native_business" ? "Create business site" : "Register site"}<ArrowRight size={17} aria-hidden="true" /></button><Link className="bz-button secondary" href={`/workspaces/${workspaceId}/sites`}>Cancel</Link></div></form>;
}
export function WorkspaceRenameForm({ workspace }: { workspace: WorkspaceAccess }) {
  const router = useRouter(); const [name, setName] = useState(workspace.name); const [savedName, setSavedName] = useState(workspace.name); const [version, setVersion] = useState(workspace.version); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (busy || name.trim() === savedName) return; const parsed = workspaceNameSchema.safeParse(name); if (!parsed.success) return setError(parsed.error.issues[0].message); setBusy(true); setError(""); setSuccess(""); try { const result = await send(`/api/workspaces/${workspace.id}`, "PATCH", { name: parsed.data, expectedVersion: version }); setVersion(result.workspace.version); setSavedName(result.workspace.name); setSuccess("Workspace name saved."); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save."); } finally { setBusy(false); } }
  return <form className="bz-form" onSubmit={submit}><label htmlFor="rename-workspace">Workspace name</label><input id="rename-workspace" required maxLength={80} value={name} onChange={event => setName(event.target.value)} disabled={busy || workspace.role !== "owner"} /><FormMessage error={error} success={success} />{workspace.role === "owner" ? <button className="bz-button" disabled={busy || name.trim() === savedName}>{busy ? "Saving…" : "Save workspace name"}</button> : <p>Only a workspace owner can rename this workspace.</p>}</form>;
}
export function SiteEditForm({ site }: { site: SiteRecord }) {
  const router = useRouter(); const [current, setCurrent] = useState(site); const [name, setName] = useState(site.name); const [status, setStatus] = useState(site.status); const [url, setUrl] = useState(site.url ?? ""); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (busy || (name.trim() === current.name && status === current.status && url === (current.url ?? ""))) return; const changedUrl = site.mode === "external" && url !== current.url; const parsed = updateSiteSchema.safeParse({ name, status, expectedVersion: current.version, ...(changedUrl ? { url, ownershipConfirmed: confirmed } : {}) }); if (!parsed.success) return setError(parsed.error.issues[0].message); setBusy(true); setError(""); setSuccess(""); try { const result = await send(`/api/workspaces/${site.workspace_id}/sites/${site.id}`, "PATCH", parsed.data); setCurrent(result.site); setName(result.site.name); setUrl(result.site.url ?? ""); setSuccess("Site record saved. The remote website was not changed."); setConfirmed(false); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save."); } finally { setBusy(false); } }
  return <form className="bz-form" onSubmit={submit}><label htmlFor="edit-site-name">Workspace site label</label><input id="edit-site-name" required maxLength={80} value={name} onChange={event => setName(event.target.value)} disabled={busy} />{site.mode === "external" && <><label htmlFor="edit-site-url">Public URL</label><input id="edit-site-url" type="url" required value={url} onChange={event => setUrl(event.target.value)} disabled={busy} maxLength={2048} />{url !== current.url && <label className="bz-check"><input type="checkbox" required checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I am authorized to register the new URL.</label>}</>}<label htmlFor="edit-site-status">Registry status</label><select id="edit-site-status" value={status} onChange={event => setStatus(event.target.value as "active" | "paused")} disabled={busy}><option value="active">Active</option><option value="paused">Paused</option></select><small>The site label organizes your workspace; edit the website’s business name in Studio. Status changes only this registry. It does not pause hosting or an agent.</small><FormMessage error={error} success={success} /><button className="bz-button" disabled={busy || (name.trim() === current.name && status === current.status && url === (current.url ?? ""))}>{busy ? "Saving…" : "Save site record"}</button></form>;
}
