"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { ArrowRight, Building2, Globe2, Plus, ShieldCheck } from "lucide-react";
import { createWorkspaceSchema, registerSiteSchema, updateSiteSchema, workspaceNameSchema, type SiteRecord, type WorkspaceAccess } from "@/domain/workspaces";
async function send(url: string, method: string, body: unknown) {
  const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body), cache: "no-store" });
  const result = await response.json().catch(() => ({ error: "The server returned an unreadable response." }));
  if (!response.ok) throw new Error(result.error ?? "The request failed. Please retry.");
  return result;
}
function FormMessage({ error, success }: { error: string; success?: string }) { return <>{error && <p className="bz-alert" role="alert">{error}</p>}{success && <p className="bz-success" role="status">{success}</p>}</>; }
export function CreateWorkspaceForm() {
  const router = useRouter(); const [name, setName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); const parsed = createWorkspaceSchema.safeParse({ name }); if (!parsed.success) return setError(parsed.error.issues[0].message); setBusy(true); setError(""); try { const result = await send("/api/workspaces", "POST", parsed.data); router.push(`/workspaces/${result.workspace.id}`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create workspace."); } finally { setBusy(false); } }
  return <form className="bz-form" onSubmit={submit}><label htmlFor="workspace-name">Workspace name</label><input id="workspace-name" value={name} onChange={event => setName(event.target.value)} maxLength={80} required placeholder="My business workspace" autoComplete="organization" disabled={busy} /><small>Keep several websites together without changing where they are hosted.</small><FormMessage error={error} /><button className="bz-button" disabled={busy}>{busy ? "Creating…" : "Create workspace"}<Plus size={16} aria-hidden="true" /></button></form>;
}
export function RegisterSiteForm({ workspaceId, projects }: { workspaceId: string; projects: { id: string; name: string }[] }) {
  const router = useRouter(); const [journey, setJourney] = useState<"existing" | "new">("existing"); const [newType, setNewType] = useState<"business" | "portfolio">("business");
  const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [kind, setKind] = useState<"business" | "portfolio">("business"); const [projectId, setProjectId] = useState(""); const [status, setStatus] = useState<"active" | "paused">("active"); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const mode = journey === "existing" ? "external" : newType === "portfolio" ? "native_portfolio" : "native_business";
  async function submit(event: FormEvent) {
    event.preventDefault();
    const input = mode === "external" ? { name, mode, kind, url, status, ownershipConfirmed: confirmed } : mode === "native_portfolio" ? { name, mode, projectId, status, ownershipConfirmed: confirmed } : { name, mode, status, ownershipConfirmed: confirmed };
    const parsed = registerSiteSchema.safeParse(input); if (!parsed.success) return setError(parsed.error.issues[0].message);
    setBusy(true); setError(""); try { const result = await send(`/api/workspaces/${workspaceId}/sites`, "POST", parsed.data); router.push(`/workspaces/${workspaceId}/sites/${result.site.id}`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not register site."); } finally { setBusy(false); }
  }
  return <form className="bz-form" onSubmit={submit}><fieldset disabled={busy}><legend>Where are you starting?</legend><div className="bz-choices"><label className={journey === "existing" ? "selected" : ""}><input type="radio" name="journey" checked={journey === "existing"} onChange={() => { setJourney("existing"); setConfirmed(false); setError(""); }} /><Globe2 size={22} aria-hidden="true" /><strong>I have a website</strong><span>Keep it where it is. Register its public URL.</span></label><label className={journey === "new" ? "selected" : ""}><input type="radio" name="journey" checked={journey === "new"} onChange={() => { setJourney("new"); setConfirmed(false); setError(""); }} /><Building2 size={22} aria-hidden="true" /><strong>I need a website</strong><span>Plan a business site or link an owned portfolio.</span></label></div>
    {journey === "new" && <><label htmlFor="new-type">Website type</label><select id="new-type" value={newType} onChange={event => { setNewType(event.target.value as "business" | "portfolio"); setConfirmed(false); }}><option value="business">New business site · planning record</option><option value="portfolio">Owned portfolio · existing Studio</option></select></>}
    <label htmlFor="site-name">Site name</label><input id="site-name" value={name} onChange={event => setName(event.target.value)} required maxLength={80} placeholder="Your business or website name" />
    {mode === "external" && <><label htmlFor="site-url">Public website URL</label><input id="site-url" type="url" required value={url} onChange={event => setUrl(event.target.value)} maxLength={2048} placeholder="https://your-business.com/" /><label htmlFor="site-kind">Category</label><select id="site-kind" value={kind} onChange={event => setKind(event.target.value as "business" | "portfolio")}><option value="business">Business website</option><option value="portfolio">Portfolio</option></select></>}
    {mode === "native_portfolio" && <><label htmlFor="project-id">Owned portfolio</label><select id="project-id" value={projectId} onChange={event => setProjectId(event.target.value)} required><option value="">Select a saved portfolio</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select><p>Need a portfolio first? <Link href="/start">Create one in the existing Studio</Link>, then return here to link it. Linking keeps its current owner and public URL.</p></>}
    <label htmlFor="site-status">Registry status</label><select id="site-status" value={status} onChange={event => setStatus(event.target.value as "active" | "paused")}><option value="active">Active</option><option value="paused">Paused</option></select>
    <div className="bz-callout"><ShieldCheck size={20} aria-hidden="true" /><p>{mode === "external" ? "Registration saves this URL only. It does not log in, fetch pages, install anything or grant edit access." : mode === "native_business" ? "This creates a planning record. Business templates, editing and publishing will be implemented in a later phase." : "Only a portfolio you own can be linked. Workspace collaborators do not gain access to its editor."}</p></div>
    <label className="bz-check"><input type="checkbox" required checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I own this site or am authorized to register this website/project.</label>
    </fieldset><FormMessage error={error} /><div className="bz-actions"><button className="bz-button" disabled={busy || (mode === "native_portfolio" && !projects.length)}>{busy ? "Saving…" : mode === "native_business" ? "Create planning record" : "Register site"}<ArrowRight size={17} aria-hidden="true" /></button><Link className="bz-button secondary" href={`/workspaces/${workspaceId}/sites`}>Cancel</Link></div></form>;
}
export function WorkspaceRenameForm({ workspace }: { workspace: WorkspaceAccess }) {
  const router = useRouter(); const [name, setName] = useState(workspace.name); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const parsed = workspaceNameSchema.safeParse(name); if (!parsed.success) return setError(parsed.error.issues[0].message); setBusy(true); setError(""); setSuccess(""); try { await send(`/api/workspaces/${workspace.id}`, "PATCH", { name: parsed.data, expectedVersion: workspace.version }); setSuccess("Workspace name saved."); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save."); } finally { setBusy(false); } }
  return <form className="bz-form" onSubmit={submit}><label htmlFor="rename-workspace">Workspace name</label><input id="rename-workspace" required maxLength={80} value={name} onChange={event => setName(event.target.value)} disabled={busy || workspace.role !== "owner"} /><FormMessage error={error} success={success} />{workspace.role === "owner" ? <button className="bz-button" disabled={busy}>{busy ? "Saving…" : "Save workspace name"}</button> : <p>Only a workspace owner can rename this workspace.</p>}</form>;
}
export function SiteEditForm({ site }: { site: SiteRecord }) {
  const router = useRouter(); const [name, setName] = useState(site.name); const [status, setStatus] = useState(site.status); const [url, setUrl] = useState(site.url ?? ""); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const changedUrl = site.mode === "external" && url !== site.url; const parsed = updateSiteSchema.safeParse({ name, status, expectedVersion: site.version, ...(changedUrl ? { url, ownershipConfirmed: confirmed } : {}) }); if (!parsed.success) return setError(parsed.error.issues[0].message); setBusy(true); setError(""); setSuccess(""); try { await send(`/api/workspaces/${site.workspace_id}/sites/${site.id}`, "PATCH", parsed.data); setSuccess("Site record saved. The remote website was not changed."); setConfirmed(false); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save."); } finally { setBusy(false); } }
  return <form className="bz-form" onSubmit={submit}><label htmlFor="edit-site-name">Site name</label><input id="edit-site-name" required maxLength={80} value={name} onChange={event => setName(event.target.value)} disabled={busy} />{site.mode === "external" && <><label htmlFor="edit-site-url">Public URL</label><input id="edit-site-url" type="url" required value={url} onChange={event => setUrl(event.target.value)} disabled={busy} maxLength={2048} />{url !== site.url && <label className="bz-check"><input type="checkbox" required checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I am authorized to register the new URL.</label>}</>}<label htmlFor="edit-site-status">Registry status</label><select id="edit-site-status" value={status} onChange={event => setStatus(event.target.value as "active" | "paused")} disabled={busy}><option value="active">Active</option><option value="paused">Paused</option></select><small>Status changes only this registry. It does not pause hosting or an agent.</small><FormMessage error={error} success={success} /><button className="bz-button" disabled={busy}>{busy ? "Saving…" : "Save site record"}</button></form>;
}
