import {describe,it,expect,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {dispatchGeneration} from './dispatch';
import {dispatchInputSchema,generationSetup} from './dispatch-contracts';
const id='11111111-1111-4111-8111-111111111111';const input={id,reason:'Authorize one synthetic private draft run',reviewed:true as const};
function fixture(){const rpc=vi.fn(async(name:string)=>({data:name==='bz_admin_identity'?{isAdmin:true,aal2:true}:name==='bz_admin_generation_queue'?[]:null,error:null}));const record=vi.fn(async()=>({data:null,error:null}));const execute=vi.fn(async()=>({status:'completed_for_human_review' as const}));return {db:{rpc} as unknown as SupabaseClient,rpc,record,deps:{env:{BIZOVEYA_ENABLE_CAMPAIGN_GENERATION:'true',NEXT_PUBLIC_SUPABASE_URL:'synthetic-url',SUPABASE_SERVICE_ROLE_KEY:'synthetic-recording-key'},recorder:{rpc:record} as unknown as SupabaseClient,execute}};}
describe('explicit draft dispatch',()=>{
 it('rejects missing consent and extra identity or provider fields',()=>{expect(dispatchInputSchema.safeParse({...input,reviewed:false}).success).toBe(false);expect(dispatchInputSchema.safeParse({...input,actorId:id}).success).toBe(false);expect(dispatchInputSchema.safeParse({...input,apiKey:'secret'}).success).toBe(false);});
 it('setup exposes booleans only',()=>{expect(generationSetup({SUPABASE_SERVICE_ROLE_KEY:'secret',NEXT_PUBLIC_SUPABASE_URL:'url'})).toEqual({enabled:false,recorderConfigured:true});});
 it('defaults off without authorization or execution',async()=>{const f=fixture();f.deps.env.BIZOVEYA_ENABLE_CAMPAIGN_GENERATION='false';await expect(dispatchGeneration(f.db,id,input,f.deps)).rejects.toMatchObject({code:'GENERATION_DISABLED'});expect(f.rpc).not.toHaveBeenCalled();expect(f.deps.execute).not.toHaveBeenCalled();});
 it('requires recording key before authorization',async()=>{const f=fixture();f.deps.env.SUPABASE_SERVICE_ROLE_KEY='';await expect(dispatchGeneration(f.db,id,input,f.deps)).rejects.toMatchObject({code:'RECORDER_REQUIRED'});expect(f.rpc).not.toHaveBeenCalled();});
 it('requires current admin MFA',async()=>{const f=fixture();f.rpc.mockResolvedValueOnce({data:{isAdmin:true,aal2:false},error:null} as never);await expect(dispatchGeneration(f.db,id,input,f.deps)).rejects.toMatchObject({code:'MFA_REQUIRED'});expect(f.deps.execute).not.toHaveBeenCalled();});
 it.each(['bz_forbidden','bz_generation_busy','bz_generation_stale'])('blocks %s before executing',async message=>{const f=fixture();f.rpc.mockImplementation(async name=>({data:name==='bz_admin_identity'?{isAdmin:true,aal2:true}:null,error:name==='bz_admin_authorize_generation'?{message}:null}) as never);await expect(dispatchGeneration(f.db,id,input,f.deps)).rejects.toMatchObject({code:'RUN_BLOCKED'});expect(f.deps.execute).not.toHaveBeenCalled();});
 it('authorizes first and finalizes through the private recorder',async()=>{const f=fixture();const r=await dispatchGeneration(f.db,id,input,f.deps);expect(r.result.status).toBe('completed_for_human_review');expect(f.rpc.mock.calls.map(c=>c[0])).toEqual(['bz_admin_identity','bz_admin_authorize_generation','bz_admin_generation_queue']);expect(f.record).toHaveBeenCalledWith('bz_finish_generation_dispatch',expect.objectContaining({p_id:id,p_result:'completed_for_human_review'}));expect(JSON.stringify(r)).not.toContain('synthetic-recording-key');});
 it('execution failure releases dispatch without retrying the engine',async()=>{const f=fixture();f.deps.execute.mockRejectedValueOnce(Error('provider failure'));await expect(dispatchGeneration(f.db,id,input,f.deps)).rejects.toMatchObject({code:'RUN_STOPPED'});expect(f.deps.execute).toHaveBeenCalledTimes(1);expect(f.record).toHaveBeenCalledWith('bz_finish_generation_dispatch',expect.objectContaining({p_result:'blocked'}));});
});
