'use client';
import Link from 'next/link';
import {useRef,useState} from 'react';
import {queueSchema,dispatchInputSchema,type generationSetup} from './dispatch-contracts';
import type {z} from 'zod';
export function GenerationRoom({initial}:{initial:{runs:z.infer<typeof queueSchema>;setup:ReturnType<typeof generationSetup>}}){
 const [runs,setRuns]=useState(initial.runs),[selected,setSelected]=useState(initial.runs[0]?.id??''),[reason,setReason]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const lock=useRef(false);
 const run=runs.find(r=>r.id===selected);const eligible=initial.setup.enabled&&initial.setup.recorderConfigured&&run&&!run.stale&&!run.leaseActive&&['prepared','running'].includes(run.status);
 async function refresh(){if(lock.current)return;setBusy(true);try{const r=await fetch('/api/admin/generations',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error??'Refresh failed');setRuns(queueSchema.parse(d.runs));setMessage('Run records refreshed. No provider request was made.');}catch(e){setMessage(e instanceof Error?e.message:'Refresh failed');}finally{setBusy(false);}}
 async function start(){if(lock.current)return;const i=dispatchInputSchema.safeParse({id:selected,reason,reviewed});if(!i.success)return;lock.current=true;setBusy(true);setMessage('Running the selected snapshot. Keep this page open; refresh records if the connection is lost.');try{const r=await fetch('/api/admin/generations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(i.data)}),d=await r.json();if(!r.ok)throw Error(d.error??'Run stopped');setRuns(queueSchema.parse(d.runs));setMessage(d.result.status==='completed_for_human_review'?'Drafts saved. Open the private campaign room to review them. Nothing was published.':'Run stopped. Inspect stage and spending records before another action.');}catch(e){setMessage(e instanceof Error?e.message:'Connection lost. Refresh run and spending records; do not resend blindly.');}finally{lock.current=false;setBusy(false);setReviewed(false);}}
 return <section className="ba-agent-room"><p className="ba-eyebrow">FOUNDER DRAFT PILOT</p><h1>Draft generation runs</h1><p>Only snapshots requested by you in a workspace you own appear here. Each run creates blog, Pinterest and LinkedIn text for human review. No images or publishing.</p><p><Link href="/admin/bindings">Model assignments</Link> · <Link href="/admin/spending">Spending controls</Link></p><p className="ba-notice">{initial.setup.enabled?'Pilot activation is enabled. Each request still requires explicit consent.':'Pilot is disabled. Review setup before enabling the admin-only flag.'}</p>
 <fieldset disabled={busy} style={{border:0,padding:0}}><label>Prepared snapshot<select value={selected} onChange={e=>{setSelected(e.target.value);setReviewed(false);}}><option value="">Select a snapshot</option>{runs.map(r=><option key={r.id} value={r.id}>{r.title} · campaign v{r.campaignVersion} · {r.status} · {r.id.slice(0,8)}</option>)}</select></label>{run&&<p>Snapshot {run.id} · {run.status} · {run.stale?'Settings changed: prepare a new snapshot':'Assignment/campaign check current'} · {run.leaseActive?'Active run lease':'No active run lease'}</p>}
 <label>Run authorization reason<textarea maxLength={300} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Authorize one private draft run for Do It With AI Tools."/></label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I reviewed the approved knowledge, current assignments and provider pricing, and authorize this one draft-only run.</label>
 <button disabled={!eligible||!reviewed||reason.trim().length<10} onClick={()=>void start()}>{busy?'Running…':'Run selected snapshot once'}</button><button disabled={busy} onClick={()=>void refresh()}>Refresh run records</button></fieldset><p role="status">{message}</p>
 <h2>Saved run records</h2>{runs.length===0?<p>Prepare a snapshot from your private campaign room first.</p>:runs.map(r=><article key={r.id}><h3>{r.title}</h3><p>{r.status} · campaign v{r.campaignVersion} · {r.outputAvailable?'Output saved':'No completed output'} · {new Date(r.createdAt).toLocaleString()}</p><code>{r.id}</code></article>)}<p>A stale snapshot preserves history. It cannot silently switch to new settings. Refresh never sends a model request.</p></section>;
}
