import {describe,it,expect,vi} from 'vitest';
import {starterAgent,agentKinds,type AgentKind} from '@bizoveya/agent-contract';
import {executeGeneration,type RuntimeDependencies} from './runtime';
import {stagePrompt,validateOutput,type Claim} from './contracts';
const source='11111111-1111-4111-8111-111111111111';const citation={sourceId:source,sourceVersion:1,factId:'f1'};
const outputs={coordinator:{schema:'campaign-plan-v1',topic:'AI workflows',audience:'Freelancers',objective:'Explain a practical workflow',requiredFacts:[citation],channelNotes:{blog:'Explain workflow',pinterest:'Summarize workflow',linkedin:'Discuss workflow'}},content:{schema:'campaign-drafts-v1',blog:{title:'AI workflows',summary:'A practical introduction',body:'Use AI thoughtfully and review outputs.',citations:[citation]},pinterest:{title:'AI workflows',description:'Discover a practical approach.',altText:'Text summarizing an AI workflow',citations:[citation]},linkedin:{post:'Use AI thoughtfully and review outputs.',citations:[citation]}},quality:{schema:'campaign-quality-v1',approved:true,issues:[],checkedCitations:[citation]}};
function context():Claim{return {execute:true,inputLimit:32768,outputLimit:1500,prior:{},snapshot:{schema:'campaign-generation-input-v1',campaign:{id:source,version:1,document:{title:'AI workflows',brief:'Use approved facts only',blog:'manual text is not evidence',pinterest:'',linkedin:''}},preferences:{version:0,document:{brandVoice:'Practical',audience:'Freelancers',guidance:'Draft only'}},knowledge:[{sourceId:source,sourceVersion:1,title:'Facts',facts:[{id:'f1',text:'Our website explains AI workflows.'}],approvedAt:'2026-10-04T00:00:00Z'}],stages:agentKinds.map(kind=>({kind,agentId:source,agentVersion:1,agent:{...starterAgent(kind),modelTier:'economical'},profile:{name:'Fixture',provider:'gemini',credentialRef:'platform-gemini',modelId:'fixture-model',tier:'economical',maxOutputTokens:1500,dailyBudgetCents:100}})),limits:{maxStages:3,maxAttemptsPerStage:1,publish:false,externalTools:false}}};}
function harness(){const events:string[]=[];const ctx=context();const rpc=vi.fn(async(name:string)=>{events.push(name);return {data:name==='bz_claim_campaign_generation_stage'?ctx:null,error:null};});const provider=vi.fn(async(kind:AgentKind)=>{events.push(kind);return {output:outputs[kind],error:null,inputTokens:100,outputTokens:100};});const deps={env:{BIZOVEYA_ENABLE_CAMPAIGN_GENERATION:'true',BIZOVEYA_GEMINI_API_KEY:'synthetic-key-never-sent'},recorder:{rpc} as unknown as RuntimeDependencies['recorder'],provider};return {deps,rpc,provider,ctx,events};}
describe('bounded draft runtime',()=>{
 it('defaults off with no storage or provider work',async()=>{const h=harness();h.deps.env.BIZOVEYA_ENABLE_CAMPAIGN_GENERATION='false';expect(await executeGeneration(source,source,h.deps)).toEqual({status:'disabled'});expect(h.rpc).not.toHaveBeenCalled();expect(h.provider).not.toHaveBeenCalled();});
 it('reserves and settles each role before moving on',async()=>{const h=harness();expect(await executeGeneration(source,source,h.deps)).toEqual({status:'completed_for_human_review'});expect(h.events).toEqual(agentKinds.flatMap(k=>['bz_claim_campaign_generation_stage','bz_record_generation_request',k,'bz_finish_campaign_generation_stage']));});
 it('never repeats a previously claimed stage',async()=>{const h=harness();h.rpc.mockResolvedValueOnce({data:{execute:false,status:'reserved',spendingState:'reserved'} as unknown as Claim,error:null});expect(await executeGeneration(source,source,h.deps)).toEqual({status:'already_claimed'});expect(h.provider).not.toHaveBeenCalled();});
 it('resumes after a successfully settled role without rerunning it',async()=>{const h=harness();h.rpc.mockResolvedValueOnce({data:{execute:false,status:'succeeded',spendingState:'settled'} as unknown as Claim,error:null});expect(await executeGeneration(source,source,h.deps)).toEqual({status:'completed_for_human_review'});expect(h.provider.mock.calls.map(c=>c[0])).toEqual(['content','quality']);});
 it('stops on unknown provider usage',async()=>{const h=harness();h.provider.mockResolvedValueOnce({output:outputs.coordinator,error:null,inputTokens:null as unknown as number,outputTokens:100});expect(await executeGeneration(source,source,h.deps)).toEqual({status:'failed',stage:'coordinator'});expect(h.provider).toHaveBeenCalledTimes(1);});
 it('settles thrown provider failures without retry',async()=>{const h=harness();h.provider.mockRejectedValueOnce(new Error('private provider details'));expect(await executeGeneration(source,source,h.deps)).toEqual({status:'failed',stage:'coordinator'});expect(h.rpc.mock.calls.at(-1)?.[0]).toBe('bz_finish_campaign_generation_stage');expect(h.provider).toHaveBeenCalledTimes(1);});
 it('rejects fabricated citations with usage preserved',async()=>{const h=harness();h.provider.mockResolvedValueOnce({output:{...outputs.coordinator,requiredFacts:[{...citation,factId:'invented'}]},error:null,inputTokens:100,outputTokens:100});expect(await executeGeneration(source,source,h.deps)).toEqual({status:'failed',stage:'coordinator'});expect(h.provider).toHaveBeenCalledTimes(1);});
 it('stops on token overrun',async()=>{const h=harness();h.provider.mockResolvedValueOnce({output:outputs.coordinator,error:null,inputTokens:50000,outputTokens:100});expect(await executeGeneration(source,source,h.deps)).toEqual({status:'failed',stage:'coordinator'});expect(h.provider).toHaveBeenCalledTimes(1);});
 it('missing key cancels before provider invocation',async()=>{const h=harness();h.deps.env.BIZOVEYA_GEMINI_API_KEY='';expect(await executeGeneration(source,source,h.deps)).toEqual({status:'failed',stage:'coordinator'});expect(h.provider).not.toHaveBeenCalled();expect(h.events.at(-1)).toBe('bz_cancel_unstarted_generation_stage');});
 it('oversized input fails preflight before request',async()=>{const h=harness();h.ctx.inputLimit=1;await expect(executeGeneration(source,source,h.deps)).resolves.toEqual({status:'failed',stage:'coordinator'});expect(h.provider).not.toHaveBeenCalled();});
 it('rejects oversized valid snapshot prompt',async()=>{const h=harness();h.ctx.inputLimit=10000;h.ctx.snapshot.knowledge[0].facts=Array.from({length:20},(_,i)=>({id:`f${i}`,text:'x'.repeat(2000)}));expect(await executeGeneration(source,source,h.deps)).toEqual({status:'failed',stage:'coordinator'});expect(h.provider).not.toHaveBeenCalled();});
 it('never advances after failed durable settlement',async()=>{const h=harness();h.rpc.mockImplementation(async(name:string)=>({data:name==='bz_claim_campaign_generation_stage'?h.ctx:null,error:name==='bz_finish_campaign_generation_stage'?{message:'unavailable'}:null} as never));await expect(executeGeneration(source,source,h.deps)).rejects.toThrow('do not retry');expect(h.provider).toHaveBeenCalledTimes(1);});
 it('keeps manual text out of approved evidence',()=>{const p=stagePrompt('content',context());expect(p.prompt).not.toContain('manual text is not evidence');expect(p.instructions).toContain('untrusted data');});
 it('requires citations for every channel',()=>{const c=context();expect(()=>validateOutput('content',{...outputs.content,pinterest:{...outputs.content.pinterest,citations:[]}},c.snapshot)).toThrow('Each channel');});
 it('rejects approval with blockers',()=>{expect(()=>validateOutput('quality',{...outputs.quality,issues:[{channel:'shared',severity:'blocker',message:'Unsupported claim'}]},context().snapshot)).toThrow('Conflicting');});
});
