'use client';
import {useRef,useState} from 'react';
import Link from 'next/link';
import type {loadSpendingRoom} from './store';
import {dollars,toMicros,spendingInputSchema,reportSchema,reservationMicros} from './contracts';
type Data=Awaited<ReturnType<typeof loadSpendingRoom>>;
export function SpendingRoom({initial}:{initial:Data}){
 const [data,setData]=useState(initial.spending),[selected,setSelected]=useState(initial.models.profiles[0]?.id??''),[reason,setReason]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[needsRefresh,setNeedsRefresh]=useState(false);const lock=useRef(false);
 const profile=initial.models.profiles.find(p=>p.id===selected),policy=data.policies.find(p=>p.profile_id===selected);
 async function save(value:unknown){if(lock.current)return;const parsed=spendingInputSchema.safeParse(value);if(!parsed.success){setMessage(parsed.error.issues[0]?.message??'Review all fields.');return;}lock.current=true;setBusy(true);setMessage('');try{const r=await fetch('/api/admin/spending',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});const j=await r.json();if(!r.ok)throw new Error(j.error??'Save failed.');setData(reportSchema.parse(j));setReason('');setReviewed(false);setMessage(parsed.data.action==='save'?'Pricing policy saved. No model request was made.':'Charge reconciled. Evidence retained.');}catch(e){setMessage(e instanceof Error?e.message:'Outcome uncertain. Refresh before retrying.');setNeedsRefresh(true);}finally{lock.current=false;setBusy(false);}}
 return <section className="ba-agent-room"><p className="ba-kicker">MODEL SPENDING</p><h1>Spending controls</h1><p>Review USD pricing and limits before authorizing model tests or campaign generation. Reservations and unresolved charges count against the same allowance.</p><p><Link href="/admin/model-tests">Model tests</Link> · <Link href="/admin/models">Model profiles</Link></p><div className="ba-notice">Rates are supplied by you from your provider account. Estimates exclude undeclared fees or pricing changes. Check provider billing for actual charges. Campaign stage accounting is installed, but provider execution stays disabled until its runtime is separately verified and activated. Inherited portfolio AI tools remain outside this ledger.</div>
 <label>Spending profile<select disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setReason('');setReviewed(false);}}>{initial.models.profiles.map(p=><option key={p.id} value={p.id}>{p.document.name}</option>)}</select></label>
 {profile?<><div className="ba-metrics"><div className="ba-metric"><span>Recorded / held today · UTC</span><strong style={{fontSize:24}}>{dollars(policy?.spentTodayMicros??0)}</strong></div><div className="ba-metric"><span>Effective daily limit</span><strong style={{fontSize:24}}>{policy?dollars(Math.min(policy.document.dailyLimitMicros,profile.document.dailyBudgetCents*10000)):'Not configured'}</strong></div><div className="ba-metric"><span>Policy status</span><strong style={{fontSize:20}}>{policy?.blocked?'Reconciliation required':policy&&policy.profile_version===profile.version&&policy.document.enabled&&Date.parse(policy.document.validUntil)>Date.now()?'Configured':'Review required'}</strong></div></div>
 <p>Conservative reservation per connectivity test: <strong>{policy?dollars(reservationMicros(policy.document)):"Set reviewed pricing first"}</strong> (4096 input / 128 output token bound plus fee and 25% margin).</p><PolicyEditor key={`${selected}-${policy?.version??0}`} initial={policy?.document} disabled={busy||needsRefresh} onSave={doc=>void save({action:'save',profileId:selected,profileRevision:profile.revision,expectedVersion:policy?.version??0,document:doc,reason,reviewed})} reason={reason} setReason={setReason} reviewed={reviewed} setReviewed={setReviewed}/></>:<p>Create a model profile first.</p>}
 <button disabled={busy} onClick={()=>window.location.reload()}>Refresh spending and configuration</button><p role="status">{message}</p>
 <h2>Latest 100 reservations and charges</h2><p>Older records remain stored. Pre-032 connectivity tests are not backfilled; their charges must be reviewed in the provider account.</p>{!data.runs.length&&<p>No budgeted requests yet.</p>}{data.runs.map(r=><article key={r.run_id}><h3>{r.state} · {initial.models.profiles.find(p=>p.id===r.profile_id)?.document.name??'Recorded profile'}</h3><p>{r.run_kind==='campaign_stage'?`Campaign ${r.stage_kind} stage`:'Connectivity test'} · held maximum {dollars(r.reserved_micros)} · counted amount {dollars(r.charged_micros)} · pricing v{r.policy_version}</p><p>Input {r.input_tokens??'unknown'} · output {r.output_tokens??'unknown'} · started {r.started_at}</p><p>Run {r.run_id}{r.generation_id?` · generation ${r.generation_id}`:''}</p>{(r.state==='unknown'||r.state==='overrun'||r.state==='reserved'&&Date.parse(r.started_at)<Date.now()-90000)&&<Reconcile runId={r.run_id} state={r.state as 'reserved'|'unknown'|'overrun'} disabled={busy||needsRefresh} onSave={v=>void save(v)}/>}</article>)}
 <h2>Pricing history</h2>{data.policyEvents.map(e=><article key={e.id}><p>Version {e.version} · {e.occurred_at} · {e.reason}</p><p>Actor {e.actor_id??'Deleted account'} · source {e.document.source}</p></article>)}<h2>Charge activity</h2>{data.events.map(e=><article key={e.id}><p>{e.action} · {dollars(e.amount_micros)} · {e.occurred_at}</p><p>{e.reason} · actor {e.actor_id??'Server recorder / deleted account'}</p></article>)}</section>;
}
function PolicyEditor({initial,disabled,onSave,reason,setReason,reviewed,setReviewed}:{initial?:Data['spending']['policies'][number]['document'];disabled:boolean;onSave:(v:unknown)=>void;reason:string;setReason:(s:string)=>void;reviewed:boolean;setReviewed:(v:boolean)=>void}){
 const [input,setInput]=useState(initial?String(initial.inputRateMicros/1e6):''),[output,setOutput]=useState(initial?String(initial.outputRateMicros/1e6):''),[fee,setFee]=useState(initial?String(initial.requestFeeMicros/1e6):'0'),[day,setDay]=useState(initial?String(initial.dailyLimitMicros/1e6):''),[run,setRun]=useState(initial?String(initial.runLimitMicros/1e6):''),[source,setSource]=useState(initial?.source??''),[until,setUntil]=useState(initial?.validUntil??new Date(Date.now()+7*86400000).toISOString()),[enabled,setEnabled]=useState(initial?.enabled??false),[error,setError]=useState('');
 function submit(){try{onSave({enabled,inputRateMicros:toMicros(input),outputRateMicros:toMicros(output),requestFeeMicros:toMicros(fee),dailyLimitMicros:toMicros(day),runLimitMicros:toMicros(run),validUntil:until,source,reviewed:true});}catch(e){setError(e instanceof Error?e.message:'Review amounts.');}}
 return <fieldset disabled={disabled}><h2>Reviewed pricing policy</h2><p>No prices are assumed. Use applicable USD rates, including billable reasoning/output and account-specific fees. Zero rates require verified free-tier/credit evidence. Limits also respect the model profile’s daily budget.</p>{[['Input USD / million tokens',input,setInput],['Output USD / million tokens',output,setOutput],['Additional USD / request',fee,setFee],['Daily limit USD',day,setDay],['Per-run limit USD',run,setRun]].map(([label,value,set])=><label key={label as string}>{label as string}<input inputMode="decimal" value={value as string} onChange={e=>{(set as (v:string)=>void)(e.target.value);setReviewed(false);}}/></label>)}<label>Pricing source HTTPS URL<input value={source} maxLength={300} onChange={e=>{setSource(e.target.value);setReviewed(false);}}/></label><label>Pricing valid until · ISO timestamp<input value={until} onChange={e=>{setUntil(e.target.value);setReviewed(false);}}/></label><label><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);setReviewed(false);}}/> Enable this pricing policy</label><label>Pricing review reason<textarea value={reason} maxLength={300} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I reviewed the applicable pricing, limits and expiry.</label><button disabled={!reviewed||reason.trim().length<10} onClick={submit}>Save pricing policy</button><p role="alert">{error}</p></fieldset>;
}
function Reconcile({runId,state,disabled,onSave}:{runId:string;state:'reserved'|'unknown'|'overrun';disabled:boolean;onSave:(v:unknown)=>void}){const [amount,setAmount]=useState(''),[reason,setReason]=useState(''),[reviewed,setReviewed]=useState(false),[error,setError]=useState('');return <fieldset disabled={disabled}><h4>Reconcile against provider billing</h4><p>Do not release a held charge based only on a timeout. Record the verified charge and evidence reference; never paste secrets.</p><label>Verified USD charge<input inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setReviewed(false);}}/></label><label>Billing evidence / reconciliation reason<textarea maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I checked the provider billing evidence.</label><button disabled={!reviewed||reason.trim().length<10} onClick={()=>{try{onSave({action:'reconcile',runId,expectedState:state,amountMicros:toMicros(amount),reason,reviewed});}catch(e){setError(e instanceof Error?e.message:'Invalid amount.');}}}>Record verified charge</button><p role="alert">{error}</p></fieldset>;}
