import {describe,it,expect} from 'vitest';
import {starterVisuals,upgradeVisuals} from './visual-contracts';
import {visualSource} from './visuals.fixture';
import {applyPrivateTemplate,archivePrivateTemplate,createPrivateTemplate,privateTemplateRecipeSchema,privateTemplateRecordSchema,recipeFromVisuals,revisePrivateTemplate} from './private-template-contracts';
const id='11111111-1111-4111-8111-111111111111',owner='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333',time='2026-10-09T23:10:00Z';
const document=()=>upgradeVisuals(starterVisuals(visualSource(),'Brand'));
const recipe=()=>recipeFromVisuals(document(),'My private design');
const record=()=>createPrivateTemplate(id,owner,recipe(),time);
const ref=(version=1)=>({templateId:id,version,renderer:'campaign-scenes-v2'});
describe('private reusable template contract foundation',()=>{
 it('extracts design without importing campaign wording or sharing mutable objects',()=>{const d=document(),r=recipeFromVisuals(d,'  Design  ');expect(r.name).toBe('Design');expect(Object.keys(r).sort()).toEqual(['brand','name','renderer','schema','templates']);r.brand.name='Different';r.templates.pins[0]='headline';expect(d.brand.name).toBe('Brand');expect(d.templates.pins[0]).toBe('classic');});
 it('pins an old immutable version after a later revision and keeps source content intact',()=>{const original=record(),before=JSON.stringify(original),r=recipe();r.brand.accent='#ff0000';const next=revisePrivateTemplate(original,owner,1,r,time),d=document(),source=JSON.stringify(d);const old=applyPrivateTemplate(next,owner,ref(),d),latest=applyPrivateTemplate(next,owner,ref(2),d);expect(old.document.brand.accent).toBe('#5271FF');expect(latest.document.brand.accent).toBe('#ff0000');expect(old.templateReference.version).toBe(1);expect(latest.document.pins).toEqual(d.pins);expect(latest.document.slides).toEqual(d.slides);expect(latest.document.linkedin).toEqual(d.linkedin);latest.document.pins[0].title='Edited';expect(JSON.stringify(d)).toBe(source);expect(JSON.stringify(original)).toBe(before);});
 it('denies other creators for apply, revise and archive regardless of workspace role',()=>{const r=record();for(const run of [()=>applyPrivateTemplate(r,other,ref(),document()),()=>revisePrivateTemplate(r,other,1,recipe(),time),()=>archivePrivateTemplate(r,other,1)])expect(run).toThrow('unavailable');});
 it('rejects stale edits and unsupported pinned versions or renderer identity',()=>{const r=revisePrivateTemplate(record(),owner,1,recipe(),time);expect(()=>revisePrivateTemplate(r,owner,1,recipe(),time)).toThrow('conflict');expect(()=>archivePrivateTemplate(r,owner,1)).toThrow('conflict');expect(()=>applyPrivateTemplate(r,owner,ref(3),document())).toThrow('unavailable');expect(()=>applyPrivateTemplate(r,owner,{...ref(),templateId:other},document())).toThrow('unavailable');expect(()=>applyPrivateTemplate(r,owner,{...ref(),renderer:'arbitrary'},document())).toThrow();});
 it('archives inventory without rewriting versions or already created drafts',()=>{const r=record(),saved=applyPrivateTemplate(r,owner,ref(),document()),before=JSON.stringify(saved),archived=archivePrivateTemplate(r,owner,1);expect(archived.versions).toEqual(r.versions);expect(r.archived).toBe(false);expect(()=>applyPrivateTemplate(archived,owner,ref(),document())).toThrow('unavailable');expect(()=>revisePrivateTemplate(archived,owner,1,recipe(),time)).toThrow('unavailable');expect(JSON.stringify(saved)).toBe(before);});
 it('rejects executable fields, unknown templates, foreign identity and noncontiguous history',()=>{expect(privateTemplateRecipeSchema.safeParse({...recipe(),script:'evil'}).success).toBe(false);expect(privateTemplateRecipeSchema.safeParse({...recipe(),templates:{...recipe().templates,carousel:'remote-svg'}}).success).toBe(false);const r=record();expect(privateTemplateRecordSchema.safeParse({...r,versions:[{...r.versions[0],creatorId:other}]}).success).toBe(false);expect(privateTemplateRecordSchema.safeParse({...r,versions:[{...r.versions[0],version:2}]}).success).toBe(false);});
 it('blocks overflow and enforces bounded revision history',()=>{const d=document();d.linkedin.body='W'.repeat(420);expect(()=>applyPrivateTemplate(record(),owner,ref(),d)).toThrow('overflow');let r=record();for(let i=1;i<50;i++)r=revisePrivateTemplate(r,owner,i,recipe(),time);expect(()=>revisePrivateTemplate(r,owner,50,recipe(),time)).toThrow('limit');});
});
