'use client';
import React,{useRef,useState} from 'react';
import {privateTemplateInventorySchema,privateTemplateRecordSchema,recipeFromVisuals,type PrivateTemplateRecord} from './private-template-contracts';
import {upgradeVisuals,type VisualDocument} from './visual-contracts';
import {visualProblems} from './visual-layout';

export function PrivateTemplatePanel({endpoint,document,disabled,onChoose}:{endpoint:string;document:VisualDocument;disabled:boolean;onChoose:(document:VisualDocument)=>void}){
 const [items,setItems]=useState<ReturnType<typeof privateTemplateInventorySchema.parse>>([]),[selected,setSelected]=useState<PrivateTemplateRecord|null>(null),[version,setVersion]=useState(1),[name,setName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[confirmArchive,setConfirmArchive]=useState(false);const lock=useRef(false);
 async function request(url:string,body?:unknown){const response=await fetch(url,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error??'Private template request failed.');return value;}
 async function action(run:()=>Promise<void>){if(lock.current||disabled)return;lock.current=true;setBusy(true);setMessage('');try{await run();}catch(error){setMessage(error instanceof Error?error.message:'Private templates are unavailable.');}finally{lock.current=false;setBusy(false);}}
 async function refresh(){const inventory=privateTemplateInventorySchema.parse(await request(`${endpoint}?archived=1`));setItems(inventory);setLoaded(true);setSelected(null);setConfirmArchive(false);}
 async function open(id:string){const record=privateTemplateRecordSchema.parse(await request(`${endpoint}/${id}`));setSelected(record);setVersion(record.versions.length);setName(record.versions.at(-1)!.recipe.name);setConfirmArchive(false);}
 async function save(create:boolean){const recipe=recipeFromVisuals(document,name);const templateId=create?crypto.randomUUID():selected!.templateId;const expectedVersion=create?0:selected!.versions.length;const record=privateTemplateRecordSchema.parse(await request(endpoint,{templateId,expectedVersion,recipe}));await refresh();setSelected(record);setVersion(record.versions.length);setMessage(`Private template v${record.versions.length} saved. Campaign text was not stored in the template.`);}
 function choose(){if(!selected||selected.archived)return;const revision=selected.versions[version-1],base=upgradeVisuals(document);const next:VisualDocument={...base,schema:'campaign-visuals-v3',brand:revision.recipe.brand,templates:revision.recipe.templates,templateReference:{templateId:selected.templateId,version,renderer:'campaign-scenes-v2'},templateRecipe:revision.recipe};const problems=visualProblems(next);if(problems.length){setMessage(problems[0]);return;}onChoose(next);setMessage(`Template v${version} previewed. Review the visual and use Save visual drafts to apply it.`);}
 return <details><summary>My private reusable templates</summary><p>Only you can see this inventory. Save the current brand and layout choices for reuse; campaign wording stays outside the template. Archived templates retain history and count toward the 32-template limit.</p><fieldset disabled={disabled||busy} style={{border:0,padding:0}}>
 <button type="button" onClick={()=>void action(refresh)}>Load or refresh my templates</button>{loaded&&<><label style={{display:'block'}}>Private template<select value={selected?.templateId??''} onChange={e=>{if(e.target.value)void action(()=>open(e.target.value));else setSelected(null);}}><option value="">New template</option>{items.map(item=><option key={item.templateId} value={item.templateId}>{item.name} · v{item.version}{item.archived?' · Archived':''}</option>)}</select></label><label style={{display:'block'}}>Template name<input maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button type="button" disabled={!name.trim()||items.length>=32} onClick={()=>void action(()=>save(true))}>Save current design as new private template</button>
 {selected&&<><p>{selected.archived?'Archived — unavailable for new application':'Active'} · Latest v{selected.versions.length}</p><label>Template version<select value={version} onChange={e=>setVersion(Number(e.target.value))}>{selected.versions.map(revision=><option key={revision.version} value={revision.version}>v{revision.version} · {revision.recipe.name}</option>)}</select></label><button type="button" disabled={selected.archived} onClick={choose}>Preview selected template</button><button type="button" disabled={selected.archived||selected.versions.length>=50||!name.trim()} onClick={()=>void action(()=>save(false))}>Save current design as next template version</button>{!selected.archived&&<><label style={{display:'block'}}><input type="checkbox" checked={confirmArchive} onChange={e=>setConfirmArchive(e.target.checked)}/> Archive this template; keep its history and saved visuals.</label><button type="button" disabled={!confirmArchive} onClick={()=>void action(async()=>{await request(`${endpoint}/${selected.templateId}`,{expectedVersion:selected.versions.length});await refresh();setMessage('Template archived. Saved campaign visuals remain available.');})}>Archive private template</button></>}</>}
 </>}</fieldset><p role="status">{busy?'Working…':message}</p></details>;
}
