import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { SupabaseClient } from '@supabase/supabase-js';
vi.mock('../workspaces/store', async original => ({ ...await original<typeof import('../workspaces/store')>(), getSite: vi.fn() }));
import { getSite } from '../workspaces/store';
import { archiveStoredPrivateMedia, listPrivateMedia, loadPrivateMedia, reviewStoredPrivateMedia } from './private-media-store';
const actor = '11111111-1111-4111-8111-111111111111', wid = '22222222-2222-4222-8222-222222222222', sid = '33333333-3333-4333-8333-333333333333', mediaId = '44444444-4444-4444-8444-444444444444';
const descriptor = { schema: 'private-media-descriptor-v1', mime: 'image/png', bytes: 1024, width: 1000, height: 1500, sha256: 'a'.repeat(64), alt: 'Blue abstract background', origin: 'user-upload', rights: { basis: 'own-work', evidence: 'Created by me for private draft use.', attested: true } };
const record = { schema: 'private-media-record-v1', mediaId, creatorId: actor, workspaceId: wid, siteId: sid, revision: 1, archived: false, versions: [{ version: 1, descriptor, createdAt: '2026-10-10T15:20:00.000000Z', review: null }] };
beforeEach(() => vi.mocked(getSite).mockResolvedValue({ workspace: { role: 'owner' }, site: { id: sid } } as never));
function fixture(data: unknown = null, error: unknown = null) { const rpc = vi.fn(async () => ({ data, error })); return { rpc, db: { rpc } as unknown as SupabaseClient }; }
describe('private media server storage', () => {
  it('checks current membership and parses creator inventory', async () => { const summary = { mediaId, revision: 1, version: 1, archived: false, descriptor, reviewDecision: null }, f = fixture([summary]); expect(await listPrivateMedia(f.db, actor, wid, sid)).toEqual([summary]); expect(getSite).toHaveBeenCalledWith(f.db, actor, wid, sid); expect(f.rpc).toHaveBeenCalledWith('bz_private_media_inventory', { p_workspace_id: wid, p_site_id: sid, p_include_archived: false }); });
  it('keeps a missing or foreign item unavailable', async () => { await expect(loadPrivateMedia(fixture(null).db, actor, wid, sid, mediaId)).rejects.toMatchObject({ status: 404 }); await expect(loadPrivateMedia(fixture(null, { message: 'bz_media_unavailable' }).db, actor, wid, sid, mediaId)).rejects.toMatchObject({ status: 404 }); });
  it('pins review and archive revisions in checked RPCs', async () => { const reviewed = { ...record, revision: 2, versions: [{ ...record.versions[0], review: { decision: 'accepted', actorId: actor, reason: 'Reviewed image and rights for private draft use.', reviewedAt: '2026-10-10T15:21:00.000000Z' } }] }, review = fixture(reviewed); await reviewStoredPrivateMedia(review.db, actor, wid, sid, mediaId, { expectedRevision: 1, version: 1, decision: 'accepted', reason: 'Reviewed image and rights for private draft use.' }); expect(review.rpc).toHaveBeenCalledWith('bz_review_private_media', expect.objectContaining({ p_expected_revision: 1, p_version: 1, p_decision: 'accepted' })); const archived = fixture({ ...reviewed, revision: 3, archived: true }); await archiveStoredPrivateMedia(archived.db, actor, wid, sid, mediaId, { expectedRevision: 2 }); expect(archived.rpc).toHaveBeenCalledWith('bz_archive_private_media', expect.objectContaining({ p_expected_revision: 2 })); });
  it('requires owner role for mutations before calling an RPC', async () => { vi.mocked(getSite).mockResolvedValue({ workspace: { role: 'editor' }, site: { id: sid } } as never); const f = fixture(record); await expect(reviewStoredPrivateMedia(f.db, actor, wid, sid, mediaId, { expectedRevision: 1, version: 1, decision: 'accepted', reason: 'Reviewed.' })).rejects.toMatchObject({ status: 403 }); await expect(archiveStoredPrivateMedia(f.db, actor, wid, sid, mediaId, { expectedRevision: 1 })).rejects.toMatchObject({ status: 403 }); expect(f.rpc).not.toHaveBeenCalled(); });
  it('keeps setup, conflict, quota and validation failures actionable', async () => { await expect(listPrivateMedia(fixture(null, { code: 'PGRST202' }).db, actor, wid, sid)).rejects.toMatchObject({ status: 503 }); await expect(archiveStoredPrivateMedia(fixture(null, { message: 'bz_conflict' }).db, actor, wid, sid, mediaId, { expectedRevision: 1 })).rejects.toMatchObject({ status: 409 }); await expect(loadPrivateMedia(fixture(null, { message: 'bz_media_limit' }).db, actor, wid, sid, mediaId)).rejects.toMatchObject({ status: 409 }); });
});
