"use client";
import Link from "next/link";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {campaignDocumentSchema,starterCampaign,type CampaignDocument,type CampaignRecord,type GenerationSummary} from "./contracts";
import {campaignDownload,downloadDraft} from "./export";
import {GeneratedDrafts} from "./outputs";
import type {OutputRecord} from "./output-contracts";
export function CampaignRoom({records,history,generations,outputs=[],outputSetupRequired=false,canReview=false,endpoint,base,canWrite,selectedId}:{outputs?:OutputRecord[];outputSetupRequired?:boolean;canReview?:boolean;records:CampaignRecord[];history:{campaign_id:string;version:number;document:CampaignDocument;occurred_at:string}[];generations:GenerationSummary[];endpoint:string;base:string;canWrite:boolean;selectedId?:string}){
 const router=useRouter();const selected=records.find(r=>r.id===selectedId);
 const [document,setDocument]=useState<CampaignDocument>(selected?.document??{title:"",brief:"",blog:"",pinterest:"",linkedin:""});
 const [id,setId]=useState(selected?.id??"");const [version,setVersion]=useState(selected?.version??0);
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [dirty,setDirty]=useState(false);
 function exportDraft(){try{downloadDraft(campaignDownload(document,id,version,dirty));setMessage("Private working copy downloaded. It includes the displayed text; no save, generation or publishing occurred.");}catch{setMessage("Download unavailable. Your draft is unchanged; copy the displayed text manually.");}}
 function change(key:keyof CampaignDocument,value:string){setDocument(d=>({...d,[key]:value}));setDirty(true);setMessage("");}
 async function save(){const parsed=campaignDocumentSchema.safeParse(document);if(!parsed.success){setMessage(parsed.error.issues[0]?.message??"Check your brief.");return;}setBusy(true);setMessage("");
 try{const requestId=id||crypto.randomUUID();setId(requestId);const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:requestId,expectedVersion:version,document:parsed.data})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Save failed.");setVersion(data.version);setDirty(false);setMessage(`Saved private draft version ${data.version}. No AI request or publishing occurred.`);router.replace(`${base}/${data.id}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Save failed. Keep your text and retry.");}finally{setBusy(false);}}
 async function prepare(){if(!id||version<1||dirty){setMessage("Save the current campaign before preparing a generation snapshot.");return;}setBusy(true);setMessage("");try{const response=await fetch(`${endpoint}/generations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:crypto.randomUUID(),campaignId:id,expectedCampaignVersion:version})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Preparation failed.");setMessage("Prepared an immutable generation snapshot. No model request, charge or publishing occurred.");router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Preparation failed.");}finally{setBusy(false);}}
 return <div className="bz-detail-layout"><section className="bz-panel"><h2>Private campaigns</h2><p>One brief, three draft formats. Generated text appears here after an explicitly authorized founder pilot.</p><Link className="bz-button" href={base} onClick={e=>{if(dirty&&!confirm("Leave unsaved changes?")){e.preventDefault();return;}if(!selectedId){setDocument({title:"",brief:"",blog:"",pinterest:"",linkedin:""});setId("");setVersion(0);setDirty(false);setMessage("");}}}>New campaign</Link>{records.length===0?<p>No saved campaigns yet.</p>:<ul>{records.map(r=><li key={r.id}><Link href={`${base}/${r.id}`} onClick={e=>{if(dirty&&!confirm("Leave unsaved changes?"))e.preventDefault();}}>{r.document.title}</Link><p>Version {r.version} · {new Date(r.updated_at).toLocaleString()}</p></li>)}</ul>}</section>
 <section className="bz-panel bz-form-panel"><h2>{selected?"Edit campaign":"Prepare a campaign"}</h2><p>Private working drafts · version {version} · {dirty?"Unsaved changes":"No unsaved changes"}</p>
 <button type="button" className="bz-button" disabled={busy} onClick={exportDraft}>Download working copy (JSON)</button><p><small>The file labels unsaved edits and contains private content. Share it only with people you authorize.</small></p>
 <form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={!canWrite||busy} style={{border:0,padding:0,minWidth:0}}>
 <button type="button" className="bz-button" onClick={()=>{if(!dirty||confirm("Replace current text with a starter brief?")){setDocument({...starterCampaign});setDirty(true);}}}>Use starter brief</button>
 {([["title","Campaign title",120,2],["brief","Shared brief",4000,6],["blog","Blog draft",24000,12],["pinterest","Pinterest title and description",2000,6],["linkedin","LinkedIn post",5000,8]] as const).map(([key,label,max,rows])=><label key={key} style={{display:"block",marginTop:18}}>{label}<textarea value={document[key]} maxLength={max} rows={rows} required={key==="title"||key==="brief"} onChange={e=>change(key,e.target.value)} style={{display:"block",width:"100%",resize:"vertical"}}/><small>{document[key].length}/{max}</small></label>)}
 <button className="bz-button" type="submit" disabled={!dirty||busy}>{busy?"Saving…":"Save private drafts"}</button></fieldset></form>
 {selected&&<div style={{marginTop:18}}><button className="bz-button" type="button" disabled={!canWrite||busy||dirty} onClick={()=>void prepare()}>Prepare generation snapshot</button><p><small>This freezes the approved knowledge, campaign, preferences, agent/model bindings and reviewed pricing for a future run. Durable stage accounting is installed, but this button still does not contact a model or reserve spend.</small></p></div>}
 {!canWrite&&<p>Your role is read-only.</p>}<p role="status">{message}</p>{selectedId&&<><details><summary>Saved revision history (latest 100 site revisions)</summary>{history.filter(h=>h.campaign_id===selectedId).map(h=><details key={h.version}><summary>Version {h.version} · {new Date(h.occurred_at).toLocaleString()}</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify(h.document,null,2)}</pre></details>)}</details><details><summary>Generation snapshots ({generations.filter(g=>g.campaignId===selectedId).length})</summary>{generations.filter(g=>g.campaignId===selectedId).map(g=><article key={g.id}><p><strong>{g.status}</strong> · campaign v{g.campaignVersion} · {g.stageCount} planned stages · {new Date(g.createdAt).toLocaleString()}</p>{g.stages.length>0&&<ul>{g.stages.map(s=><li key={s.id}>{s.kind}: {s.status} · spending {s.spendingState}</li>)}</ul>}</article>)}</details></>}{outputSetupRequired&&<p role="status">Generated output review needs migration037. Your existing campaign drafts remain available.</p>}<GeneratedDrafts key={outputs.map(o=>`${o.id}:${o.reviews[0]?.version??0}`).join(",")} records={outputs.filter(o=>o.campaignId===selectedId)} endpoint={`${endpoint}/reviews`} canReview={canReview}/><p>Generated outputs remain separate from your editable drafts. Human acceptance does not publish. Publishing and visual composition are unavailable.</p></section></div>;
}
