import {describe,it,expect} from 'vitest';
import {starterVisuals,upgradeVisuals,visualDocumentSchema,visualTemplates} from './visual-contracts';
import {visualScene,sceneSvg,visualProblems} from './visual-layout';
import {visualSource} from './visuals.fixture';
describe('shared templates and standalone LinkedIn image',()=>{
 it('upgrades an editable copy without modifying saved source',()=>{const source=visualSource(),old=starterVisuals(source,'Brand'),before=JSON.stringify(old),s=JSON.stringify(source),next=upgradeVisuals(old);expect(next.templates.pins).toEqual(['classic','midnight']);expect(next.linkedin).toEqual(old.slides[0]);expect(JSON.stringify(old)).toBe(before);expect(JSON.stringify(source)).toBe(s);expect(visualDocumentSchema.safeParse(old).success).toBe(true);expect(visualDocumentSchema.safeParse(next).success).toBe(true);});
 it('retains exact legacy scenes for default classic/midnight conversion',()=>{const old=starterVisuals(visualSource(),'Brand'),next=upgradeVisuals(old);for(const index of [0,1] as const)expect(visualScene(next,{kind:'pin',index})).toEqual(visualScene(old,{kind:'pin',index}));expect(visualScene(next,{kind:'slide',index:2})).toEqual(visualScene(old,{kind:'slide',index:2}));});
 it('renders four distinct safe designs for each format while preserving words',()=>{const d=upgradeVisuals(starterVisuals(visualSource(),'Brand'));for(const target of [{kind:'pin',index:0},{kind:'slide',index:0},{kind:'linkedin',index:0}] as const){const svgs=new Set<string>();for(const t of visualTemplates){d.templates={pins:[t.id,t.id],carousel:t.id,linkedin:t.id};const scene=visualScene(d,target);expect(scene.blocks.find(b=>b.id==='body')?.text).toBe(target.kind==='linkedin'?d.linkedin.body:target.kind==='pin'?d.pins[0].body:d.slides[0].body);expect(scene.blocks.every(b=>!b.overflow)).toBe(true);const svg=sceneSvg(scene);expect(svg).not.toMatch(/href=|foreignObject|<script/);svgs.add(svg);}expect(svgs.size).toBe(4);}});
 it('rejects unknown templates, executable fields and mixed versions',()=>{const d=upgradeVisuals(starterVisuals(visualSource(),'Brand'));expect(visualDocumentSchema.safeParse({...d,templates:{...d.templates,carousel:'custom-code'}}).success).toBe(false);expect(visualDocumentSchema.safeParse({...d,templates:{...d.templates,script:'evil'}}).success).toBe(false);expect(visualDocumentSchema.safeParse({...d,linkedin:{title:'',body:'text'}}).success).toBe(false);expect(visualDocumentSchema.safeParse({...d,schema:'campaign-visuals-v1'}).success).toBe(false);});
 it('checks standalone overflow and square dimensions',()=>{const d=upgradeVisuals(starterVisuals(visualSource(),'Brand'));expect(visualProblems(d)).toEqual([]);expect(visualScene(d,{kind:'linkedin',index:0})).toMatchObject({width:1080,height:1080});d.linkedin.body='W'.repeat(420);expect(visualProblems(d)).toContain('LinkedIn post image: shorten or complete body text so it fits.');expect(()=>sceneSvg(visualScene(d,{kind:'linkedin',index:0}))).toThrow();expect(()=>visualScene(starterVisuals(visualSource(),'Brand'),{kind:'linkedin',index:0})).toThrow('Add the LinkedIn image');});
});
