"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {BookOpen,CheckCircle2,Download,FileText,History,Plus,Search,ShieldCheck,Trash2,Upload} from "lucide-react";
import {approvedKnowledgeSchema,extractKnowledgeCandidates,knowledgeDocumentSchema,knowledgeMatches,knowledgeSourceSchema,readKnowledgeFile,type ApprovedKnowledge,type KnowledgeDocument,type KnowledgeMutation,type KnowledgeSource} from "@/domain/knowledge";
import type {WorkspaceRole} from "@/domain/workspaces";
import "./knowledge.css";
const blank=():KnowledgeDocument=>({title:"",filename:"",sourceText:"",facts:[]});
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=window.document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
async function jsonRequest(url:string,input?:KnowledgeMutation){const response=await fetch(url,input?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input),cache:"no-store"}:{cache:"no-store"});const data=await response.json();if(!response.ok)throw Error(data.error??"Knowledge request failed. Please retry.");return data;}
export function KnowledgeRoom({initialSources,endpoint,role,siteId}:{initialSources:KnowledgeSource[];endpoint:string;role:WorkspaceRole;siteId:string}){
 const [sources,setSources]=useState(initialSources);const [selected,setSelected]=useState<string|null>(null);const [draft,setDraft]=useState<KnowledgeDocument>(blank);const [saved,setSaved]=useState(JSON.stringify(blank()));
 const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [confirmed,setConfirmed]=useState(false);
 const [approved,setApproved]=useState<ApprovedKnowledge[]>([]);const [query,setQuery]=useState("");const [retrievalError,setRetrievalError]=useState("");const [history,setHistory]=useState<Array<{version:number;document:KnowledgeDocument;approved:boolean;occurred_at:string;action:string}>>([]);
 const writable=role!=="viewer",owner=role==="owner";const current=sources.find(s=>s.id===selected);const dirty=JSON.stringify(draft)!==saved;
 useEffect(()=>{let active=true;setApproved([]);setRetrievalError("");jsonRequest(endpoint+"/approved").then(data=>{if(active)setApproved(data.sources.map((v:unknown)=>approvedKnowledgeSchema.parse(v)));}).catch(()=>{if(active){setApproved([]);setRetrievalError("Approved facts could not be loaded. Retrieval is unavailable until you retry or reload.");}});return()=>{active=false;};},[endpoint,sources]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};const signout=(e:Event)=>{if(!window.confirm("Discard unsaved knowledge changes and sign out?"))e.preventDefault();};const guard=(e:MouseEvent)=>{const link=(e.target as Element).closest?.("a[href]") as HTMLAnchorElement|null;if(!link||link.target==="_blank"||link.hasAttribute("download")||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const next=new URL(link.href,location.href);if(next.href!==location.href&&!window.confirm("Discard unsaved knowledge changes and leave?")){e.preventDefault();e.stopPropagation();}};window.addEventListener("beforeunload",warn);window.addEventListener("bizoveya:before-signout",signout);window.document.addEventListener("click",guard,true);return()=>{window.removeEventListener("beforeunload",warn);window.removeEventListener("bizoveya:before-signout",signout);window.document.removeEventListener("click",guard,true);};},[dirty]);
 function edit(next:KnowledgeDocument){setDraft(next);setConfirmed(false);setMessage("");setError("");}
 function open(source?:KnowledgeSource){if(dirty&&!window.confirm("Discard unsaved knowledge changes?"))return;setSelected(source?.id??null);const value=source?.document??blank();setDraft(value);setSaved(JSON.stringify(value));setHistory([]);setConfirmed(false);setMessage("");setError("");}
 async function mutate(input:KnowledgeMutation){if(lock.current)return;lock.current=true;setBusy(true);setError("");setMessage("");try{const data=await jsonRequest(endpoint,input);if(input.action==="delete"){setSources(prev=>prev.filter(s=>s.id!==input.id));setSelected(null);setDraft(blank());setSaved(JSON.stringify(blank()));setMessage("Source and its stored revisions removed. A content-free removal event remains.");}else{const source=knowledgeSourceSchema.parse(data.source);setSources(prev=>[source,...prev.filter(s=>s.id!==source.id)]);setSelected(source.id);setDraft(source.document);setSaved(JSON.stringify(source.document));setMessage(input.action==="approve"?"Reviewed facts approved for this site.":input.action==="revoke"?"Approval revoked. Facts are excluded from approved retrieval.":"Source saved as a private draft. Owner review is required before use.");}setHistory([]);setConfirmed(false);}catch(cause){setError(cause instanceof Error?cause.message:"Could not save knowledge.");}finally{lock.current=false;setBusy(false);}}
 function save(e:FormEvent){e.preventDefault();const parsed=knowledgeDocumentSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues[0]?.message??"Review the source details.");return;}void mutate({action:"save",id:selected??crypto.randomUUID(),expectedVersion:current?.version??0,document:parsed.data});}
 async function importFile(file:File){if(lock.current)return;if(draft.sourceText.trim()&&!window.confirm("Replace staged source text and facts with this file?"))return;lock.current=true;setBusy(true);setError("");try{if(file.size>48000)throw Error("Use a text file no larger than 48,000 bytes.");const value=readKnowledgeFile(file.name,new Uint8Array(await file.arrayBuffer()));edit({...value,facts:[]});setMessage("File staged locally. Generate candidates, review them, then save. Nothing has been uploaded yet.");}catch(cause){setError(cause instanceof Error?cause.message:"File import failed.");}finally{lock.current=false;setBusy(false);}}
 async function revisions(){if(!current||lock.current)return;lock.current=true;setBusy(true);setError("");try{const data=await jsonRequest(endpoint+"/"+current.id+"/history");setHistory(data.revisions);}catch(cause){setError(cause instanceof Error?cause.message:"History unavailable.");}finally{lock.current=false;setBusy(false);}}
 const matches=approved.flatMap(s=>knowledgeMatches(s,query));
 return <div className="knowledge-room"><section className="knowledge-metrics" aria-label="Knowledge overview"><article><FileText/><strong>{sources.length}/20</strong><span>Site sources</span></article><article><ShieldCheck/><strong>{sources.filter(s=>s.approved).length}</strong><span>Owner-approved sources</span></article><article><BookOpen/><strong>{approved.reduce((n,s)=>n+s.facts.length,0)}</strong><span>Approved facts</span></article></section>
 <div className="bz-callout"><ShieldCheck size={24}/><p>Private to this site’s workspace. Candidate extraction is deterministic and does not verify truth. Review every fact before approval. No API key, automatic website updates, public chatbot, embeddings or agent runs are used here. Import UTF-8 .txt/.md; PDF/DOCX/OCR remain planned.</p></div>
 {error&&<p role="alert" className="bz-alert">{error}</p>}{message&&<p role="status" className="knowledge-message">{message}</p>}
 <div className="knowledge-grid"><aside className="bz-panel knowledge-library"><h2>Source library</h2>{writable&&<button className="bz-button" disabled={busy||sources.length>=20} onClick={()=>open()}><Plus size={17}/>New source</button>}{sources.length===0&&<p>No sources yet. Add information you are authorized to store.</p>}<ul>{sources.map(s=><li key={s.id}><button disabled={busy} aria-pressed={selected===s.id} onClick={()=>open(s)}><FileText size={17}/><span><strong>{s.document.title}</strong><small>{s.approved?"Approved":"Draft"} · revision {s.version}</small></span></button></li>)}</ul><button className="bz-button" disabled={busy||!sources.length} onClick={()=>download(`bizoveya-${siteId}-knowledge.json`,{schemaVersion:1,siteId,exportedAt:new Date().toISOString(),sources})}><Download size={17}/>Export saved knowledge</button><p className="knowledge-help">Export includes private source text and reviewed facts. Store it securely. Unsaved changes and past revisions are excluded; export history separately.</p></aside>
 <section className="bz-panel knowledge-editor"><h2>{current?current.document.title:"Prepare a source"}</h2>{current&&<p className="knowledge-help">{current.approved?"Approved":"Draft"} · revision {current.version} · {current.approved_at?`Approved ${new Date(current.approved_at).toLocaleString()}`:"Owner approval pending"}</p>}{(!writable&&!current)?<p>Select a saved source to read it.</p>:<form onSubmit={save}><fieldset disabled={busy||!writable}><label>Source title<input value={draft.title} maxLength={120} onChange={e=>edit({...draft,title:e.target.value})} required/></label><label>Original filename<input value={draft.filename} maxLength={120} onChange={e=>edit({...draft,filename:e.target.value})} placeholder="Optional for pasted text"/></label>{writable&&<label className="knowledge-upload"><Upload size={18}/>Import text file<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value="";}}/></label>}<label>Source text<textarea aria-label="Source text" value={draft.sourceText} maxLength={16000} rows={9} onChange={e=>edit({...draft,sourceText:e.target.value,facts:[]})} required/></label><p className="knowledge-help">{draft.sourceText.length}/16,000 characters. Changing source text clears staged facts. Any saved change removes the previous approval.</p>
 {writable&&<button type="button" className="bz-button" disabled={!draft.sourceText.trim()} onClick={()=>{if(draft.facts.length&&!window.confirm("Replace the staged fact list with new candidates?"))return;const result=extractKnowledgeCandidates(draft.sourceText);edit({...draft,facts:result.facts});setMessage(`${result.facts.length} candidates prepared for review.${result.omitted?` ${result.omitted} additional chunks were omitted; split the source to review them.`:""}`);}}>Generate fact candidates</button>}
 <h3>Review facts ({draft.facts.length}/40)</h3>{!draft.facts.length&&<p>No reviewed facts yet. Generate candidates or add a fact.</p>}{draft.facts.map((fact,i)=><div className="knowledge-fact-edit" key={fact.id}><label>Fact {i+1}<textarea aria-label={`Fact ${i+1}`} value={fact.text} rows={3} maxLength={500} onChange={e=>edit({...draft,facts:draft.facts.map(f=>f.id===fact.id?{...f,text:e.target.value}:f)})}/></label>{writable&&<button className="bz-button" type="button" aria-label={`Remove fact ${i+1}`} onClick={()=>edit({...draft,facts:draft.facts.filter(f=>f.id!==fact.id)})}><Trash2 size={16}/></button>}</div>)}{writable&&<button type="button" className="bz-button" disabled={draft.facts.length>=40} onClick={()=>edit({...draft,facts:[...draft.facts,{id:crypto.randomUUID(),text:""}]})}><Plus size={16}/>Add fact</button>}
 {writable&&<button type="submit" className="bz-button knowledge-primary" disabled={!dirty}><CheckCircle2 size={17}/>Save knowledge draft</button>}</fieldset></form>}
 {owner&&current&&<div className="knowledge-approval"><h3>Owner controls</h3>{!current.approved&&<label><input type="checkbox" checked={confirmed} disabled={busy||dirty} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed these facts, am authorized to store this material, and approve this saved revision for future site-specific use.</label>}<div className="knowledge-actions">{!current.approved?<button className="bz-button knowledge-primary" disabled={busy||dirty||!confirmed||!current.document.facts.length} onClick={()=>void mutate({action:"approve",id:current.id,expectedVersion:current.version})}>Approve reviewed facts</button>:<button className="bz-button" disabled={busy||dirty} onClick={()=>void mutate({action:"revoke",id:current.id,expectedVersion:current.version})}>Revoke approval</button>}<button className="bz-button" disabled={busy||dirty} onClick={()=>{if(window.confirm("Remove this source and every stored revision? This cannot be undone. A content-free removal record remains; provider backups and earlier downloads are outside this action."))void mutate({action:"delete",id:current.id,expectedVersion:current.version});}}><Trash2 size={16}/>Remove source and revisions</button></div></div>}
 {current&&<div className="knowledge-history"><button className="bz-button" disabled={busy} onClick={()=>void revisions()}><History size={17}/>Load revision history</button>{history.length>0&&<><button className="bz-button" disabled={busy} onClick={()=>download(`bizoveya-${current.id}-revisions.json`,{siteId,sourceId:current.id,revisions:history})}>Export revision history</button><ol>{history.map(h=><li key={h.version}><strong>Revision {h.version} · {h.action} · {h.approved?"approved":"draft"}</strong><small>{new Date(h.occurred_at).toLocaleString()}</small><details><summary>Read revision</summary><pre>{JSON.stringify(h.document,null,2)}</pre></details>{writable&&<button className="bz-button" disabled={busy} onClick={()=>{if(dirty&&!window.confirm("Replace unsaved changes with this revision?"))return;edit(h.document);}}>Stage this revision as draft</button>}</li>)}</ol></>}</div>}
 </section></div><section className="bz-panel knowledge-retrieval"><h2><Search size={22}/>Approved fact lookup</h2><p>This searches this site’s currently approved facts. It is an exact keyword filter, not an AI answer or semantic search. Source ID, revision and fact ID are shown for provenance.</p>{retrievalError&&<p role="alert">{retrievalError}</p>}<label>Search approved facts<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a service, policy or business detail"/></label><p role="status">{matches.length} approved facts found</p><div className="knowledge-results">{matches.map(f=><article key={f.sourceId+f.factId}><p>{f.text}</p><strong>{f.title} · revision {f.sourceVersion}</strong><small>{f.filename||"Pasted source"} · fact {f.factId}</small><code>Source: {f.sourceId}</code></article>)}</div>{!matches.length&&<p>No approved facts match. Unapproved and revoked material is excluded.</p>}</section></div>;
}
