import Link from "next/link";
import { Building2, Globe2, Users, ShieldCheck, ArrowUpRight, LockKeyhole, History } from "lucide-react";
import type { AdminAudit, AdminSummary } from "./store";
export function AdminNotice({ message }: { message: string }) { return <section className="ba-panel"><p className="ba-kicker">ADMINISTRATION UNAVAILABLE</p><h1>Check the platform setup</h1><p>{message}</p><p>Follow the deployment and admin setup runbooks supplied in the project documentation.</p><Link href="/login" className="ba-button">Return to admin login</Link></section>; }
export function AdminOverview({ summary }: { summary: AdminSummary }) {
  return <><section className="ba-hero"><div><p className="ba-kicker">PLATFORM OVERVIEW</p><h1>A clear view of your foundation.</h1><p>Track the registry and review who has platform access.</p></div><span className="ba-verified"><ShieldCheck size={18} /> Admin + MFA verified</span></section>
    <div className="ba-metrics">{[{ label: "Workspaces", value: summary.workspaces, hint: "All saved workspaces", icon: Building2 }, { label: "Registered sites", value: summary.sites, hint: "Includes paused and planning records", icon: Globe2 }, { label: "Workspace members", value: summary.workspaceMembers, hint: "Distinct users with a membership", icon: Users }, { label: "Platform admins", value: summary.admins, hint: "Current operator-issued grants", icon: ShieldCheck }].map(({ label, value, hint, icon: Icon }) => <article className="ba-metric" key={label}><Icon size={22} /><span>{label}</span><strong>{value.toLocaleString("en-US")}</strong><small>{hint}</small></article>)}</div>
    <div className="ba-columns"><section className="ba-panel"><History className="ba-accent" /><h2>Access with a record</h2><p>Review admin grants and revocations with timestamps, subjects and operator reasons.</p><Link className="ba-button" href="/admin/audit">Open access history <ArrowUpRight size={17} /></Link></section><section className="ba-panel"><LockKeyhole className="ba-accent" /><h2>Private work stays private</h2><p>This overview contains aggregate counts. It does not grant access to client documents, site content or transcripts.</p><Link href="/admin/security">Check your authenticator →</Link></section></div>
    <section className="ba-panel"><p className="ba-kicker">COMING IN LATER PHASES</p><h2>Your control room will grow here.</h2><div className="ba-roadmap">{["Agent rules & evaluations", "Model profiles & API keys", "Template administration", "Runs, usage & support"].map(label => <div key={label}><span>{label}</span><small>Planned</small></div>)}</div><p className="ba-muted">These controls are not active. Counts above are current database records, not online users, revenue or running agents.</p></section></>;
}
export function AuditTimeline({ events }: { events: AdminAudit }) {
  return <><div className="ba-hero"><div><p className="ba-kicker">ACCESS HISTORY</p><h1>Every access change has a trail.</h1><p>Latest 100 platform-admin grants and revocations, newest first. Timestamps are UTC.</p></div><span className="ba-verified">{events.length} records shown</span></div><section className="ba-panel"><p className="ba-muted">Operator labels and reasons are supplied by the database operator. Database actor identifies the connection account. Sign-in/MFA events remain in Supabase Auth logs.</p>{events.length ? <ol className="ba-timeline">{events.map(event => <li key={event.id}><div className={`ba-event-dot ${event.action}`} /><div><div className="ba-event-heading"><h2>{event.action === "admin_granted" ? "Admin access granted" : "Admin access revoked"}</h2><time dateTime={event.occurred_at}>{new Date(event.occurred_at).toISOString().replace("T", " ").replace("Z", " UTC")}</time></div><p>{event.reason}</p><dl><dt>Subject</dt><dd>{event.subject_id}</dd><dt>Operator</dt><dd>{event.operator_label}</dd><dt>Database actor</dt><dd>{event.database_actor}</dd><dt>Event</dt><dd>{event.id}</dd></dl></div></li>)}</ol> : <div className="ba-empty"><History size={30} /><h2>No access changes recorded</h2><p>Only actual events are shown here.</p></div>}</section></>;
}
