import { DeleteSite } from "@/features/workspaces/delete-site";
import Link from "next/link";
import { ArrowUpRight, ShieldCheck } from "lucide-react";
import { canWriteWorkspace, siteCapabilityLabel } from "@/domain/workspaces";
import { loadWorkspacePage } from "@/features/workspaces/page-data";
import { getSite } from "@/features/workspaces/store";
import { WorkspaceFrame } from "@/features/workspaces/frame";
import { SetupNotice, WorkspaceHeading } from "@/features/workspaces/views";
import { SiteEditForm } from "@/features/workspaces/forms";
export const dynamic = "force-dynamic";
export default async function SitePage({ params }: { params: Promise<{ workspaceId: string; siteId: string }> }) {
  const { workspaceId, siteId } = await params; const state = await loadWorkspacePage(`/workspaces/${workspaceId}/sites/${siteId}`, (db, userId) => getSite(db, userId, workspaceId, siteId));
  if (!state.ready) return <WorkspaceFrame><SetupNotice message={state.message} /></WorkspaceFrame>;
  const { workspace, site, canOpenStudio } = state.value;
  return <WorkspaceFrame email={state.email} workspace={workspace}><WorkspaceHeading eyebrow={`${site.kind.toUpperCase()} WEBSITE · ${site.status.toUpperCase()}`} title={site.name} description={siteCapabilityLabel(site)} action={site.mode === "native_business" ? <Link className="bz-button" href={`/workspaces/${workspaceId}/sites/${siteId}/editor`}>{canWriteWorkspace(workspace.role) ? "Open business editor" : "View business draft"}<ArrowUpRight size={17} aria-hidden="true" /></Link> : canOpenStudio && site.project_id && <Link className="bz-button" href={`/studio/${site.project_id}`}>Open existing Studio<ArrowUpRight size={17} aria-hidden="true" /></Link>} /><div className="bz-detail-layout"><section className="bz-panel bz-details"><h2>Site record</h2><p><Link className="bz-button" href={`/workspaces/${workspaceId}/sites/${siteId}/campaigns`}>Content campaigns</Link></p><Link className="bz-button" href={`/workspaces/${workspaceId}/sites/${siteId}/knowledge`}>Open site knowledge</Link><p><Link className="bz-button" href={`/workspaces/${workspaceId}/sites/${siteId}/agents`}>Agent readiness</Link></p><dl><div><dt>Mode</dt><dd>{site.mode.replaceAll("_", " ")}</dd></div><div><dt>Access</dt><dd>{site.mode === "external" ? "Public URL only · no connector grant" : site.mode === "native_business" ? "Private business draft · workspace role applies" : canOpenStudio ? "Your owned portfolio" : "Registry metadata only"}</dd></div><div><dt>Record version</dt><dd>{site.version}</dd></div><div><dt>Site ID</dt><dd className="bz-mono">{site.id}</dd></div></dl>{site.url && <a className="bz-card-link" href={site.url} target="_blank" rel="noopener noreferrer">Visit website<ArrowUpRight size={16} aria-hidden="true" /></a>}<div className="bz-callout"><ShieldCheck size={20} aria-hidden="true" /><p>{site.mode === "native_business" ? "Open the business editor to save a private draft and customize your selected business design. Publish a saved snapshot explicitly from Studio." : site.mode === "external" ? "No remote content has been read or changed. CMS, GitHub and social connections will be added in later phases." : canOpenStudio ? "Studio editing and publishing use the existing portfolio controls and owner permissions." : "Only the original portfolio owner can enter Studio. Linking does not change those permissions."}</p></div></section><section className="bz-panel bz-form-panel"><h2>Manage this record</h2>{canWriteWorkspace(workspace.role) ? <><SiteEditForm site={site} />{workspace.role === "owner" && <DeleteSite site={site} />}</> : <p>Your workspace role is read-only.</p>}</section></div></WorkspaceFrame>;
}
