import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..');const args=process.argv.slice(2);const out=path.resolve(args.includes('--out')?args[args.indexOf('--out')+1]:path.join(root,'tools/phase1-verification/results/browser'));
await mkdir(out,{recursive:true});const servers=[];let browser;const report={scope:'Two unconfigured local production applications; not real Auth/MFA acceptance',checks:[],screenshots:[],errors:[]};
async function start(app,port){const proc=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],{cwd:path.join(root,'apps',app),env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});servers.push(proc);let log='';proc.stdout.on('data',x=>log+=x);proc.stderr.on('data',x=>log+=x);for(let i=0;i<120;i++){try{await fetch(`http://127.0.0.1:${port}/login`);return;}catch{}if(proc.exitCode!==null)throw new Error(`${app} failed: ${log}`);await new Promise(r=>setTimeout(r,250));}throw new Error(`${app} server timeout`);}
const check=s=>report.checks.push(s);const web='http://127.0.0.1:3170',admin='http://127.0.0.1:3171';
try{
 await start('web',3170);await start('admin',3171);
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH||undefined,args:process.env.BROWSER_NO_SANDBOX==='1'?['--no-sandbox']:[]});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',route=>{const u=new URL(route.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)?route.continue():route.abort();});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));
 for(const route of ['/admin','/admin/security','/admin/audit','/api/admin/summary','/api/admin/audit']){const r=await context.request.get(web+route,{maxRedirects:0});assert.equal(r.status(),404);assert.ok(!r.headers().location);check(`Public ${route}:404 without redirect`);}
 await page.goto(web+'/');assert.equal(await page.locator('a[href^="/admin"],a[href*="localhost:3001"],a[href*="127.0.0.1:3171"]').count(),0);check('Public homepage has no admin entry link');
 await page.goto(web+'/bizoveya/docs');assert.ok((await page.locator('body').innerText()).includes('1.7'));await page.getByRole('button',{name:/Switch to dark/i}).click();await page.screenshot({path:path.join(out,'web-docs-dark.png'),fullPage:true});report.screenshots.push('web-docs-dark.png');
 for(const slug of ['23_FOUNDER_MANUAL_TESTING','24_DEPLOYMENT_AND_ENVIRONMENTS','decisions--ADR-0004-separate-admin-application']){const response=await page.goto(web+'/bizoveya/docs/'+slug);assert.equal(response.status(),200);}check('Docs release1.7 and all three new documents respond');
 await page.goto(web+'/workspaces');assert.ok((await page.locator('body').innerText()).includes('unavailable'));check('Public workspace honest unconfigured state retained');
 const entry=await context.request.get(admin+'/',{maxRedirects:0});assert.ok([307,308].includes(entry.status()));assert.equal(entry.headers().location,'/login');check('Admin root redirects locally to its login');
 await page.goto(admin+'/login');assert.ok((await page.locator('body').innerText()).includes('Sign in to administration'));assert.ok((await page.locator('body').innerText()).includes('until Supabase is configured'));assert.equal(await page.locator('nav[aria-label="Administration"]').count(),0);assert.equal(await page.locator('a[href^="/workspaces"],a[href^="/bizoveya"],a[href^="/start"]').count(),0);await page.screenshot({path:path.join(out,'admin-login-desktop.png'),fullPage:true});report.screenshots.push('admin-login-desktop.png');check('Admin login only; no public signup/docs/workspace links');
 for(const route of ['/workspaces','/bizoveya/docs','/start','/projects']){const r=await context.request.get(admin+route);assert.equal(r.status(),404);check(`Admin ${route}:404`);}
 for(const route of ['/api/admin/summary','/api/admin/audit']){const r=await context.request.get(admin+route);assert.equal(r.status(),503);assert.equal((await r.json()).code,'SETUP_REQUIRED');assert.ok(r.headers()['cache-control'].includes('no-store'));const p=await context.request.post(admin+route);assert.equal(p.status(),405);}check('Admin data APIs fail closed and reject unsupported writes');
 await page.goto(admin+'/admin');assert.ok(!(await page.locator('body').innerText()).includes('Admin + MFA verified'));check('No fabricated admin authorization/data');
 await page.setViewportSize({width:390,height:844});await page.goto(admin+'/login');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'admin-login-mobile.png'),fullPage:true});report.screenshots.push('admin-login-mobile.png');check('Admin login mobile fits viewport');
 await page.goto(web+'/bizoveya/docs');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('Web docs mobile fits viewport');assert.equal(report.errors.length,0);report.passed=true;
} catch(e){report.passed=false;report.failure=String(e);process.exitCode=1;}finally{if(browser)await browser.close();for(const proc of servers)proc.kill('SIGTERM');await writeFile(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
