import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..');const args=process.argv.slice(2);const out=path.resolve(args.includes('--out')?args[args.indexOf('--out')+1]:path.join(root,'tools/phase1-verification/results/browser'));
await mkdir(out,{recursive:true});const servers=[];let browser;const report={scope:'Two unconfigured local production applications; business demo and boundary checks, not hosted saved-draft/Auth/MFA acceptance',checks:[],screenshots:[],errors:[]};
async function start(app,port){const proc=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],{cwd:path.join(root,'apps',app),env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});servers.push(proc);let log='';proc.stdout.on('data',x=>log+=x);proc.stderr.on('data',x=>log+=x);for(let i=0;i<120;i++){try{await fetch(`http://127.0.0.1:${port}/login`);return;}catch{}if(proc.exitCode!==null)throw new Error(`${app} failed: ${log}`);await new Promise(r=>setTimeout(r,250));}throw new Error(`${app} server timeout`);}
const check=s=>{report.checks.push(s);console.log(`PASS: ${s}`);};const web='http://127.0.0.1:3170',admin='http://127.0.0.1:3171';
try{
 await start('web',3170);await start('admin',3171);
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH||undefined,args:process.env.BROWSER_NO_SANDBOX==='1'?['--no-sandbox']:[]});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',route=>{const u=new URL(route.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)?route.continue():route.abort();});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));
 for(const route of ['/admin','/admin/security','/admin/audit','/api/admin/summary','/api/admin/audit']){const r=await context.request.get(web+route,{maxRedirects:0});assert.equal(r.status(),404);assert.ok(!r.headers().location);check(`Public ${route}:404 without redirect`);}
 await page.goto(web+'/');assert.equal(await page.locator('a[href^="/admin"],a[href*="localhost:3001"],a[href*="127.0.0.1:3171"]').count(),0);check('Public homepage has no admin entry link');

 await page.goto(web+'/');assert.ok((await page.locator('h1').innerText()).includes('Bring your business'));await page.screenshot({path:path.join(out,'homepage-dark-desktop.png'),fullPage:true});report.screenshots.push('homepage-dark-desktop.png');check('Bizoveya public homepage replaces root Studio with honest current/future capabilities');
 await page.getByRole('button',{name:'Switch to light mode'}).click();await page.reload();assert.equal(await page.locator('.biz-public').getAttribute('data-theme'),'light');await page.screenshot({path:path.join(out,'homepage-light-desktop.png'),fullPage:true});report.screenshots.push('homepage-light-desktop.png');check('Marketing light theme persists on reload');
 await page.getByRole('link',{name:/Create a website/}).click();await page.waitForURL('**/get-started?journey=new');assert.ok(page.url().includes('journey=new'));await page.getByRole('link',{name:/Continue to workspace/}).click();await page.waitForURL('**/workspaces?journey=new');assert.ok(page.url().includes('workspaces?journey=new'));check('New-site journey reaches workspace with explicit selection');
 await page.goto(web+'/templates?category=business');assert.equal(await page.locator('.biz-template-card').count(),3);check('Catalog shows three business presets');await page.goto(web+'/templates?category=portfolio');assert.equal(await page.locator('.biz-template-card').count(),1);check('Portfolio filter preserved');
 for(const slug of ['service-studio','local-services','creative-business']){await page.goto(web+'/templates/'+slug);assert.equal(await page.locator('.business-preview').count(),1);await page.screenshot({path:path.join(out,slug+'-desktop.png'),fullPage:true});report.screenshots.push(slug+'-desktop.png');check(slug+': meaningful modular editor and preview render');}
 await page.goto(web+'/templates/service-studio');await page.getByLabel('Business name',{exact:true}).fill('Founder Test Business');await page.getByLabel('Contact email',{exact:true}).fill('contact@example.com');assert.equal(await page.locator('.business-preview a[href="mailto:contact@example.com"]').count(),1);check('Shared business/contact facts update preview');
 await page.getByRole('button',{name:'01 · Hero',exact:true}).click();await page.getByLabel('Headline',{exact:true}).fill('Approved heading survives design changes');await page.getByLabel('Section layout',{exact:true}).selectOption('centered');assert.equal(await page.locator('[data-section-type="hero"]').getAttribute('data-layout'),'centered');check('Hero layout changes with content preserved');
 await page.getByRole('button',{name:'Business & brand',exact:true}).click();await page.getByLabel('Starting design').selectOption('local-services-v1');assert.ok((await page.locator('[data-section-type="hero"] h2').innerText()).includes('Approved heading'));assert.equal(await page.locator('.business-preview').getAttribute('data-font'),'modern');check('Preset changes composition and tokens without losing headline');
 await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await page.getByLabel('Starting design').inputValue(),'service-studio-v1');await page.getByRole('button',{name:'Redo',exact:true}).click();assert.equal(await page.getByLabel('Starting design').inputValue(),'local-services-v1');check('Preset undo and redo restore exact design state');
 await page.getByLabel('New section').selectOption('testimonials');await page.getByRole('button',{name:'Add section',exact:true}).click();assert.equal(await page.locator('[data-section-type="testimonials"]').count(),1);assert.ok((await page.locator('[data-section-type="testimonials"]').innerText()).includes('genuine customer quotes'));check('Empty testimonial section does not fabricate proof');
 await page.getByRole('button',{name:'Add item',exact:true}).click();await page.getByLabel('Customer / attribution 1',{exact:true}).fill('Test customer A');await page.getByLabel('Quote 1',{exact:true}).fill('Founder-supplied test quote A');await page.getByRole('button',{name:'Add item',exact:true}).click();await page.getByLabel('Customer / attribution 2',{exact:true}).fill('Test customer B');await page.getByLabel('Quote 2',{exact:true}).fill('Founder-supplied test quote B');await page.getByLabel('Section layout').selectOption('slider');assert.ok((await page.locator('.business-quotes').innerText()).includes('quote A'));await page.getByRole('button',{name:'Next testimonial'}).click();assert.ok((await page.locator('.business-quotes').innerText()).includes('quote B'));await page.getByRole('button',{name:'Previous testimonial'}).click();assert.ok((await page.locator('.business-quotes').innerText()).includes('quote A'));check('Manual testimonial slider switches approved quotes and attribution');
 await page.getByLabel('Section layout').selectOption('cards');assert.equal(await page.locator('.business-quotes figure').count(),2);check('Layout switch retains all testimonial items');
 await page.getByRole('button',{name:'Duplicate section',exact:true}).click();assert.equal(await page.locator('[data-section-type="testimonials"]').count(),2);await page.getByRole('button',{name:'Delete section',exact:true}).click();assert.equal(await page.locator('[data-section-type="testimonials"]').count(),1);await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await page.locator('[data-section-type="testimonials"]').count(),2);assert.ok((await page.locator('.business-preview').innerText()).includes('quote A'));check('Duplicate/delete/undo preserve section content');
 await page.getByRole('button',{name:'Hide testimonials-2',exact:true}).click();assert.equal(await page.locator('[data-section-type="testimonials"]').count(),1);await page.getByRole('button',{name:'Show testimonials-2',exact:true}).click();assert.equal(await page.locator('[data-section-type="testimonials"]').count(),2);await page.getByRole('button',{name:'Move testimonials-2 up',exact:true}).click();assert.equal(await page.locator('[data-section-type="testimonials"]').first().getAttribute('id'),'section-testimonials-2');check('Visibility and reorder work by stable section ID');
 await page.getByRole('button',{name:'Business & brand',exact:true}).click();await page.getByLabel('Starting design').selectOption('creative-business-v1');assert.equal(await page.locator('[data-section-type="testimonials"]').count(),2);assert.ok((await page.locator('.business-preview').innerText()).includes('quote A'));check('Preset switch retains extra testimonial sections');
 await context.route('https://assets.example.com/photo.svg',route=>route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="960" height="720"><rect width="960" height="720" fill="#bce8c9"/></svg>'}));
 await page.getByRole('button',{name:'Edit hero section hero',exact:true}).click();await page.getByLabel('Image URL (optional)',{exact:true}).fill('https://assets.example.com/photo.svg');await page.locator('[data-section-type="hero"] img').waitFor();assert.equal(await page.locator('[data-section-type="hero"] img').getAttribute('src'),'https://assets.example.com/photo.svg');check('Optional HTTPS photo renders through direct browser request');
 await page.getByLabel('Image URL (optional)',{exact:true}).fill('javascript:alert(1)');assert.equal(await page.locator('[data-section-type="hero"] img').count(),0);await page.getByLabel('Image URL (optional)',{exact:true}).fill('');check('Unsafe photo reference is not rendered; text-only layout remains');
 await page.getByRole('button',{name:'Edit faq section faq-1',exact:true}).click();await page.getByRole('button',{name:'Add item',exact:true}).click();await page.getByLabel('Question 1',{exact:true}).fill('How can we contact you?');await page.getByLabel('Answer 1',{exact:true}).fill('Use the approved email address.');await page.locator('[data-section-type="faq"] summary').first().click();assert.ok((await page.locator('[data-section-type="faq"] details[open]').innerText()).includes('approved email'));await page.getByLabel('Section layout').selectOption('list');assert.equal(await page.locator('[data-section-type="faq"] details').count(),0);assert.ok((await page.locator('[data-section-type="faq"]').innerText()).includes('approved email'));check('FAQ accordion and list retain question/answer content');
 await page.getByRole('button',{name:'Edit hero section hero',exact:true}).click();await page.getByLabel('Headline',{exact:true}).fill('<script>window.bad=true</script>');assert.equal(await page.evaluate(()=>window.bad),undefined);assert.ok((await page.locator('[data-section-type="hero"] h2').innerText()).includes('<script>'));await page.getByLabel('Headline',{exact:true}).fill('Approved heading survives design changes');check('Escaped owner text cannot execute scripts');
 await page.getByRole('button',{name:'Check demo draft',exact:true}).click();assert.ok((await page.getByRole('status').innerText()).includes('demo is not saved'));const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download draft',exact:true}).click();const download=await downloadPromise;await download.saveAs(path.join(out,'demo-draft.json'));check('Demo explicitly unsaved; valid JSON export works');
 await page.getByRole('button',{name:'Business & brand',exact:true}).click();await page.getByLabel('Business name',{exact:true}).fill('Changed after export');await page.getByLabel('Restore JSON backup',{exact:true}).setInputFiles(path.join(out,'demo-draft.json'));await page.getByRole('status').filter({hasText:'Backup loaded into this editor'}).waitFor();assert.equal(await page.getByLabel('Business name',{exact:true}).inputValue(),'Founder Test Business');assert.equal(await page.locator('[data-section-type="testimonials"]').count(),2);check('Backup restoration restores composition and facts without saving automatically');
 await page.getByRole('button',{name:'Mobile preview',exact:true}).click();assert.ok(await page.locator('.business-preview-wrap').evaluate(el=>el.getBoundingClientRect().width<=390));check('Mobile-width canvas uses responsive container layouts');await page.getByRole('button',{name:'Desktop preview',exact:true}).click();await page.getByRole('button',{name:'Full preview',exact:true}).click();assert.equal(await page.locator('.business-editor').count(),0);assert.equal(await page.locator('.business-select-section').count(),0);await page.getByRole('button',{name:'Back to editor',exact:true}).click();check('Full preview removes inspector and section edit controls');
 page.once('dialog',dialog=>dialog.accept());await page.reload();assert.equal(await page.getByLabel('Business name',{exact:true}).inputValue(),'Northline Studio');check('Public sample resets on reload');
 for(const url of ['/', '/templates', '/get-started?journey=existing','/templates/service-studio','/templates/local-services','/templates/creative-business']){await page.setViewportSize({width:390,height:844});await page.goto(web+url);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await page.screenshot({path:path.join(out,'business-editor-mobile.png'),fullPage:true});report.screenshots.push('business-editor-mobile.png');check('Public gallery and all three editors fit mobile viewport');await page.setViewportSize({width:1440,height:1000});
 const portfolio=await page.goto(web+'/portfolio');assert.equal(portfolio.status(),200);assert.ok((await page.locator('body').innerText()).includes('Voxfolio'));check('Inherited portfolio Studio remains at /portfolio');
 const api=await context.request.get(web+'/api/workspaces/11111111-1111-4111-8111-111111111111/sites/22222222-2222-4222-8222-222222222222/business');assert.equal(api.status(),503);assert.ok(api.headers()['cache-control'].includes('no-store'));check('Business API fails closed without Supabase configuration');
 await page.goto(web+'/bizoveya/docs');assert.ok((await page.locator('body').innerText()).includes('1.9'));if(await page.getByRole('button',{name:/Switch to dark/i}).count())await page.getByRole('button',{name:/Switch to dark/i}).click();await page.screenshot({path:path.join(out,'web-docs-dark.png'),fullPage:true});report.screenshots.push('web-docs-dark.png');
 for(const slug of ['23_FOUNDER_MANUAL_TESTING','24_DEPLOYMENT_AND_ENVIRONMENTS','decisions--ADR-0004-separate-admin-application','25_BUSINESS_BUILDER_AND_TESTING','decisions--ADR-0005-business-entry-and-drafts','26_BUSINESS_TEMPLATES_AND_SECTIONS','decisions--ADR-0006-modular-business-studio']){const response=await page.goto(web+'/bizoveya/docs/'+slug);assert.equal(response.status(),200);}check('Docs release1.9 and all current guides/decisions respond');
 await page.goto(web+'/workspaces');assert.ok((await page.locator('body').innerText()).includes('unavailable'));check('Public workspace honest unconfigured state retained');
 const entry=await context.request.get(admin+'/',{maxRedirects:0});assert.ok([307,308].includes(entry.status()));assert.equal(entry.headers().location,'/login');check('Admin root redirects locally to its login');
 await page.goto(admin+'/login');assert.ok((await page.locator('body').innerText()).includes('Sign in to administration'));assert.ok((await page.locator('body').innerText()).includes('until Supabase is configured'));assert.equal(await page.locator('nav[aria-label="Administration"]').count(),0);assert.equal(await page.locator('a[href^="/workspaces"],a[href^="/bizoveya"],a[href^="/start"]').count(),0);await page.screenshot({path:path.join(out,'admin-login-desktop.png'),fullPage:true});report.screenshots.push('admin-login-desktop.png');check('Admin login only; no public signup/docs/workspace links');
 for(const route of ['/workspaces','/bizoveya/docs','/start','/projects']){const r=await context.request.get(admin+route);assert.equal(r.status(),404);check(`Admin ${route}:404`);}
 for(const route of ['/api/admin/summary','/api/admin/audit']){const r=await context.request.get(admin+route);assert.equal(r.status(),503);assert.equal((await r.json()).code,'SETUP_REQUIRED');assert.ok(r.headers()['cache-control'].includes('no-store'));const p=await context.request.post(admin+route);assert.equal(p.status(),405);}check('Admin data APIs fail closed and reject unsupported writes');
 await page.goto(admin+'/admin');assert.ok(!(await page.locator('body').innerText()).includes('Admin + MFA verified'));check('No fabricated admin authorization/data');
 await page.setViewportSize({width:390,height:844});await page.goto(admin+'/login');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'admin-login-mobile.png'),fullPage:true});report.screenshots.push('admin-login-mobile.png');check('Admin login mobile fits viewport');
 await page.goto(web+'/bizoveya/docs');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('Web docs mobile fits viewport');assert.equal(report.errors.length,0);report.passed=true;report.finishedAt=new Date().toISOString();
} catch(e){report.passed=false;report.failure=String(e);process.exitCode=1;}finally{if(browser)await browser.close();for(const proc of servers)proc.kill('SIGTERM');await writeFile(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
