import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, Boxes, CircleCheck, Command, Compass, FileText, History, Layers3 } from "lucide-react";
import { getDocument, getDocuments } from "@/features/document-room/documents";
import { Explorer } from "@/features/document-room/explorer";
import { ActivityVisual, PhaseVisual, WorkVisual } from "@/features/document-room/visuals";
import { phases, work, latestPackage } from "@/features/document-room/insights";
import { ThemeSwitch } from "@/features/document-room/theme-switch";
import "./document-room.css";

export const metadata: Metadata = { title: { absolute: "Bizoveya | Project intelligence" }, description: "Living plans, progress and guidance for Bizoveya.", robots: { index: false, follow: false } };

export default async function DocumentRoom() {
  const [documents, phase, completed, activity, registry] = await Promise.all([getDocuments(), getDocument("10_PHASES_AND_STATUS"), getDocument("COMPLETED_WORK"), getDocument("ACTIVITY_LOG"), getDocument("PACKAGE_VERSIONS")]);
  const release = latestPackage(registry?.content ?? "");
  const grandPhases = phases(phase?.content ?? "");
  const done = work(completed?.content ?? "");
  const accepted = grandPhases.filter((item) => item.status === "accepted").length;
  return <main className="document-room"><div className="document-room-shell">
    <header className="doc-topbar"><Link href="/bizoveya/docs" className="doc-brand"><span className="doc-brand-symbol"><Boxes size={20} /></span><span><b>BIZOVEYA</b><small>PROJECT INTELLIGENCE</small></span></Link><div className="doc-top-actions"><span className="doc-live"><span /> PUBLIC WORKSPACE</span><ThemeSwitch /><Link href="/" className="doc-site-link">Main site <ArrowUpRight size={15} /></Link></div></header>
    <div className="doc-dashboard-layout"><nav className="doc-dashboard-nav" aria-label="Document room sections"><span>WORKSPACE</span><a href="#overview" className="doc-nav-active"><Compass size={17} /> Overview</a><a href="#roadmap"><Layers3 size={17} /> Phase map</a><a href="#completed"><CircleCheck size={17} /> Completed</a><a href="#activity"><History size={17} /> Activity</a><a href="#library"><BookOpen size={17} /> Document library</a><div className="doc-nav-help"><span><Command size={17} /> SOURCE OF TRUTH</span><p>{documents.length} living Markdown documents power this view. New deliveries update both the code and the record.</p><Link href="/bizoveya/docs/00_INDEX">Start here <ArrowRight size={14} /></Link></div></nav>
      <div className="doc-dashboard-content" id="overview">
        <section className="doc-hero"><div><p className="doc-eyebrow"><span className="doc-signal" /> LIVE PROJECT RECORD <span className="doc-hero-divider">/</span> BIZOVEYA {release?.version ?? "—"}</p><h1>Everything in motion.<br /><em>One clear view.</em></h1><p>Explore the decisions, delivery evidence, roadmap, and guidance behind Bizoveya. Every view is generated from the living project documents.</p><div className="doc-hero-links"><a href="#library" className="doc-primary-action">Explore documents <ArrowRight size={17} /></a><Link href="/bizoveya/docs/10_PHASES_AND_STATUS" className="doc-secondary-action">View roadmap <ArrowUpRight size={16} /></Link></div></div><div className="doc-hero-art" aria-label="Project document overview"><div className="doc-orbit doc-orbit-one" /><div className="doc-orbit doc-orbit-two" /><div className="doc-hero-core"><Boxes size={33} /><span>THE BIZOVEYA<br />KNOWLEDGE CORE</span></div><span className="doc-art-pill doc-art-pill-one"><FileText size={14} /> SOURCE</span><span className="doc-art-pill doc-art-pill-two"><Layers3 size={14} /> PLAN</span><span className="doc-art-pill doc-art-pill-three"><CircleCheck size={14} /> EVIDENCE</span></div></section>
        <section className="doc-metrics" aria-label="Project status"><article><span className="doc-metric-icon"><Layers3 size={19} /></span><span>Grand phases</span><strong>{grandPhases.length.toString().padStart(2, "0")}</strong><small>{accepted} accepted · {grandPhases.length - accepted} await acceptance</small></article><article><span className="doc-metric-icon"><CircleCheck size={19} /></span><span>Completed records</span><strong>{done.length.toString().padStart(2, "0")}</strong><small>Documented deliveries and decisions</small></article><article><span className="doc-metric-icon"><BookOpen size={19} /></span><span>Living documents</span><strong>{documents.length.toString().padStart(2, "0")}</strong><small>Historical archive excluded</small></article><article><span className="doc-metric-icon"><Boxes size={19} /></span><span>Current package</span><strong>{release?.version ?? "—"}</strong><small>{release?.title ?? "No delivery recorded"}</small></article></section>
        <section className="doc-overview-intro"><div><p className="doc-eyebrow">YOUR COMMAND CENTER</p><h2>A clearer way to follow the build.</h2><p>Visual summaries help you find the signal. Open the source document whenever you need the complete context or acceptance limits.</p></div><Link href="/bizoveya/docs/00_INDEX" className="doc-text-link">Reading guide <ArrowUpRight size={16} /></Link></section>
        <div className="doc-dashboard-widgets"><div id="roadmap">{phase && <PhaseVisual content={phase.content} compact />}</div><div className="doc-widget-column"><div id="completed">{completed && <WorkVisual content={completed.content} compact />}</div><div id="activity">{activity && <ActivityVisual content={activity.content} compact />}</div></div></div>
        <section className="doc-library" id="library"><div className="doc-section-heading"><div><p className="doc-eyebrow">EXPLORE THE KNOWLEDGE BASE</p><h2>The document library <span>({documents.length})</span></h2><p>Search across document text and filter by topic. Each page includes its complete Markdown source.</p></div><span className="doc-library-symbol"><BookOpen size={25} /></span></div><Explorer documents={documents} /></section>
      </div></div><footer className="doc-footer"><span>© Bizoveya · Living project documentation</span><span>Source: <code>docs/platform/</code> · Public prelaunch view</span></footer>
  </div></main>;
}
