import {afterEach,describe,expect,it,vi} from 'vitest';
import {testProvider,restrictedFetch} from './provider';import {starterProfile} from '../models/contracts';
afterEach(()=>vi.unstubAllGlobals());
const responses={nebius:{id:'fixture',object:'chat.completion',created:1,model:'fixture',choices:[{index:0,message:{role:'assistant',content:'BIZOVEYA_OK'},finish_reason:'stop'}],usage:{prompt_tokens:13,completion_tokens:4,total_tokens:17}},gemini:{candidates:[{content:{role:'model',parts:[{text:'BIZOVEYA_OK'}]},finishReason:'STOP',index:0}],usageMetadata:{promptTokenCount:13,candidatesTokenCount:4,totalTokenCount:17}},openai:{id:'resp_fixture',object:'response',created_at:1,model:'fixture',status:'completed',output:[{id:'msg_fixture',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'BIZOVEYA_OK',annotations:[]}]}],usage:{input_tokens:13,output_tokens:4,total_tokens:17,input_tokens_details:{cached_tokens:0},output_tokens_details:{reasoning_tokens:0}}}};
describe('actual SDK adapters using local synthetic HTTP responses',()=>{
 for(const provider of ['nebius','openai','gemini'] as const)it(provider+' makes one bounded call and normalizes usage',async()=>{const fetcher=vi.fn(async()=>Response.json(responses[provider]));vi.stubGlobal('fetch',fetcher);const d={...starterProfile(),provider,credentialRef:`platform-${provider}` as const,modelId:'fixture-model'};const result=await testProvider(d,{[`BIZOVEYA_${provider.toUpperCase()}_API_KEY`]:'local-fixture-only'});expect(result).toEqual({code:'response_matched',inputTokens:13,outputTokens:4});expect(fetcher).toHaveBeenCalledTimes(1);const call=fetcher.mock.calls[0] as unknown as [string,RequestInit];expect(call[1].redirect).toBe('error');expect(String(call[1].body)).toContain('128');expect(String(call[1].body)).toContain('BIZOVEYA_OK');});
 it('provider errors are redacted and never retried',async()=>{const f=vi.fn(async()=>Response.json({error:{message:'secret-diagnostic',type:'server_error',code:'error'}},{status:500}));vi.stubGlobal('fetch',f);expect(await testProvider({...starterProfile(),modelId:'fixture'},{BIZOVEYA_NEBIUS_API_KEY:'fixture'})).toEqual({code:'provider_error',inputTokens:null,outputTokens:null});expect(f).toHaveBeenCalledTimes(1);});
 it('unexpected text cannot pass',async()=>{vi.stubGlobal('fetch',async()=>Response.json({...responses.nebius,choices:[{index:0,message:{role:'assistant',content:'Something else'},finish_reason:'stop'}]}));expect((await testProvider({...starterProfile(),modelId:'fixture'},{BIZOVEYA_NEBIUS_API_KEY:'fixture'})).code).toBe('unexpected_response');});
 it('does not fetch arbitrary origins',()=>{const f=vi.fn();vi.stubGlobal('fetch',f);expect(()=>restrictedFetch('https://example.com/')).toThrow('Unsupported');expect(f).not.toHaveBeenCalled();});
});
