'use client';
import Link from 'next/link';
import {useRef,useState} from 'react';
import {registrySchema,type Registry} from '../models/contracts';
import {reportSchema,type TestReport,type TestSetup,type TestRequest} from './contracts';
export function ModelTestsRoom({initial}:{initial:{registry:Registry;report:TestReport;setup:TestSetup}}){
 const [data,setData]=useState(initial),[selected,setSelected]=useState(initial.registry.profiles[0]?.id??''),[reason,setReason]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[retry,setRetry]=useState<TestRequest|null>(null);const lock=useRef(false);
 const p=data.registry.profiles.find(p=>p.id===selected);const c=data.registry.credentials.find(c=>c.id===p?.document.credentialRef);
 const available=data.setup.enabled&&data.setup.recorderConfigured&&!!p&&data.setup.keys[p.document.provider]&&p.checked&&c?.enabled&&data.report.usedToday<data.report.dailyLimit&&!data.report.runs.some(r=>r.status==='running');
 async function refresh(){if(lock.current)return;lock.current=true;setBusy(true);try{const r=await fetch('/api/admin/model-tests',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error??'Refresh failed.');setData({registry:registrySchema.parse(j.registry),report:reportSchema.parse(j.report),setup:j.setup});setMessage('Results refreshed. A connectivity match does not certify output quality.');}catch(e){setMessage(e instanceof Error?e.message:'Refresh failed.');}finally{lock.current=false;setBusy(false);}}
 async function run(){if(lock.current||!p||!c)return;const input=retry??{id:crypto.randomUUID(),profileId:p.id,expectedRevision:p.revision,credentialVersion:c.version,reviewed:true as const,reason:reason.trim()};lock.current=true;setBusy(true);setRetry(input);setMessage('Testing this saved model. Keep this page open.');
 try{const r=await fetch('/api/admin/model-tests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const j=await r.json();if(!r.ok)throw new Error(j.error??'Result unavailable.');setData(d=>({...d,report:reportSchema.parse(j.report)}));setRetry(null);setReviewed(false);setMessage(j.replayed?'This request was already recorded; no second provider call was made.':'Result recorded below. Review its status before continuing.');}catch(e){setMessage((e instanceof Error?e.message:'Result unavailable.')+' Refresh to inspect the record. Retrying the same request does not create a second recorded attempt; an interrupted provider request may still be billed.');}finally{lock.current=false;setBusy(false);}}
 return <section className="ba-agent-room"><p className="ba-eyebrow">MODEL CONNECTIVITY</p><h1>Test a saved model</h1><p>Confirm that your chosen model returns a short expected response. Customer content is never included in this test.</p><p><Link href="/admin/spending">Review spending controls</Link> · <Link href="/admin/models">Manage model profiles</Link> · <Link href="/admin/credentials">Manage credential references</Link></p>
 <div className="ba-notice"><strong>{data.setup.enabled?'Live testing enabled':'Live testing disabled'}</strong><p>{data.report.usedToday}/{data.report.dailyLimit} attempts used today (UTC), shared across all admins and providers. Each attempt makes at most one request, asks for up to128 output tokens, and stops waiting after20 seconds. Provider charges can apply even on failures. New tests also require an enabled, current pricing policy. The server reserves a conservative USD estimate and enforces per-run/daily limits before dispatch. Provider billing is the final source of actual charges.</p><p>Recording key: {data.setup.recorderConfigured?'configured':'missing'}. Enable testing only after server setup. No automatic fallback, retry, agent activation or publishing occurs.</p></div>
 <fieldset disabled={busy||!!retry}><label htmlFor="test-profile">Saved model profile<select id="test-profile" aria-label="Saved model profile" value={selected} onChange={e=>{setSelected(e.target.value);setReviewed(false);}}><option value="" disabled>Select a profile</option>{data.registry.profiles.map(x=><option key={x.id} value={x.id}>{x.document.name} · v{x.version}</option>)}</select></label>{p&&<p>{p.document.provider} / {p.document.modelId} · {p.checked?'Configuration checked':'Check configuration first'} · provider key {data.setup.keys[p.document.provider]?'present':'missing'} · reference v{c?.version}</p>}<label htmlFor="test-reason">Test reason<textarea id="test-reason" value={reason} onChange={e=>setReason(e.target.value)} maxLength={300} placeholder="Verify this model before the draft pilot. No secrets here."/></label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I authorize this provider request and have checked the model’s pricing in my provider account.</label></fieldset>
 <div className="ba-agent-actions"><button disabled={busy||(!retry&&(!available||!reviewed||reason.trim().length<10))} onClick={()=>void run()}>{busy?'Working…':retry?'Retry same request':'Run paid connectivity test'}</button><button disabled={busy} onClick={()=>void refresh()}>Refresh results</button>{retry&&<button disabled={busy} onClick={()=>{setRetry(null);setReviewed(false);setMessage('Retry cleared. Review recorded attempts before authorizing a new test.');}}>Clear retry</button>}</div><p role="status">{message}</p>
 <h2>Latest 50 attempts</h2>{!data.report.runs.length&&<p>No model tests have been recorded.</p>}{data.report.runs.map(r=><article key={r.id}><h3>{r.provider} / {r.model_id}</h3><p><strong>{r.status}</strong> · {r.current?'Matches current profile/reference':'Historical or not qualified'} · {r.result_code??(r.status==='unknown'?'Result unconfirmed; check provider usage':'Awaiting result')}</p><p>Profile v{r.profile_version} · reference v{r.credential_version} · input tokens {r.input_tokens??'unknown'} · output tokens {r.output_tokens??'unknown'}</p><p>{r.reason}</p><p>{r.adapter_version} · Started {r.started_at} · completed {r.finished_at??'unconfirmed'}</p><p>Actor {r.actor_id??'deleted account'} · run {r.id}</p></article>)}<p>A passing response checks this exact model/profile/reference version only. It does not prove tool use, structured outputs, factual accuracy, pricing or hackathon eligibility. Editing the profile or changing its reference makes earlier results historical. Actual key changes must also be recorded as a reference rotation.</p></section>;
}
