import {describe,it,expect,vi} from 'vitest';import type {SupabaseClient} from '@supabase/supabase-js';import {executeTest} from './store';import {executionSetup,requestSchema} from './contracts';import {starterProfile} from '../models/contracts';
const id='11111111-1111-4111-8111-111111111111',pid='22222222-2222-4222-8222-222222222222';const request={id,profileId:pid,expectedRevision:2,credentialVersion:2,reviewed:true as const,reason:'Verify the first test model'};
function fixtures(replay=false){const document={...starterProfile(),name:'Fixture',modelId:'fixture'};const rpc=vi.fn(async(name:string)=>({error:null,data:name==='bz_admin_identity'?{isAdmin:true,aal2:true}:name==='bz_admin_model_registry'?{profiles:[{id:pid,slug:'fixture',version:1,revision:2,document,checked:true}],credentials:[{id:'platform-nebius',provider:'nebius',enabled:true,version:2}]}:name==='bz_admin_begin_model_test'?replay?{execute:false,id}:{execute:true,id,document}:{dailyLimit:5,usedToday:1,runs:[]}}));const recorderRpc=vi.fn(async()=>({error:null,data:null}));const provider=vi.fn(async()=>({code:'response_matched' as const,inputTokens:13,outputTokens:4}));return {db:{rpc} as unknown as SupabaseClient,rpc,recorderRpc,provider,deps:{env:{BIZOVEYA_ENABLE_MODEL_TESTS:'true',BIZOVEYA_NEBIUS_API_KEY:'fixture-only',SUPABASE_SERVICE_ROLE_KEY:'fixture-recorder-only'},recorder:{rpc:recorderRpc} as unknown as SupabaseClient,provider}};}
describe('bounded test orchestration',()=>{
 it.each(['bz_run_budget','bz_daily_budget','bz_spending_not_ready','bz_spending_unresolved','bz_pricing_expired'])('blocks %s before contacting the provider',async message=>{const f=fixtures();const original=f.rpc.getMockImplementation()!;f.rpc.mockImplementation(async name=>name==='bz_admin_begin_model_test'?{error:{message},data:null} as never:original(name));await expect(executeTest(f.db,request,f.deps)).rejects.toMatchObject({code:'SPENDING_BLOCKED'});expect(f.provider).not.toHaveBeenCalled();expect(f.recorderRpc).not.toHaveBeenCalled();});

 it('rejects extra prompt/endpoint fields and missing consent',()=>{expect(requestSchema.safeParse({...request,prompt:'arbitrary'}).success).toBe(false);expect(requestSchema.safeParse({...request,reviewed:false}).success).toBe(false);});
 it('returns only booleans for setup',()=>{const data=executionSetup({BIZOVEYA_OPENAI_API_KEY:'secret',SUPABASE_SERVICE_ROLE_KEY:'another',BIZOVEYA_ENABLE_MODEL_TESTS:'true'});expect(JSON.stringify(data)).not.toContain('secret');expect(data.keys.openai).toBe(true);});
 it('disabled execution makes no RPC or provider call',async()=>{const f=fixtures();f.deps.env.BIZOVEYA_ENABLE_MODEL_TESTS='false';await expect(executeTest(f.db,request,f.deps)).rejects.toMatchObject({code:'TESTS_DISABLED'});expect(f.rpc).not.toHaveBeenCalled();expect(f.provider).not.toHaveBeenCalled();});
 it('requires recording credentials before consuming an attempt',async()=>{const f=fixtures();f.deps.env.SUPABASE_SERVICE_ROLE_KEY='';await expect(executeTest(f.db,request,f.deps)).rejects.toMatchObject({code:'RECORDER_REQUIRED'});expect(f.rpc).not.toHaveBeenCalled();});
 it('idempotent replay never reaches the provider or recorder',async()=>{const f=fixtures(true);expect((await executeTest(f.db,request,f.deps)).replayed).toBe(true);expect(f.provider).not.toHaveBeenCalled();expect(f.recorderRpc).not.toHaveBeenCalled();});
 it('records through the privileged client and never returns key/claim',async()=>{const f=fixtures();const r=await executeTest(f.db,request,f.deps);expect(f.provider).toHaveBeenCalledTimes(1);expect(f.recorderRpc).toHaveBeenCalledTimes(1);expect(JSON.stringify(r)).not.toContain('fixture-only');expect(f.rpc.mock.calls.some(x=>x[0]==='bz_finish_model_test')).toBe(false);});
 it('recording failure is surfaced without repeating the provider request',async()=>{const f=fixtures();f.recorderRpc.mockResolvedValueOnce({error:{code:'PGRST202',message:'not present'},data:null} as never);await expect(executeTest(f.db,request,f.deps)).rejects.toMatchObject({code:'SETUP_REQUIRED'});expect(f.provider).toHaveBeenCalledTimes(1);});
});
