import { describe, it, expect } from "vitest";
import { applyPreset, businessDocumentSchema, businessPresets, imageSchema, legacyBusinessSchema, makeSection, newBusinessDocument, sampleBusiness, sampleForPreset, saveBusinessSchema, sectionCatalog, sectionTypes, storedBusinessSchema, uniqueSectionId } from "./business";
describe("modular business document boundary", () => {
  it("accepts all presets without fabricated contact details", () => { for (const p of businessPresets) { const d = businessDocumentSchema.parse(sampleForPreset(p.id)); expect(d.email).toBe(""); expect(d.sections.some(s => s.type === "testimonials")).toBe(false); } });
  it.each([{ templateId: "arbitrary" }, { accent: "javascript:alert(1)" }, { email: "javascript:alert(1)" }, { services: [] }, { name: " " }, { schemaVersion: 3 }, { script: "payload" }])("rejects unsafe or unsupported fields %j", patch => expect(businessDocumentSchema.safeParse({ ...sampleBusiness,...patch }).success).toBe(false));
  it("preserves every legacy field while upgrading without changing the saved version", () => { const base = Object.fromEntries(Object.entries(sampleBusiness).filter(([key]) => !["font","hours","sections"].includes(key))); const legacy = legacyBusinessSchema.parse({ ...base,schemaVersion:1 }); const upgraded = storedBusinessSchema.parse(legacy); for (const [key,value] of Object.entries(legacy)) if (key !== "schemaVersion") expect(upgraded[key as keyof typeof upgraded]).toEqual(value); expect(upgraded.sections.map(s => s.type)).toEqual(["hero","services","about","contact"]); expect(upgraded.schemaVersion).toBe(2); });
  it("preserves text, extra sections, IDs and photos through preset changes", () => { const extra = { ...makeSection("testimonials","reviews"),items:[{title:"Approved person",body:"Approved quote",image:"https://example.com/photo.jpg"}] }; const d = { ...sampleBusiness,sections:[...sampleBusiness.sections,extra] }; for (const p of businessPresets) { const changed = applyPreset(d,p.id); expect(changed.services).toEqual(d.services); expect(changed.headline).toBe(d.headline); expect(changed.sections.find(s => s.id === "reviews")).toEqual(extra); for (const s of d.sections) expect(changed.sections.find(n => n.id === s.id)?.items).toEqual(s.items); expect(businessDocumentSchema.safeParse(changed).success).toBe(true); } });
  it("refuses a full-page preset switch rather than dropping owner content", () => { const d = { ...sampleBusiness,sections:Array.from({length:20},(_,i) => makeSection("hero",`hero-${i}`)) }; expect(() => applyPreset(d,"creative-business-v1")).toThrow("content has not changed"); expect(d.sections).toHaveLength(20); });
  it("validates every registered layout and rejects wrong type/layout pairings", () => { for (const type of sectionTypes) for (const layout of sectionCatalog[type].layouts) expect(businessDocumentSchema.safeParse({ ...sampleBusiness,sections:[{...makeSection(type,type),layout}] }).success).toBe(true); expect(businessDocumentSchema.safeParse({ ...sampleBusiness,sections:[{...makeSection("hero","hero"),layout:"accordion"}] }).success).toBe(false); });
  it("requires unique IDs and bounds sections, services and item content", () => { const s = makeSection("faq","faq"); expect(businessDocumentSchema.safeParse({...sampleBusiness,sections:[s,s]}).success).toBe(false); expect(businessDocumentSchema.safeParse({...sampleBusiness,sections:[]}).success).toBe(false); expect(businessDocumentSchema.safeParse({...sampleBusiness,services:Array(7).fill(sampleBusiness.services[0])}).success).toBe(false); expect(businessDocumentSchema.safeParse({...sampleBusiness,sections:[{...s,items:Array(9).fill({title:"q",body:"a",image:""})}]}).success).toBe(false); expect(businessDocumentSchema.safeParse({...sampleBusiness,about:"x".repeat(1501)}).success).toBe(false); });
  it.each(["javascript:alert(1)","http://example.com/x","data:image/svg+xml,x","https://user:password@example.com/x","https://localhost/x","https://127.0.0.1/x","https://example.com/a b"])("rejects unsafe image references %s",url => expect(imageSchema.safeParse(url).success).toBe(false));
  it("accepts optional HTTPS photos and generates collision-free IDs", () => { expect(imageSchema.parse("")).toBe(""); expect(imageSchema.parse("https://example.com/a.jpg")).toContain("https://"); expect(uniqueSectionId("faq",[makeSection("faq","faq-1")])).toBe("faq-2"); });
  it("bounds the whole UTF-8 document and concurrency version", () => { const sections = Array.from({length:20},(_,i) => ({ ...makeSection("projects",`projects-${i}`),items:Array(8).fill({title:"project",body:"a".repeat(600),image:""}) })); expect(businessDocumentSchema.safeParse({...sampleBusiness,sections}).success).toBe(false); for (const expectedVersion of [-1,1.5,"0"]) expect(saveBusinessSchema.safeParse({document:sampleBusiness,expectedVersion}).success).toBe(false); expect(saveBusinessSchema.parse({document:newBusinessDocument("Acme"),expectedVersion:0}).expectedVersion).toBe(0); });
});
